XD2031 pcserver: curl_provider.c File Reference
curl_provider.c File Reference
#include <curl/curl.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stdio.h>
#include "wireformat.h"
#include "provider.h"
#include "log.h"
Data Structures
struct File
struct curl_endpoint_t
Macros
#define DEBUG_CURL
#define MAX_BUFFER_SIZE 64
#define MAX_PROTO_SIZE 11
#define MAX_SESSIONS 10
Typedefs
typedef struct File File
Enumerations
enum proto_t { PROTO_FTP, PROTO_FTPS, PROTO_HTTP, PROTO_HTTPS }
Functions
static void curl_init ()
static void init_fp (File *fp)
static curl_endpoint_t * new_endpoint (const char *path)
static curl_endpoint_t * _new (const char *path)
static endpoint_t * ftp_new (endpoint_t *parent, const char *path)
static endpoint_t * http_new (endpoint_t *parent, const char *path)
static File * find_file (endpoint_t *ep, int chan)
static void close_fd (File *fp)
static File * reserve_file (endpoint_t *ep, int chan)
void prov_free (endpoint_t *ep)
static void close_fds (endpoint_t *ep, int tfd)
static size_t write_cb (char *ptr, size_t size, size_t nmemb, void *user)
static CURLMcode pull_data (curl_endpoint_t *cep, File *fp, int *eof)
static int reply_with_data (curl_endpoint_t *cep, File *fp, char *retbuf, int len, int *eof)
static int read_file (endpoint_t *ep, int tfd, char *retbuf, int len, int *eof)
static File * open_file (endpoint_t *ep, int tfd, const char *buf, int is_dir)
static int open_rd (endpoint_t *ep, int tfd, const char *buf)
int dir_nlst_read_converter (struct curl_endpoint_t *cep, File *fp, char *retbuf, int len, int *eof)
static int open_dr (endpoint_t *ep, int tfd, const char *buf)
int do_chdir (endpoint_t *ep, char *name)
Variables
provider_t ftp_provider
provider_t http_provider
Macro Definition Documentation
#define DEBUG_CURL
Definition at line 46 of file curl_provider.c.
#define MAX_BUFFER_SIZE 64
Definition at line 48 of file curl_provider.c.
Referenced by do_chdir(), new_endpoint(), and open_file().
#define MAX_PROTO_SIZE 11
Definition at line 50 of file curl_provider.c.
#define MAX_SESSIONS 10
Definition at line 52 of file curl_provider.c.
Referenced by find_file(), new_endpoint(), prov_free(), and reserve_file().
Typedef Documentation
typedef struct File File
Enumeration Type Documentation
enum proto_t
Enumerator:
PROTO_FTP
PROTO_FTPS
PROTO_HTTP
PROTO_HTTPS
Definition at line 60 of file curl_provider.c.
             {
    PROTO_FTP,
    PROTO_FTPS,
    PROTO_HTTP,
    PROTO_HTTPS
} proto_t;
Function Documentation
static curl_endpoint_t* _new (const char * path) static
Definition at line 149 of file curl_provider.c.
References new_endpoint().
Referenced by ftp_new(), and http_new().
{
    curl_endpoint_t *fsep = new_endpoint(path);
    return fsep;
}
static void close_fd (File * fp) static
Definition at line 192 of file curl_provider.c.
References File::buffer, init_fp(), File::multi, File::name_buffer, and File::session.
Referenced by close_fds(), prov_free(), and reserve_file().
{
    if (fp->session != NULL) {
        curl_multi_remove_handle(fp->multi, fp->session);
        curl_easy_cleanup(fp->session);
        curl_multi_cleanup(fp->multi);
        if (fp->buffer != NULL) {
            free(fp->buffer);
        }
        init_fp(fp);
    }
    if (fp->name_buffer != NULL) {
        free(fp->name_buffer);
        fp->name_buffer = NULL;
    }
}
static void close_fds (endpoint_t * ep, int tfd) static
Definition at line 244 of file curl_provider.c.
References close_fd(), find_file(), log_warn(), and File::session.
{
    File *fp = find_file(ep, tfd);
    if (fp != NULL) {
        if (fp->session == NULL) {
            log_warn("curl sesion %d is NULL!", tfd);
        } else {
            close_fd(fp);
        }
    }
}
static void curl_init () static
Definition at line 97 of file curl_provider.c.
{
    // according to the curl man page, this init can be done multiple times
    CURLcode cc = curl_global_init(CURL_GLOBAL_ALL);
    if (cc != 0) {
        // error handling!
    }
}
int dir_nlst_read_converter (struct curl_endpoint_t * cep, File * fp, char * retbuf, int len, int * eof)
converts the list of file names from an FTP NLST command to a wireformat dir entry.
Because of the FS_DIR_* macros used here, the wireformat.h include is required, which I would like to have avoided...
Definition at line 496 of file curl_provider.c.
References File::bufdatalen, File::buffer, File::bufrp, ERROR_DIR_ERROR, ERROR_FAULT, ERROR_FILE_NAME_TOO_LONG, FS_DIR_MOD_FIL, FS_DIR_MOD_FRE, FS_DIR_MOD_NAM, FS_DIR_MODE, FS_DIR_NAME, log_debug(), log_error(), File::name_buffer, pull_data(), and File::read_state.
Referenced by open_dr().
{
    if (len < FS_DIR_NAME + 1) {
        log_error("read buffer too small for dir entry (is %d, need at least %d)\n",
                len, FS_DIR_NAME+1);
        return -ERROR_FAULT;
    }
    // prepare dir entry
    memset(retbuf, 0, FS_DIR_NAME+1);
    int l = 0;
    char *namep = retbuf + FS_DIR_NAME;
    switch(fp->read_state) {
    case 0:     // disk name
        retbuf[FS_DIR_MODE] = FS_DIR_MOD_NAM;
        l = strlen(fp->name_buffer);
        if (len < FS_DIR_NAME + l + 1) {
            log_error("read buffer too small for dir name (is %d, need at least %d)\n",
                len, l+FS_DIR_NAME+1);
            return -ERROR_FILE_NAME_TOO_LONG;
        }
        strncpy(retbuf, fp->name_buffer, l+1);
        l = l + FS_DIR_NAME + 1;
        fp->read_state++;
        break;
    case 1:
        // file names
#ifdef DEBUG_CURL
        log_debug("get filename, bufdatalen=%d, bufrp=%d, eof=%d\n",
            fp->bufdatalen, fp->bufrp, *eof);
#endif
        l = FS_DIR_NAME;
        retbuf[FS_DIR_MODE] = FS_DIR_MOD_FIL;
        do {
            while ((fp->bufdatalen <= fp->bufrp) && (*eof == 0)) {
                //log_debug("Trying to pull...\n");
                CURLMcode rv = pull_data((curl_endpoint_t*)cep, fp, eof);
                if (rv != CURLM_OK) {
                    log_error("Error retrieving directory data (%d)\n", rv);
                    return -ERROR_DIR_ERROR;
                }
            }
            // find length of name
            while (fp->bufrp < fp->bufdatalen) {
                char c = fp->buffer[fp->bufrp];
                fp->bufrp ++;
                if (c == 13) {
                    // ignore
                } else
                if (c != 10) {
                    *namep = c;
                    namep++;
                    l++;
                } else {
                    // end of name
                    *namep = 0;
                    l++;
#ifdef DEBUG_CURL
                    log_debug("bufrp=%d, datalen=%d\n", fp->bufrp, fp->bufdatalen);
#endif
                    break;
                }
                if (len < FS_DIR_NAME + l + 1) {
                    log_error("read buffer too small for dir name (is %d, need at least %d)\n",
                        len, l+FS_DIR_NAME+1);
                    return -ERROR_FILE_NAME_TOO_LONG;
                }
            }
            if (*eof != 0) {
                log_debug("end of dir read\n");
                fp->read_state++;
                *namep = 0;
            }
        }
        while (*namep != 0 && *eof == 0);   // not null byte, then not done
        *eof = 0;
        if (l > FS_DIR_NAME) {
            break;
        }
        // otherwise fall through
    case 2:
        log_debug("final dir entry\n");
        retbuf[FS_DIR_MODE] = FS_DIR_MOD_FRE;
        retbuf[FS_DIR_NAME] = 0;
        l = FS_DIR_NAME + 1;
        *eof = 1;
        fp->read_state++;
        break;
    }
#ifdef DEBUG_CURL
    printf("Got some dir data : datalen=%d\n", l);
        for (int i = 0; i < FS_DIR_NAME; i++) {
            printf("%02x ", retbuf[i]);
        }
        printf(": %s\n", retbuf+FS_DIR_NAME);
#endif
    return l;
}
int do_chdir (endpoint_t * ep, char * name)
Definition at line 659 of file curl_provider.c.
References ERROR_FILE_NAME_TOO_LONG, ERROR_OK, log_debug(), log_error(), MAX_BUFFER_SIZE, provider_t::name, and curl_endpoint_t::path_buffer.
{
    // change into new dir
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    log_debug("CHDIR: Current path is '%s', name is '%s'\n", cep->path_buffer, name);
    // path buffer is a static buffer, so we can check it in-place
    char *curpath = cep->path_buffer;
    if (name[0] == '/') {
        // absolute path - just copy over old path
        strncpy(cep->path_buffer, name, MAX_BUFFER_SIZE);
        cep->path_buffer[MAX_BUFFER_SIZE-1] = 0;
        return 0;
    }
    // pointer in name
    char *p = name;
    do {
        int plen = strlen(p);
        int l = strlen(cep->path_buffer);
        if ( ((plen > 1) && p[0] == '.' && p[1] == '.')
        && (plen == 2 || p[2] == '/')) {
        // one dir up
        // remove the last path element
        while (l > 0) {
            if (cep->path_buffer[l] == '/') {
                break;
            }
            l--;
        }
        cep->path_buffer[l] = 0;
        // advance to next path part
        plen = (plen > 2) ? 3 : 2;
        } else {
        // append new path part
        // find end of next part
        for (plen = 0; p[plen] != 0; plen++) {
            if (p[plen] == '/') {
                break;
            }
        }
        if (plen + l + 1 > MAX_BUFFER_SIZE) {
            log_error("new path for chdir too long: %d\n", plen+l+1);
            return ERROR_FILE_NAME_TOO_LONG;
        }
        strcat(cep->path_buffer, "/");
        strncat(cep->path_buffer, p, plen);
        cep->path_buffer[MAX_BUFFER_SIZE-1] = 0;
        if(p[plen] == '/') plen++;
        }
        p = p+plen;
    } while(*p != 0);
    log_debug("CHDIR: New path is '%s'\n", cep->path_buffer);
    return ERROR_OK;
}
static File* find_file (endpoint_t * ep, int chan) static
Definition at line 180 of file curl_provider.c.
References File::chan, curl_endpoint_t::files, log_warn(), and MAX_SESSIONS.
Referenced by close_fds(), and read_file().
{
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    for (int i = 0; i < MAX_SESSIONS; i++) {
        if (cep->files[i].chan == chan) {
            return &(cep->files[i]);
        }
    }
    log_warn("Did not find curl session for channel=%d\n", chan);
    return NULL;
}
static endpoint_t* ftp_new (endpoint_t * parent, const char * path) static
Definition at line 156 of file curl_provider.c.
References _new(), PROTO_FTP, curl_endpoint_t::protocol, and curl_endpoint_t::ptype.
{
    curl_endpoint_t *fsep = _new(path);
    // not sure if this is needed...
    fsep->protocol = PROTO_FTP;
    fsep->ptype = (struct provider_t *) &ftp_provider;
    return (endpoint_t*) fsep;
}
static endpoint_t* http_new (endpoint_t * parent, const char * path) static
Definition at line 168 of file curl_provider.c.
References _new(), PROTO_HTTP, curl_endpoint_t::protocol, and curl_endpoint_t::ptype.
{
    curl_endpoint_t *fsep = _new(path);
    // not sure if this is needed...
    fsep->protocol = PROTO_HTTP;
    fsep->ptype = (struct provider_t *) &http_provider;
    return (endpoint_t*) fsep;
}
static void init_fp (File * fp) static
Definition at line 105 of file curl_provider.c.
References File::bufdatalen, File::buffer, File::buflen, File::bufrp, File::chan, File::multi, File::name_buffer, File::read_converter, File::read_state, and File::session.
Referenced by close_fd(), new_endpoint(), and reserve_file().
{
    fp->chan = -1;
    fp->session = NULL;
    fp->multi = NULL;
    fp->buffer = NULL;
    fp->buflen = 0;
    fp->bufdatalen = 0;
    fp->bufrp = 0;
    fp->read_converter = NULL;
    fp->read_state = 0;
    fp->name_buffer = NULL;
}
static curl_endpoint_t* new_endpoint (const char * path) static
Definition at line 119 of file curl_provider.c.
References curl_endpoint_t::error_buffer, curl_endpoint_t::files, curl_endpoint_t::host_buffer, init_fp(), MAX_BUFFER_SIZE, MAX_SESSIONS, curl_endpoint_t::name_buffer, and curl_endpoint_t::path_buffer.
Referenced by _new().
{
    curl_endpoint_t *fsep = malloc(sizeof(curl_endpoint_t));
    for (int i = 0; i < MAX_SESSIONS; i++) {
        File *fp = &(fsep->files[i]);
        init_fp(fp);
    }
    fsep->error_buffer[0] = 0;
    fsep->name_buffer[0] = 0;
    fsep->path_buffer[0] = 0;
    fsep->host_buffer[0] = 0;
    // separate host from path
    // if hostend is NULL, then we only have the host
    char *hostend=index(path, '/');
    int hostlen = strlen(path);
    if (hostend != NULL) {
        hostlen = hostend - path;
    }
    strncpy(fsep->host_buffer, path, hostlen);
    fsep->host_buffer[hostlen] = 0;
    strncpy(fsep->path_buffer, path+hostlen+1, MAX_BUFFER_SIZE);
    fsep->path_buffer[MAX_BUFFER_SIZE-1] = 0;
    return fsep;
}
static int open_dr (endpoint_t * ep, int tfd, const char * buf) static
Definition at line 602 of file curl_provider.c.
References dir_nlst_read_converter(), ERROR_FAULT, ERROR_OK, File::multi, File::name_buffer, curl_endpoint_t::name_buffer, open_file(), File::read_converter, File::session, and write_cb().
{
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    File *fp = open_file(ep, tfd, buf, 1);
    if (fp != NULL) {
        int namelen = strlen(buf);
        fp->name_buffer = malloc(namelen + 1);
        strncpy(fp->name_buffer, buf, namelen + 1);
        fp->read_converter = &dir_nlst_read_converter;  // do DIR conversion
        // set for receiving
        curl_easy_setopt(fp->session, CURLOPT_WRITEFUNCTION, write_cb);
        // TODO: support for MLST/MLSD FTP commands,
        // only they are so new, I still need to find a running one for tests
        //
        // NLST is the "name list" without other data
        strcpy(cep->name_buffer, "NLST ");
        strcpy(cep->name_buffer + strlen(cep->name_buffer), buf);
        // custom FTP command to make info more grokable
        curl_easy_setopt(fp->session, CURLOPT_CUSTOMREQUEST, &(cep->name_buffer));
        //add to multi session
        CURLMcode rv = curl_multi_add_handle(fp->multi, fp->session);
        printf("multi add returns %d\n", rv);
        return ERROR_OK;
    }
    return ERROR_FAULT;
}
static File* open_file (endpoint_t * ep, int tfd, const char * buf, int is_dir) static
Definition at line 406 of file curl_provider.c.
References curl_endpoint_t::error_buffer, curl_endpoint_t::host_buffer, log_error(), log_info(), MAX_BUFFER_SIZE, File::multi, curl_endpoint_t::name_buffer, curl_endpoint_t::path_buffer, curl_endpoint_t::ptype, reserve_file(), and File::session.
Referenced by open_dr(), and open_rd().
{
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    File *fp = reserve_file(ep, tfd);
    if (fp != NULL) {
        // create session
        fp->multi = curl_multi_init();
        if (fp->multi == NULL) {
            log_error("multi session is NULL\n");
            return NULL;
        }
        fp->session = curl_easy_init();
        if (fp->session == NULL) {
            log_error("easy session is NULL\n");
            curl_multi_cleanup(fp->multi);
            return NULL;
        }
        // set options
        curl_easy_setopt(fp->session, CURLOPT_VERBOSE, (long)1);
        //curl_easy_setopt(fp->session, CURLOPT_WRITEFUNCTION, write_cb);
        curl_easy_setopt(fp->session, CURLOPT_WRITEDATA, fp);
        //curl_easy_setopt(fp->session, CURLOPT_READFUNCTION, read_cb);
        curl_easy_setopt(fp->session, CURLOPT_READDATA, fp);
        curl_easy_setopt(fp->session, CURLOPT_ERRORBUFFER, &(cep->error_buffer));
        // prepare name
        strcpy(cep->name_buffer, ((provider_t*)(cep->ptype))->name);
        strcat(cep->name_buffer, "://");
        strcat(cep->name_buffer, cep->host_buffer);
        strcat(cep->name_buffer, "/");
        strcat(cep->name_buffer, cep->path_buffer);
        strcat(cep->name_buffer, "/");
        strcat(cep->name_buffer, buf);
        if (is_dir) {
            // end with a slash "/" to indicate a dir list
            strcpy(cep->name_buffer + strlen(cep->name_buffer), "/");
        }
        log_info("curl URL: %s\n", cep->name_buffer);
        // set URL
        curl_easy_setopt(fp->session, CURLOPT_URL, &(cep->name_buffer));
        // debatable...
        curl_easy_setopt(fp->session, CURLOPT_BUFFERSIZE, (long) MAX_BUFFER_SIZE);
        // add to multi session
        //curl_multi_add_handle(fp->multi, fp->session);
    }
    return fp;
}
static int open_rd (endpoint_t * ep, int tfd, const char * buf) static
Definition at line 463 of file curl_provider.c.
References ERROR_FAULT, ERROR_OK, File::multi, open_file(), File::session, and write_cb().
{
    File *fp = open_file(ep, tfd, buf, 0);
    if (fp != NULL) {
        // set for receiving
        curl_easy_setopt(fp->session, CURLOPT_WRITEFUNCTION, write_cb);
// HTTP
//  curl_easy_setopt(curl_handle, CURLOPT_USERAGENT, "libcurl-agent/1.0");
        // protocol specific stuff
        //if (fp->protocol == FTP) {
        //  // FTP append
        //  curl_easy_setopt(fp->session, CURLOPT_APPEND);
        //}
        //add to multi session
        CURLMcode rv = curl_multi_add_handle(fp->multi, fp->session);
        printf("multi add returns %d\n", rv);
        return ERROR_OK;
    }
    return ERROR_FAULT;
}
void prov_free (endpoint_t * ep)
Definition at line 227 of file curl_provider.c.
References File::chan, close_fd(), curl_endpoint_t::files, log_warn(), MAX_SESSIONS, and File::session.
{
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    int i;
        for(i=0;i<MAX_SESSIONS;i++) {
        File *fp = &(cep->files[i]);
        if (fp->session != NULL) {
            log_warn("curl session %d is not NULL on free!", fp->chan);
        }
        close_fd(&(cep->files[i]));
        }
    free(ep);
}
static CURLMcode pull_data (curl_endpoint_t * cep, File * fp, int * eof) static
Definition at line 290 of file curl_provider.c.
References File::bufdatalen, File::bufrp, curl_endpoint_t::error_buffer, log_debug(), log_error(), and File::multi.
Referenced by dir_nlst_read_converter(), read_file(), and reply_with_data().
{
    int running_handles = 0;
    *eof = 0;
    fp->bufdatalen = 0;
    fp->bufrp = 0;
    CURLMcode rv = CURLM_OK;
    do {
        rv = curl_multi_perform(fp->multi, &running_handles);
#ifdef DEBUG_CURL
        if (rv != 0 || running_handles != 1) {
            printf("curl read file returns: %d, running=%d\n", rv, running_handles);
        }
#endif
    } while (rv == CURLM_CALL_MULTI_PERFORM);
    if (running_handles == 0) {
        // no more data will be available
        log_debug("pull_data sets EOF (running=0), rv=%d, datalen=%d\n", rv, fp->bufdatalen);
        *eof = 1;
    }
    int msgs_in_queue = 0;
    CURLMsg *cmsg = NULL;
    while ((cmsg = curl_multi_info_read(fp->multi, &msgs_in_queue)) != NULL) {
#ifdef DEBUG_CURL
        printf("cmsg=%p, in queue=%d\n", (void*)cmsg, msgs_in_queue);
#endif
        // we only added one easy handle, so easy_handle is known
        CURLMSG msg = cmsg->msg;
        if (msg == CURLMSG_DONE) {
            CURLcode cc = cmsg->data.result;
            //printf("cc = %d\n", cc);
            if (cc != CURLE_OK) {
                log_error("errorbuffer = %s\n", cep->error_buffer);
            }
            log_debug("pull_data sets EOF (err msg)\n");
            *eof = 1;
            break;
        }
    }
    return rv;
}
static int read_file (endpoint_t * ep, int tfd, char * retbuf, int len, int * eof) static
Definition at line 366 of file curl_provider.c.
References File::bufdatalen, File::bufrp, ERROR_FAULT, find_file(), log_error(), pull_data(), File::read_converter, File::read_state, and reply_with_data().
{
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    File *fp = find_file(ep, tfd);
    if (fp != NULL) {
        if (fp->read_converter != NULL) {
            // mostly used for directory
            // I'll never understand where I need a "struct" ...
            return fp->read_converter((struct curl_endpoint_t*)cep, fp, retbuf, len, eof);
        }
        if (fp->bufdatalen > fp->bufrp) {
#ifdef DEBUG_CURL
            printf("Got some data already: datalen=%d\n", fp->bufdatalen);
#endif
            return reply_with_data(cep, fp, retbuf, len, eof);
        }
        // we don't have enough data to send something
        CURLMcode rv = pull_data(cep, fp, &(fp->read_state));
        if (fp->bufdatalen > fp->bufrp) {
            // we should now have some data to give back
#ifdef DEBUG_CURL
            printf("Pulled some data: datalen=%d, eof=%d\n", fp->bufdatalen, *eof);
#endif
            return reply_with_data(cep, fp, retbuf, len, eof);
        }
        if (rv == CURLM_OK) {
            return 0;
        }
    } else {
        log_error("fp is NULL on read attempt\n");
    }
    return -ERROR_FAULT;
}
static int reply_with_data (curl_endpoint_t * cep, File * fp, char * retbuf, int len, int * eof) static
Definition at line 335 of file curl_provider.c.
References File::bufdatalen, File::buffer, File::bufrp, log_debug(), pull_data(), and File::read_state.
Referenced by read_file().
{
    // we already have some data to give back
    int datalen = fp->bufdatalen - fp->bufrp;
    if (datalen > len) {
        // we have more data than requested
        datalen = len;
    }
    memcpy(retbuf, &(fp->buffer[fp->bufrp]), datalen);
    fp->bufrp += datalen;
    if (fp->bufdatalen <= fp->bufrp) {
        // reached the end of the buffer
        CURLMcode rv = CURLM_OK;
        if (!fp->read_state) {      // set from previous pull_data
            // try to pull in more, so we see if eof should be sent
            rv = pull_data(cep, fp, &(fp->read_state));
            if (rv != CURLM_OK) {
                log_debug("reply_with_data sets EOF rv=%d, datalen=%d\n", rv, fp->bufdatalen);
                *eof = 1;
            }
        }
        if (fp->read_state && fp->bufdatalen <= fp->bufrp) {
            log_debug("reply with data sets EOF (2)\n");
            *eof = 1;
        }
    }
    return datalen;
}
static File* reserve_file (endpoint_t * ep, int chan) static
Definition at line 208 of file curl_provider.c.
References File::chan, close_fd(), curl_endpoint_t::files, init_fp(), log_warn(), and MAX_SESSIONS.
Referenced by open_file().
{
    curl_endpoint_t *cep = (curl_endpoint_t*) ep;
    for (int i = 0; i < MAX_SESSIONS; i++) {
        if (cep->files[i].chan == chan) {
            log_warn("curl session still open for chan %d\n", chan);
            close_fd(&(cep->files[i]));
        }
        if (cep->files[i].chan < 0) {
            File *fp = &(cep->files[i]);
            init_fp(fp);
            fp->chan = chan;
            return &(cep->files[i]);
        }
    }
    log_warn("Did not find free curl session for channel=%d\n", chan);
    return NULL;
}
static size_t write_cb (char * ptr, size_t size, size_t nmemb, void * user) static
Definition at line 255 of file curl_provider.c.
References File::bufdatalen, File::buffer, File::buflen, and File::bufrp.
Referenced by open_dr(), and open_rd().
{
    File *fp = (File*) user;
    fp->bufdatalen = 0;
    long inlen = size * nmemb;
#ifdef DEBUG_CURL
printf("write_cb-> %ld (buffer is %d): ", inlen, fp->buflen);
if (fp->buflen > 0) {
    printf("%02x ", ptr[0]);
}
printf("\n");
#endif
    if (inlen > fp->buflen) {
        free(fp->buffer);   // fp->buffer NULL is ok, nothing is done
        int alloclen = inlen < 8192 ? 8192 : inlen;
        fp->buffer = malloc(alloclen);
        if (fp->buffer == NULL) {
            // malloc failed
            printf("malloc failed!\n");
            return 0;
        }
        fp->buflen = alloclen;
    }
    memcpy(fp->buffer, ptr, inlen);
    fp->bufdatalen = inlen;
    fp->bufrp = 0;
    return inlen;
}
Variable Documentation
provider_t ftp_provider
Initial value:
= {
    "ftp",
    curl_init,
    ftp_new,
    prov_free,
    close_fds,
    open_rd,
    NULL,
    NULL,
    NULL,
    open_dr,
    read_file,
    NULL,
    NULL,
    NULL,
    do_chdir,
    NULL,
    NULL
}
Definition at line 726 of file curl_provider.c.
Referenced by ftp_test().
provider_t http_provider
Initial value:
= {
    "http",
    curl_init,
    http_new,
    prov_free,
    close_fds,
    open_rd,
    NULL,
    NULL,
    NULL,
    NULL,
    read_file,
    NULL,
    NULL,
    NULL,
    do_chdir,
    NULL,
    NULL
}
Definition at line 747 of file curl_provider.c.
Referenced by http_test().