XD2031 pcserver: curl_test.c File Reference
curl_test.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include "provider.h"
#include "wireformat.h"
Functions
void ftp_test ()
void http_test ()
void get_test (provider_t *prov, const char *rootpath, const char *name)
void dir_test (provider_t *prov, const char *rootpath, const char *name)
int main (int argc, char *argv[])
Variables
provider_t ftp_provider
provider_t http_provider
Function Documentation
void dir_test (provider_t * prov, const char * rootpath, const char * name)
Definition at line 65 of file curl_test.c.
References provider_t::close, ep, FS_DIR_NAME, provider_t::init, provider_t::newep, provider_t::opendir, and provider_t::readfile.
{
    printf("dirprov=%p\n", prov);
    prov->init();
    printf("prov init done\n");
    // get endpoint for base URL
    endpoint_t *ep = prov->newep(rootpath);
    printf("ep=%p\n", ep);
    int rv = prov->opendir(ep, 1, name);
    printf("open -> %d\n", rv);
    char *buffer = malloc(8192 * sizeof(char));
    int eof = 0;
    do {
        rv = prov->readfile(ep, 1, buffer, 100, &eof);
        if (rv != 0) printf("readfile -> %d, eof=%d\n", rv, eof);
        if (rv > 0) {
            printf("---> %d: ", rv);
            for (int i = 0; i < FS_DIR_NAME; i++) {
                printf("%02x ", buffer[i]);
            }
            printf(": %s\n", buffer+FS_DIR_NAME);
        }
    }
    while (rv >= 0 && eof == 0);
    free(buffer);
    prov->close(ep, 1);
}
void ftp_test ()
Definition at line 47 of file curl_test.c.
References ftp_provider, and get_test().
Referenced by main().
                {
    provider_t *prov = &ftp_provider;
    //get_test(prov, "anonymous:fachat_at_web.de@ftp.zimmers.net/pub/cbm", "00INDEX");
    //get_test(prov, "ftp.zimmers.net/pub/cbm", "00INDEX");
    get_test(prov, "ftp.zimmers.net/pub/cbm", "index.html");
    //dir_test(prov, "ftp.zimmers.net/pub/cbm", "");
}
void get_test (provider_t * prov, const char * rootpath, const char * name)
Definition at line 105 of file curl_test.c.
References provider_t::close, ep, provider_t::init, provider_t::newep, provider_t::open_rd, and provider_t::readfile.
Referenced by ftp_test(), and http_test().
{
    printf("prov=%p\n", prov);
    prov->init();
    printf("prov init done\n");
    // get endpoint for base URL
    endpoint_t *ep = prov->newep(rootpath);
    printf("ep=%p\n", ep);
    int rv = prov->open_rd(ep, 1, name);
    printf("open -> %d\n", rv);
    char *buffer = malloc(8192 * sizeof(char));
    int eof = 0;
    do {
        rv = prov->readfile(ep, 1, buffer, 100, &eof);
        if (rv != 0) printf("readfile -> %d, eof=%d\n", rv, eof);
        if (rv > 0) {
            buffer[rv] = 0;
            printf("---> %s\n", buffer);
        }
    }
    while (rv >= 0 && eof == 0);
    free(buffer);
    prov->close(ep, 1);
}
void http_test ()
Definition at line 58 of file curl_test.c.
References get_test(), and http_provider.
Referenced by main().
                 {
    provider_t *prov = &http_provider;
    get_test(prov, "www.zimmers.net/anonftp/pub/cbm", "index.html");
}
int main (int argc, char * argv[])
Definition at line 38 of file curl_test.c.
References ftp_test(), and http_test().
{
    ftp_test();
    http_test();
}
Variable Documentation
provider_t ftp_provider
provider_t http_provider