XD2031 pcserver: dir.c File Reference
dir.c File Reference
#include <stdio.h>
#include <dirent.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include "dir.h"
#include "name.h"
#include "fscmd.h"
#include "wireformat.h"
#include "log.h"
Macros
#define min(a, b) (((a)<(b))?(a):(b))
Functions
FILE * open_first_match (const char *dir, const char *pattern, const char *options)
int dir_call_matches (const char *dir, const char *pattern, int(*callback)(const int num_of_match, const char *name))
int dir_fill_header (char *dest, int driveno, char *dirpattern)
struct dirent * dir_next (DIR *dp, char *dirpattern)
int dir_fill_entry (char *dest, char *curpath, struct dirent *de, int maxsize)
int dir_fill_disk (char *dest)
char * malloc_path (const char *base, const char *name)
Macro Definition Documentation
#define min (a, b) (((a)<(b))?(a):(b))
Definition at line 43 of file dir.c.
Referenced by dir_fill_entry().
Function Documentation
int dir_call_matches (const char * dir, const char * pattern, int(*)(const int num_of_match, const char *name) callback)
calls the callback on every matching file, returning the number of matches The callback gets the match count as first parameter (starting with one), and if it returns != 0 then the loop is exited.
Definition at line 103 of file dir.c.
References compare_pattern(), and malloc_path().
Referenced by fs_delete().
{
    int matches = 0;
    DIR *dp;
    int rv;
    struct dirent *de;
    int onlyone = 0;
    // shortcut - if we don't have wildcards, just open it
    if (index(pattern, '*') == NULL && index(pattern, '?') == NULL) {
        onlyone = 1;
    }
    dp = opendir(dir);
    if (dp) {
        de = readdir(dp);
        while (de != NULL) {
            if (compare_pattern(de->d_name, pattern)) {
                // match
                matches ++;
                // get full path
                char *namebuf = malloc_path(dir, de->d_name);
                rv = callback(matches, namebuf);
                // free memory
                free(namebuf);
                if (rv || onlyone) {
                    // either callback tells us to stop
                    // or there are no wildcards, so this has to be it
                    closedir(dp);
                    // if rv < 0 then some kind of error happened, return it
                    // instead of the number of matches
                    return (rv < 0) ? rv : matches;
                }
            }
            de = readdir(dp);
        }
    }
    closedir(dp);
    return matches;
}
int dir_fill_disk (char * dest)
fill in the buffer with the final disk info entry
Definition at line 245 of file dir.c.
References FS_DIR_LEN, FS_DIR_MOD_FRE, FS_DIR_MODE, and FS_DIR_NAME.
Referenced by read_dir().
{
        dest[FS_DIR_LEN] = 1;
        dest[FS_DIR_LEN+1] = 0;
        dest[FS_DIR_LEN+2] = 0;
        dest[FS_DIR_LEN+3] = 0;
        dest[FS_DIR_MODE]  = FS_DIR_MOD_FRE;
        dest[FS_DIR_NAME] = 0;
    return FS_DIR_NAME + 1;
}
int dir_fill_entry (char * dest, char * curpath, struct dirent * de, int maxsize)
fill in the buffer with a directory entry
Definition at line 203 of file dir.c.
References FS_DIR_DAY, FS_DIR_HOUR, FS_DIR_LEN, FS_DIR_MIN, FS_DIR_MOD_DIR, FS_DIR_MOD_FIL, FS_DIR_MODE, FS_DIR_MONTH, FS_DIR_NAME, FS_DIR_SEC, FS_DIR_YEAR, log_errno(), log_error(), malloc_path(), and min.
Referenced by read_dir().
{
    struct stat sbuf;
    struct tm *tp;
    char *realname = malloc_path(curpath, de->d_name);
        /* TODO: check return value */
    int rv = stat(realname, &sbuf);
    if (rv < 0) {
        log_error("Failed stat'ing entry %s\n", de->d_name);
        log_errno("Problem stat'ing dir entry");
    }
    free(realname);
        dest[FS_DIR_LEN] = sbuf.st_size & 255;
        dest[FS_DIR_LEN+1] = (sbuf.st_size >> 8) & 255;
        dest[FS_DIR_LEN+2] = (sbuf.st_size >> 16) & 255;
        dest[FS_DIR_LEN+3] = (sbuf.st_size >> 24) & 255;
        tp = localtime(&sbuf.st_mtime);
        dest[FS_DIR_YEAR]  = tp->tm_year;
        dest[FS_DIR_MONTH] = tp->tm_mon;
        dest[FS_DIR_DAY]   = tp->tm_mday;
        dest[FS_DIR_HOUR]  = tp->tm_hour;
        dest[FS_DIR_MIN]   = tp->tm_min;
        dest[FS_DIR_SEC]   = tp->tm_sec;
        dest[FS_DIR_MODE]  = S_ISDIR(sbuf.st_mode) ? FS_DIR_MOD_DIR : FS_DIR_MOD_FIL;
        // de->d_name is 0-terminated (see readdir man page)
        int l = strlen(de->d_name);
        strncpy(dest+FS_DIR_NAME, de->d_name,
                  min(l+1, maxsize-1-FS_DIR_NAME));
    // make sure we're still null-terminated
    dest[maxsize-1] = 0;
    return FS_DIR_NAME + strlen(dest+FS_DIR_NAME) + 1;
}
int dir_fill_header (char * dest, int driveno, char * dirpattern)
fill the buffer with a header entry, using the driveno as line number and dirpattern as file name
returns the length of the buffer
Definition at line 155 of file dir.c.
References FS_DIR_LEN, FS_DIR_MOD_NAM, FS_DIR_MODE, and FS_DIR_NAME.
Referenced by read_dir().
{
        dest[FS_DIR_LEN+0] = driveno & 255;
        dest[FS_DIR_LEN+1] = 0;
        dest[FS_DIR_LEN+2] = 0;
        dest[FS_DIR_LEN+3] = 0;
        // don't set date for now
        dest[FS_DIR_MODE]  = FS_DIR_MOD_NAM;
    if (*dirpattern == 0) {
        // no pattern given
            // simple default
            strncpy(dest+FS_DIR_NAME, ".               ", 16);
    } else {
        strncpy(dest+FS_DIR_NAME, dirpattern, 16);
        int l = strlen(dest+FS_DIR_NAME);
        // fill up with spaces
        while (l < 16) (dest+FS_DIR_NAME)[l++] = ' ';
    }
        dest[FS_DIR_NAME + 16] = 0;
    return FS_DIR_NAME + 17;
}
struct dirent* dir_next (DIR * dp, char * dirpattern) read
finds the next directory entry matching the given directory pattern
Definition at line 180 of file dir.c.
References compare_pattern().
Referenced by read_dir().
{
    struct dirent *de = NULL;
    de = readdir(dp);
    if (dirpattern != NULL && *dirpattern != 0) {
        while (de != NULL) {
            if (compare_pattern(de->d_name, dirpattern)) {
                // match
                return de;
            }
            de = readdir(dp);
        }
    }
    return de;
}
char* malloc_path (const char * base, const char * name)
malloc a new path and copy the given base path and name, concatenating them with the path separator
Definition at line 259 of file dir.c.
References log_info().
Referenced by dir_call_matches(), dir_fill_entry(), fs_cd(), fs_mkdir(), fs_rename(), fs_rmdir(), fsp_new(), and open_first_match().
{
        int l = (base == NULL) ? 0 : strlen(base);
        l += (name == NULL) ? 0 : strlen(name);
        l += 3; // dir separator, terminating zero, optional "."
        char *dirpath = malloc(l);
        dirpath[0] = 0;
        if (base != NULL) {
                strcat(dirpath, base);
                strcat(dirpath, "/");   // TODO dir separator char
        }
        if (name != NULL) {
                strcat(dirpath, name);
        }
        log_info("Calculate new dir path: %s\n", dirpath);
        return dirpath;
}
FILE* open_first_match (const char * dir, const char * pattern, const char * options)
fopen the first matching directory entry, using the given options string
Definition at line 49 of file dir.c.
References compare_pattern(), log_errno(), log_info(), and malloc_path().
Referenced by open_file().
{
    DIR *dp;
    FILE *fp;
    struct dirent *de;
    // shortcut - if we don't have wildcards, just open it
    if (index(pattern, '*') == NULL && index(pattern, '?') == NULL) {
        char *namebuf = malloc_path(dir, pattern);
        log_info("opening file with name %s\n",namebuf);
        fp = fopen(namebuf, options);
        if (fp == NULL) {
            log_errno("Error opening file with first match");
        }
        free(namebuf);
        return fp;
    }
    dp = opendir(dir);
    if (dp) {
        de = readdir(dp);
        while (de != NULL) {
            if (compare_pattern(de->d_name, pattern)) {
                // match
                char *namebuf = malloc_path(dir, de->d_name);
                log_info("opening file with name %s\n",namebuf);
                fp = fopen(namebuf, options);
                if (fp == NULL) {
                    log_errno("Error opening file with match");
                }
                free(namebuf);
                closedir(dp);
                return fp;
            }
            de = readdir(dp);
        }
    }
    return NULL;
}