XD2031 pcserver: fs_provider.c File Reference
fs_provider.c File Reference
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <dirent.h>
#include <string.h>
#include <strings.h>
#include <limits.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <stdlib.h>
#include "dir.h"
#include "fscmd.h"
#include "provider.h"
#include "errors.h"
#include "log.h"
Data Structures
struct File
struct fs_endpoint_t
Macros
#define __USE_XOPEN_EXTENDED
#define MAX_BUFFER_SIZE 64
Functions
void fsp_init ()
static void init_fp (File *fp)
static int close_fd (File *file)
static void fsp_free (endpoint_t *ep)
static endpoint_t * fsp_new (endpoint_t *parent, const char *path)
static int errno_to_error (int err)
static File * reserve_file (endpoint_t *ep, int chan)
static File * find_file (endpoint_t *ep, int chan)
static void close_fds (endpoint_t *ep, int tfd)
static int open_file (endpoint_t *ep, int tfd, const char *buf, const char *mode)
static int open_dr (endpoint_t *ep, int tfd, const char *buf)
static int read_dir (endpoint_t *ep, int tfd, char *retbuf, int len, int *eof)
static int read_file (endpoint_t *ep, int tfd, char *retbuf, int len, int *eof)
static int write_file (endpoint_t *ep, int tfd, char *buf, int len, int is_eof)
static int _delete_callback (const int num_of_match, const char *name)
static int fs_delete (endpoint_t *ep, char *buf, int *outdeleted)
static int fs_rename (endpoint_t *ep, char *buf)
static int fs_cd (endpoint_t *ep, char *buf)
static int fs_mkdir (endpoint_t *ep, char *buf)
static int fs_rmdir (endpoint_t *ep, char *buf)
static int open_file_rd (endpoint_t *ep, int tfd, const char *buf)
static int open_file_wr (endpoint_t *ep, int tfd, const char *buf)
static int open_file_ap (endpoint_t *ep, int tfd, const char *buf)
static int readfile (endpoint_t *ep, int chan, char *retbuf, int len, int *eof)
Variables
provider_t fs_provider
Macro Definition Documentation
#define __USE_XOPEN_EXTENDED
Definition at line 46 of file fs_provider.c.
#define MAX_BUFFER_SIZE 64
Definition at line 58 of file fs_provider.c.
Function Documentation
static int _delete_callback (const int num_of_match, const char * name) static
Definition at line 436 of file fs_provider.c.
References errno_to_error(), ERROR_OK, and log_errno().
Referenced by fs_delete().
{
    printf("%d: Calling DELETE on: %s\n", num_of_match, name);
    if (unlink(name) < 0) {
        // error handling
        log_errno("While trying to unlink");
        return -errno_to_error(errno);
    }
    return ERROR_OK;
}
static int close_fd (File * file) static
Definition at line 96 of file fs_provider.c.
References File::dp, File::fp, init_fp(), and log_errno().
Referenced by close_fds(), fsp_free(), open_dr(), open_file(), and reserve_file().
{
    int er = 0;
    if (file->fp != NULL) {
        er = fclose(file->fp);
        if (er < 0) {
            log_errno("Error closing fd");
        }
        file->fp = NULL;
    }
    if (file->dp != NULL) {
        er = closedir(file->dp);
        if (er < 0) {
            log_errno("Error closing dp");
        }
        file->dp = NULL;
    }
    init_fp(file);
    return er;
}
static void close_fds (endpoint_t * ep, int tfd) static
Definition at line 253 of file fs_provider.c.
References close_fd(), find_file(), and init_fp().
Referenced by read_dir(), read_file(), and write_file().
{
    File *file = find_file(ep, tfd); // ((fs_endpoint_t*)ep)->files;
    if (file != NULL) {
        close_fd(file);
        init_fp(file);
    }
}
static int errno_to_error (int err) static
Definition at line 183 of file fs_provider.c.
References ERROR_DIR_NOT_EMPTY, ERROR_DISK_FULL, ERROR_FAULT, ERROR_FILE_EXISTS, ERROR_FILE_NAME_TOO_LONG, ERROR_FILE_NOT_FOUND, ERROR_FILE_TYPE_MISMATCH, ERROR_NO_CHANNEL, ERROR_NO_PERMISSION, ERROR_SYNTAX_INVAL, and ERROR_WRITE_PROTECT.
Referenced by _delete_callback(), fs_mkdir(), fs_rename(), fs_rmdir(), and open_dr().
{
    switch(err) {
    case EEXIST:
        return ERROR_FILE_EXISTS;
    case EACCES:
        return ERROR_NO_PERMISSION;
    case ENAMETOOLONG:
        return ERROR_FILE_NAME_TOO_LONG;
    case ENOENT:
        return ERROR_FILE_NOT_FOUND;
    case ENOSPC:
        return ERROR_DISK_FULL;
    case EROFS:
        return ERROR_WRITE_PROTECT;
    case ENOTDIR:   // mkdir, rmdir
    case EISDIR:    // open, rename
        return ERROR_FILE_TYPE_MISMATCH;
    case ENOTEMPTY:
        return ERROR_DIR_NOT_EMPTY;
    case EMFILE:
        return ERROR_NO_CHANNEL;
    case EINVAL:
        return ERROR_SYNTAX_INVAL;
    default:
        return ERROR_FAULT;
    }
}
static File* find_file (endpoint_t * ep, int chan) static
Definition at line 237 of file fs_provider.c.
References File::chan, fs_endpoint_t::files, log_warn(), and MAXFILES.
Referenced by close_fds(), read_dir(), read_file(), readfile(), and write_file().
{
        fs_endpoint_t *cep = (fs_endpoint_t*) ep;
        for (int i = 0; i < MAXFILES; i++) {
                if (cep->files[i].chan == chan) {
                        return &(cep->files[i]);
                }
        }
        log_warn("Did not find curl session for channel=%d\n", chan);
        return NULL;
}
static int fs_cd (endpoint_t * ep, char * buf) static
Definition at line 540 of file fs_provider.c.
References fs_endpoint_t::basepath, fs_endpoint_t::curpath, ERROR_FILE_NOT_FOUND, ERROR_NO_PERMISSION, ERROR_OK, log_debug(), log_error(), and malloc_path().
{
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    log_debug("Change dir to: %s\n", buf);
    //  concat new path to current path
    char *newpath = malloc_path(fsep->curpath, buf);
    // canonicalize it
    char *newreal = realpath(newpath, NULL);
    // free buffer so we don't forget it
    free(newpath);
    log_debug("Checking that new path '%s' is under base '%s'\n",
        newreal, fsep->basepath);
    if (newreal == NULL) {
        // target does not exist
        return ERROR_FILE_NOT_FOUND;
    }
    // check if the new path is still under the base path
    if (strstr(newreal, fsep->basepath) == newreal) {
        // the needle base path is found at the start of the new real path -> ok
        free(fsep->curpath);
        fsep->curpath = newreal;
    } else {
        // needle (base path) is not in haystack (new path)
        // -> security error
        log_error("Tried to chdir outside base dir %s, to %s\n", fsep->basepath, newreal);
        free(newreal);
        return ERROR_NO_PERMISSION;
    }
    return ERROR_OK;
}
static int fs_delete (endpoint_t * ep, char * buf, int * outdeleted) static
Definition at line 449 of file fs_provider.c.
References _delete_callback(), fs_endpoint_t::curpath, dir_call_matches(), and ERROR_SCRATCHED.
{
    int matches = 0;
    char *p = buf;
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    do {
        // comma is file pattern separator
        char *pnext = index(p, ',');
        if (pnext != NULL) {
            *pnext = 0; // write file name terminator (replacing the ',')
        }
        int rv = dir_call_matches(fsep->curpath, p, _delete_callback);
        if (rv < 0) {
            // error happened
            return -rv;
        }
        matches += rv;
        p = (pnext == NULL) ? NULL : pnext+1;
    }
    while (p != NULL);
    *outdeleted = matches;
    return ERROR_SCRATCHED; // FILES SCRATCHED message
}
static int fs_mkdir (endpoint_t * ep, char * buf) static
Definition at line 576 of file fs_provider.c.
References fs_endpoint_t::curpath, errno_to_error(), ERROR_DIR_ERROR, ERROR_FILE_EXISTS, ERROR_OK, log_errno(), malloc_path(), and provider_t::mkdir.
{
    int er = ERROR_DIR_ERROR;
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    char *newpath = malloc_path(fsep->curpath, buf);
    char *newreal = realpath(newpath, NULL);
    if (newreal != NULL) {
        // file or directory exists
        er = ERROR_FILE_EXISTS;
    } else {
        int rv = mkdir(newpath, 0557);
        if (rv < 0) {
            log_errno("Error trying to make a directory");
            er = errno_to_error(errno);
        } else {
            // ok
            er = ERROR_OK;
        }
    }
    free(newpath);
    free(newreal);
    return er;
}
static int fs_rename (endpoint_t * ep, char * buf) static
Definition at line 479 of file fs_provider.c.
References fs_endpoint_t::basepath, fs_endpoint_t::curpath, errno_to_error(), ERROR_FAULT, ERROR_FILE_EXISTS, ERROR_OK, ERROR_SYNTAX_DIR_SEPARATOR, ERROR_SYNTAX_NONAME, log_errno(), log_error(), malloc_path(), and provider_t::rename.
{
    int er = ERROR_FAULT;
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    // first find the two names separated by "="
    int p = 0;
    while (buf[p] != 0 && buf[p] != '=') {
        p++;
    }
    if (buf[p] == 0) {
        // not found
        log_error("Did not find '=' in rename command %s\n", buf);
        return ERROR_SYNTAX_NONAME;
    }
    buf[p] = 0;
    char *from = buf+p+1;
    char *to = buf;
    if (index(to, '/') != NULL) {
        // no separator char
        log_error("target file name contained dir separator\n");
        return ERROR_SYNTAX_DIR_SEPARATOR;
    }
    char *frompath = malloc_path(fsep->curpath, from);
    char *topath = malloc_path(fsep->curpath, to);
    char *fromreal = realpath(frompath, NULL);
    free(frompath);
    char *toreal = realpath(topath, NULL);
    if (toreal != NULL) {
        // target already exists
        er = ERROR_FILE_EXISTS;
    } else {
        // check both paths against container boundaries
        if ((strstr(fromreal, fsep->basepath) == fromreal)
            && (strstr(topath, fsep->basepath) == topath)) {
            // ok
            int rv = rename(fromreal, topath);
            if (rv < 0) {
                er = errno_to_error(errno);
                log_errno("Error renaming a file\n");
            } else {
                er = ERROR_OK;
            }
        }
    }
    free(topath);
    free(toreal);
    free(fromreal);
    return er;
}
static int fs_rmdir (endpoint_t * ep, char * buf) static
Definition at line 606 of file fs_provider.c.
References fs_endpoint_t::basepath, fs_endpoint_t::curpath, errno_to_error(), ERROR_FAULT, ERROR_FILE_NOT_FOUND, ERROR_OK, log_errno(), malloc_path(), and provider_t::rmdir.
{
    int er = ERROR_FAULT;
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    char *newpath = malloc_path(fsep->curpath, buf);
    char *newreal = realpath(newpath, NULL);
    free(newpath);
    if (newreal == NULL) {
        // directory does not exist
        er = ERROR_FILE_NOT_FOUND;
    } else
    if (strstr(newreal, fsep->basepath) == newreal) {
        // current path is still at the start of new path
        // so it is not broken out of the container
        int rv = rmdir(newreal);
        if (rv < 0) {
            er = errno_to_error(errno);
            log_errno("Error trying to remove a directory");
        } else {
            // ok
            er = ERROR_OK;
        }
    }
    free(newreal);
    return er;
}
static void fsp_free (endpoint_t * ep) static
Definition at line 117 of file fs_provider.c.
References fs_endpoint_t::basepath, close_fd(), fs_endpoint_t::curpath, fs_endpoint_t::files, and MAXFILES.
Referenced by fsp_new().
{
        fs_endpoint_t *cep = (fs_endpoint_t*) ep;
        int i;
        for(i=0;i<MAXFILES;i++) {
                close_fd(&(cep->files[i]));
        }
    free(cep->basepath);
    free(cep->curpath);
        free(ep);
}
void fsp_init ()
Definition at line 80 of file fs_provider.c.
                {
}
static endpoint_t* fsp_new (endpoint_t * parent, const char * path) static
Definition at line 128 of file fs_provider.c.
References fs_endpoint_t::basepath, fs_endpoint_t::curpath, fs_endpoint_t::files, fsp_free(), init_fp(), log_errno(), log_error(), log_info(), malloc_path(), MAXFILES, and fs_endpoint_t::ptype.
{
    fs_endpoint_t *parentep = (fs_endpoint_t*) parent;
    // alloc and init a new endpoint struct
    fs_endpoint_t *fsep = malloc(sizeof(fs_endpoint_t));
    fsep->basepath = NULL;
    fsep->curpath = NULL;
        for(int i=0;i<MAXFILES;i++) {
        init_fp(&(fsep->files[i]));
        }
    fsep->ptype = (struct provider_t *) &fs_provider;
    char *dirpath = malloc_path((parentep == NULL) ? NULL : parentep->curpath,
                path);
    // malloc's a buffer and stores the canonical real path in it
    fsep->basepath = realpath(dirpath, NULL);
    free(dirpath);
    if (fsep->basepath == NULL) {
        // some problem with dirpath - maybe does not exist...
        log_errno("Could not resolve path for assign");
        fsp_free((endpoint_t*)fsep);
        return NULL;
    }
    if (parentep != NULL) {
        // if we have a parent, make sure we do not
        // escape the parent container, i.e. basepath
        if (strstr(fsep->basepath, parentep->basepath) != fsep->basepath) {
            // the parent base path is not at the start of the new base path
            // so we throw an error
            log_error("ASSIGN broke out of container (%s), was trying %s\n",
                parentep->basepath, fsep->basepath);
            fsp_free((endpoint_t*)fsep);
            return NULL;
        }
    }
    // copy into current path
    fsep->curpath = malloc(strlen(fsep->basepath) + 1);
    strcpy(fsep->curpath, fsep->basepath);
    log_info("FS provider set to real path '%s'\n", fsep->basepath);
    return (endpoint_t*) fsep;
}
static void init_fp (File * fp) static
Definition at line 85 of file fs_provider.c.
References File::chan, File::dp, and File::fp.
Referenced by close_fd(), close_fds(), fsp_new(), and reserve_file().
{
    //log_debug("initializing fp=%p (used to be chan %d)\n", fp, fp == NULL ? -1 : fp->chan);
        fp->chan = -1;
    fp->fp = NULL;
    fp->dp = NULL;
}
static int open_dr (endpoint_t * ep, int tfd, const char * buf) static
Definition at line 296 of file fs_provider.c.
References close_fd(), fs_endpoint_t::curpath, File::dirpattern, File::dp, errno_to_error(), ERROR_FAULT, ERROR_OK, File::fp, File::is_first, log_errno(), log_info(), provider_t::opendir, and reserve_file().
{
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
        File *file = reserve_file(ep, tfd);
    if (file != NULL) {
        // save pattern for later comparisons
        strcpy(file->dirpattern, buf);
        DIR *dp = opendir(fsep->curpath /*buf+FSP_DATA*/);
        log_info("OPEN_DR(%s)=%p, (chan=%d, file=%p, dp=%p)\n",buf,(void*)dp,
                            tfd, (void*)file, (void*)dp);
        if(dp) {
          file->fp = NULL;
          file->dp = dp;
          file->is_first = 1;
          return ERROR_OK;
        } else {
          log_errno("Error opening directory");
          int er = errno_to_error(errno);
          close_fd(file);
          return er;
        }
    }
    return ERROR_FAULT;
}
static int open_file (endpoint_t * ep, int tfd, const char * buf, const char * mode) static
Definition at line 262 of file fs_provider.c.
References close_fd(), fs_endpoint_t::curpath, File::dp, ERROR_FAULT, ERROR_OK, ERROR_SYNTAX_DIR_SEPARATOR, File::fp, log_info(), open_first_match(), and reserve_file().
Referenced by open_file_ap(), open_file_rd(), and open_file_wr().
{
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    log_info("open file in dir %s with name %s\n", fsep->curpath, buf);
        File *file = reserve_file(ep, tfd);
    if (file != NULL) {
        /* no directory separators - security rules! */
        char *nm = (char*)buf;
        if(*nm=='/') nm++;
        if(strchr(nm, '/')) {
            // should give a security error
            // TODO: replace with correct error number
            return ERROR_SYNTAX_DIR_SEPARATOR;
        }
        FILE *fp = open_first_match(fsep->curpath, nm, mode);
        log_info("OPEN_RD/AP/WR(%s: %s (@ %p))=%p (fp=%p)\n",mode, buf, buf, (void*)file, (void*)fp);
        if(fp) {
          file->fp = fp;
          file->dp = NULL;
          return ERROR_OK;
        }
        // TODO: open error (maybe depending on errno?)
        close_fd(file);
    }
    return ERROR_FAULT;
}
static int open_file_ap (endpoint_t * ep, int tfd, const char * buf) static
Definition at line 651 of file fs_provider.c.
References open_file().
{
       return open_file(ep, tfd, buf, "ab");
}
static int open_file_rd (endpoint_t * ep, int tfd, const char * buf) static
Definition at line 643 of file fs_provider.c.
References open_file().
{
       return open_file(ep, tfd, buf, "rb");
}
static int open_file_wr (endpoint_t * ep, int tfd, const char * buf) static
Definition at line 647 of file fs_provider.c.
References open_file().
{
       return open_file(ep, tfd, buf, "wb");
}
static int read_dir (endpoint_t * ep, int tfd, char * retbuf, int len, int * eof) static
Definition at line 334 of file fs_provider.c.
References close_fds(), fs_endpoint_t::curpath, File::de, dir_fill_disk(), dir_fill_entry(), dir_fill_header(), dir_next(), File::dirpattern, File::dp, ERROR_FAULT, find_file(), and File::is_first.
Referenced by readfile().
{
    fs_endpoint_t *fsep = (fs_endpoint_t*) ep;
    File *file = find_file(ep, tfd);
    //log_debug("read_dir: file=%p, is_first=%d\n", file, (file == NULL) ? -1 : file->is_first);
    if (file != NULL) {
        int rv = 0;
          if (file->is_first) {
            file->is_first = 0;
            int l = dir_fill_header(retbuf, 0, file->dirpattern);
            rv = l;
            file->de = dir_next(file->dp, file->dirpattern);
            return rv;
          }
          if(!file->de) {
            close_fds(ep, tfd);
            *eof = 1;
            int l = dir_fill_disk(retbuf);
            rv = l;
            return rv;
          }
          int l = dir_fill_entry(retbuf, fsep->curpath, file->de, len);
          rv = l;
          // prepare for next read (so we know if we're done)
          file->de = dir_next(file->dp, file->dirpattern);
          return rv;
    }
    return -ERROR_FAULT;
}
static int read_file (endpoint_t * ep, int tfd, char * retbuf, int len, int * eof) static
Definition at line 371 of file fs_provider.c.
References close_fds(), ERROR_FAULT, find_file(), and File::fp.
Referenced by readfile().
{
    File *file = find_file(ep, tfd);
    if (file != NULL) {
        int rv = 0;
          FILE *fp = file->fp;
          int n = fread(retbuf, 1, len, fp);
          rv = n;
          if(n<len) {
            // short read, so either error or eof
            *eof = 1;
            close_fds(ep, tfd);
          } else {
            // as feof() does not let us know if the file is EOF without
            // having attempted to read it first, we need this kludge
            int eofc = fgetc(fp);
            if (eofc < 0) {
              // EOF
              *eof = 1;
              //printf("Setting EOF!\n");
              close_fds(ep, tfd);
            } else {
              // restore fp, so we can read it properly on the next request
              ungetc(eofc, fp);
              // do not send EOF
            }
          }
        return rv;
    }
    return -ERROR_FAULT;
}
static int readfile (endpoint_t * ep, int chan, char * retbuf, int len, int * eof) static
Definition at line 656 of file fs_provider.c.
References File::dp, find_file(), File::fp, log_debug(), read_dir(), and read_file().
{
    File *f = find_file(ep, chan); // ((fs_endpoint_t*)ep)->files;
#ifdef DEBUG_READ
    log_debug("readfile chan %d: file=%p (fp=%p, dp=%p, eof=%d)\n",
        chan, f, f==NULL ? NULL : f->fp, f == NULL ? NULL : f->dp, *eof);
#endif
    int rv = 0;
    if (f->dp) {
        rv = read_dir(ep, chan, retbuf, len, eof);
    } else
    if (f->fp) {
        // read a file
        rv = read_file(ep, chan, retbuf, len, eof);
    }
    return rv;
}
static File* reserve_file (endpoint_t * ep, int chan) static
Definition at line 216 of file fs_provider.c.
References File::chan, close_fd(), fs_endpoint_t::files, init_fp(), log_warn(), and MAXFILES.
Referenced by open_dr(), and open_file().
{
        fs_endpoint_t *cep = (fs_endpoint_t*) ep;
        for (int i = 0; i < MAXFILES; i++) {
                if (cep->files[i].chan == chan) {
                        close_fd(&(cep->files[i]));
                }
                if (cep->files[i].chan < 0) {
                        File *fp = &(cep->files[i]);
                        init_fp(fp);
                        fp->chan = chan;
            //log_debug("reserving file %p for chan %d\n", fp, chan);
                        return &(cep->files[i]);
                }
        }
        log_warn("Did not find free curl session for channel=%d\n", chan);
        return NULL;
}
static int write_file (endpoint_t * ep, int tfd, char * buf, int len, int is_eof) static
Definition at line 406 of file fs_provider.c.
References close_fds(), ERROR_FAULT, ERROR_OK, ERROR_WRITE_ERROR, find_file(), File::fp, and log_debug().
{
    File *file = find_file(ep, tfd);
    //log_debug("write_file: file=%p\n", file);
    if (file != NULL) {
        FILE *fp = file->fp;
        if(fp) {
          // TODO: evaluate return value
          int n = fwrite(buf, 1, len, fp);
          if (n < len) {
            // short write indicates an error
            log_debug("Short write on file!\n");
            close_fds(ep, tfd);
            return -ERROR_WRITE_ERROR;
          }
          if(is_eof) {
            log_debug("Write file received an EOF\n");
            close_fds(ep, tfd);
          }
          return ERROR_OK;
        }
    }
    return -ERROR_FAULT;
}
Variable Documentation
provider_t fs_provider
Initial value:
= {
    "fs",
    fsp_init,
    fsp_new,
    fsp_free,
    close_fds,
    open_file_rd,
    open_file_wr,
    open_file_ap,
    NULL,
    open_dr,
    readfile,
    write_file,
    fs_delete,
    fs_rename,
    fs_cd,
    fs_mkdir,
    fs_rmdir
}
Definition at line 676 of file fs_provider.c.