XD2031 pcserver: fscmd.c File Reference
fscmd.c File Reference
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <dirent.h>
#include <string.h>
#include <strings.h>
#include <ctype.h>
#include "wireformat.h"
#include "fscmd.h"
#include "dir.h"
#include "provider.h"
#include "log.h"
Data Structures
struct chan_t
Macros
#define MAX_BUFFER_SIZE 64
Functions
static void do_cmd (char *buf, int fs)
void chan_init ()
endpoint_t * chan_to_endpoint (int chan)
void free_chan (int channo)
void set_chan (int channo, endpoint_t *ep)
void cmd_init ()
void cmd_assign_from_cmdline (int argc, char *argv[])
static void cmd_sync (int readfd, int writefd)
void cmd_loop (int readfd, int writefd)
Variables
chan_t chantable [MAX_NUMBER_OF_ENDPOINTS]
Macro Definition Documentation
#define MAX_BUFFER_SIZE 64
Definition at line 53 of file fscmd.c.
Referenced by do_cmd().
Function Documentation
void chan_init ()
Definition at line 69 of file fscmd.c.
References chan_t::channo, and MAX_NUMBER_OF_ENDPOINTS.
Referenced by cmd_init().
                 {
       int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
          chantable[i].channo = -1;
        }
}
endpoint_t* chan_to_endpoint (int chan)
Definition at line 76 of file fscmd.c.
References chan_t::ep, log_info(), and MAX_NUMBER_OF_ENDPOINTS.
Referenced by do_cmd().
{
       int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
               if (chantable[i].channo == chan) {
                       return chantable[i].ep;
               }
        }
       log_info("Did not find ep for channel %d\n", chan);
       return NULL;
}
void cmd_assign_from_cmdline (int argc, char * argv[])
take the command line, search for "-A<driv>=<name>" parameters and assign the value
Definition at line 125 of file fscmd.c.
References log_error(), and provider_assign().
Referenced by main().
{
    for (int i = 0; i < argc; i++) {
        if ((strlen(argv[i]) >4)
            && argv[i][0] == '-'
            && argv[i][1] == 'A') {
            if (!isdigit(argv[i][2])) {
                log_error("Could not identify %c as drive number!\n", argv[i][2]);
                continue;
            }
            if (argv[i][3] != '=') {
                log_error("Could not identify %s as ASSIGN parameter\n", argv[i]);
                continue;
            }
            int rv = provider_assign(argv[i][2] & 0x0f, &(argv[i][4]));
            if (rv < 0) {
                log_error("Could not assign, error number is %d\n", rv);
            }
        }
    }
}
void cmd_init ()
Definition at line 116 of file fscmd.c.
References chan_init(), and provider_init().
Referenced by main().
                {
    provider_init();
    chan_init();
}
void cmd_loop (int readfd, int writefd)
this is the main loop of the program
Here the data is read from the given readfd, put into a packet buffer, then given to do_cmd() for the actual execution, and the reply is again packeted and written to the writefd
Definition at line 191 of file fscmd.c.
References cmd_sync(), do_cmd(), FS_SYNC, FSP_CMD, FSP_DATA, and FSP_LEN.
Referenced by main().
{
        char buf[8192];
        int wrp,rdp,plen, cmd;
        int n;
    // sync device and server
    cmd_sync(readfd, writefd);
        /* write and read pointers in the input buffer "buf" */
        wrp = rdp = 0;
        while((n=read(readfd, buf+wrp, 8192-wrp))!=0) {
#ifdef DEBUG_READ
          printf("read %d bytes: ",n);
          for(int i=0;i<n;i++) printf("%02x ",255&buf[wrp+i]); printf("\n");
#endif
              if(n<0) {
                fprintf(stderr,"fstcp: read error %d (%s)\n",errno,strerror(errno));
                break;
              }
              wrp+=n;
              if(rdp && (wrp==8192 || rdp==wrp)) {
                if(rdp!=wrp) {
                  memmove(buf, buf+rdp, wrp-rdp);
                }
                wrp -= rdp;
                rdp = 0;
              }
//printf("wrp=%d, rdp=%d, FSP_LEN=%d\n",wrp,rdp,FSP_LEN);
              // as long as we have more than FSP_LEN bytes in the buffer
              // i.e. 2 or more, we loop and process packets
              // FSP_LEN is the position of the packet length
              while(wrp-rdp > FSP_LEN) {
                // first byte in packet is command, second is length of packet
                plen = 255 & buf[rdp+FSP_LEN];  //  AND with 255 to fix sign
                cmd = 255 & buf[rdp+FSP_CMD];   //  AND with 255 to fix sign
//printf("wrp-rdp=%d, plen=%d\n",wrp-rdp,plen);
                // full packet received already?
                if (cmd == FS_SYNC || plen < FSP_DATA) {
          // a packet is at least 3 bytes (when with zero data length)
          // or the byte is the FS_SYNC command
          // so ignore byte and shift one in buffer position
          rdp++;
        } else
                if(wrp-rdp >= plen) {
                  // yes, then execute
                  do_cmd(buf+rdp, writefd);
                  rdp +=plen;
                } else {
                  break;
                }
              }
            }
}
static void cmd_sync (int readfd, int writefd) static
Definition at line 151 of file fscmd.c.
References FS_SYNC, and log_errno().
Referenced by cmd_loop().
{
    char syncbuf[1];
    // first sync the device and the server.
    // I.e. we send an FS_SYNC byte, and wait for the sync byte return,
    // ignoreing all other bytes
    //
    // write the sync byte
    syncbuf[0] = FS_SYNC;
    int e = 0;
    do {
#if defined DEBUG_WRITE || defined DEBUG_CMD
        printf("sync write %02x\n", syncbuf[0]);
#endif
        e = write(writefd, syncbuf, 1);
    } while (e == 0 || (e < 0 &&  errno == EAGAIN));
    if (e < 0) {
        log_errno("Error on sync write", errno);
    }
    // wait for a sync byte
    int n = 0;
    do {
        n = read(readfd, syncbuf, 1);
#ifdef DEBUG_READ
            printf("sync read %d bytes: ",n);
            for(int i=0;i<n;i++) printf("%02x ",255&syncbuf[i]); printf("\n");
#endif
        if (n < 0) {
            log_errno("Error on sync read", errno);
        }
    } while (n != 1 || (0xff & syncbuf[0]) != FS_SYNC);
}
static void do_cmd (char * buf, int fd) static
This function executes a packet from the device. The return data is written into the file descriptor fd
Definition at line 256 of file fscmd.c.
References provider_t::cd, chan_to_endpoint(), provider_t::close, ep, ERROR_FAULT, ERROR_OK, ERROR_SCRATCHED, free_chan(), FS_ASSIGN, FS_CHDIR, FS_CLOSE, FS_DELETE, FS_EOF, FS_MKDIR, FS_OPEN_AP, FS_OPEN_DR, FS_OPEN_RD, FS_OPEN_WR, FS_READ, FS_RENAME, FS_REPLY, FS_RMDIR, FS_TERM, FS_WRITE, FSP_CMD, FSP_DATA, FSP_FD, FSP_LEN, log_debug(), log_error(), log_rv, log_term(), MAX_BUFFER_SIZE, provider_t::mkdir, provider_t::open_ap, provider_t::open_rd, provider_t::open_wr, provider_t::opendir, provider_assign(), provider_lookup(), _endpoint::ptype, provider_t::readfile, provider_t::rename, provider_t::rmdir, provider_t::scratch, set_chan(), and provider_t::writefile.
Referenced by cmd_loop().
{
    int tfd, cmd;
    unsigned int len;
    char retbuf[200];
    int rv;
    cmd = buf[FSP_CMD];     // 0
    len = 255 & buf[FSP_LEN];   // 1
    if (cmd == FS_TERM) {
#ifdef DEBUG_CMD_TERM
        {
            int n = buf[FSP_LEN];
            log_debug("term: %d bytes @%p: ",n, buf);
            for(int i=0;i<n;i++) printf("%02x ",255&buf[i]); printf("\n");
        }
#endif
        if (len > 200) {
            log_error("TERM length exceeds 200! Is %d\n", len);
            len = 200;
        }
        memcpy(retbuf, buf+3, len-3);
        retbuf[len-3] = 0;
        log_term(retbuf);
        return;
    }
#ifdef DEBUG_CMD
    {
        int n = buf[FSP_LEN];
        log_debug("cmd: %d bytes @%p: ",n, buf);
        for(int i=0;i<n;i++) printf("%02x ",255&buf[i]); printf("\n");
    }
#endif
    // not on FS_TERM
    tfd = buf[FSP_FD];
    if (tfd < 0) {
        printf("Illegal file descriptor: %d\n", tfd);
        return;
    }
    buf[(unsigned int)buf[FSP_LEN]] = 0;    // 0-terminator
    provider_t *prov = NULL; //&fs_provider;
    endpoint_t *ep = NULL;
#if 0
    printf("got cmd=%d, fd=%d, name=%s",cmd,tfd,
            (cmd<FS_ASSIGN)?((char*)buf+FSP_DATA):"null");
    for (int i = 3; i < buf[FSP_LEN]; i++) printf(" %02x", (unsigned int)buf[i]);
    printf("\n");
#endif
    retbuf[FSP_CMD] = FS_REPLY;
    retbuf[FSP_LEN] = 4;
    retbuf[FSP_FD] = tfd;
    retbuf[FSP_DATA] = ERROR_FAULT;
    int eof = 0;
    int outdeleted = 0;
    switch(cmd) {
        // file-oriented commands
    case FS_OPEN_WR:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            rv = prov->open_wr(ep, tfd, buf + FSP_DATA + 1);
            retbuf[FSP_DATA] = rv;
            if (rv == 0) {
                set_chan(tfd, ep);
            } else {
                log_rv(rv);
            }
        }
        break;
    case FS_OPEN_DR:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            // not all providers support directory operation
            if (prov->opendir != NULL) {
                rv = prov->opendir(ep, tfd, buf + FSP_DATA + 1);
                retbuf[FSP_DATA] = rv;
                if (rv == 0) {
                    set_chan(tfd, ep);
                } else {
                    log_rv(rv);
                }
            }
        }
        break;
    case FS_OPEN_RD:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            rv = prov->open_rd(ep, tfd, buf + FSP_DATA + 1);
            retbuf[FSP_DATA] = rv;
            if (rv == 0) {
                set_chan(tfd, ep);
            } else {
                log_rv(rv);
            }
        }
        break;
    case FS_OPEN_AP:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            rv = prov->open_ap(ep, tfd, buf + FSP_DATA + 1);
            retbuf[FSP_DATA] = rv;
            if (rv == 0) {
                set_chan(tfd, ep);
            } else {
                log_rv(rv);
            }
        }
        break;
    case FS_READ:
        ep = chan_to_endpoint(tfd);
        if (ep != NULL) {
            eof = 0;    // default just in case
            prov = (provider_t*) ep->ptype;
            rv = prov->readfile(ep, tfd, retbuf + FSP_DATA, MAX_BUFFER_SIZE-FSP_DATA, &eof);
            // TODO: handle error (rv<0)
            if (rv < 0) {
                log_rv(-rv);
            }
            retbuf[FSP_LEN] = FSP_DATA + rv;
            if (eof) {
                retbuf[FSP_CMD] = FS_EOF;
            }
        }
        break;
    case FS_WRITE:
    case FS_EOF:
        ep = chan_to_endpoint(tfd);
        //printf("WRITE: chan=%d, ep=%p\n", tfd, ep);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            rv = prov->writefile(ep, tfd, buf+FSP_DATA, len-FSP_DATA, cmd == FS_EOF);
            if (rv != 0) {
                log_rv(rv);
            }
            retbuf[FSP_DATA] = rv;
        }
        break;
    case FS_CLOSE:
        ep = chan_to_endpoint(tfd);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            prov->close(ep, tfd);
            free_chan(tfd);
            retbuf[FSP_DATA] = ERROR_OK;
        }
        break;
        // command operations
    case FS_DELETE:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            if (prov->scratch != NULL) {
                rv = prov->scratch(ep, buf+FSP_DATA+1, &outdeleted);
                if (rv == ERROR_SCRATCHED) {
                    retbuf[FSP_DATA + 1] = outdeleted > 99 ? 99 :outdeleted;
                    retbuf[FSP_LEN] = FSP_DATA + 2;
                } else
                if (rv != 0) {
                    log_rv(rv);
                }
                retbuf[FSP_DATA] = rv;
            }
        }
        break;
    case FS_RENAME:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            if (prov->rename != NULL) {
                rv = prov->rename(ep, buf+FSP_DATA+1);
                if (rv != 0) {
                    log_rv(rv);
                }
                retbuf[FSP_DATA] = rv;
            }
        }
        break;
    case FS_CHDIR:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            if (prov->cd != NULL) {
                rv = prov->cd(ep, buf+FSP_DATA+1);
                if (rv != 0) {
                    log_rv(rv);
                }
                retbuf[FSP_DATA] = rv;
            }
        }
        break;
    case FS_MKDIR:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            if (prov->mkdir != NULL) {
                rv = prov->mkdir(ep, buf+FSP_DATA+1);
                if (rv != 0) {
                    log_rv(rv);
                }
                retbuf[FSP_DATA] = rv;
            }
        }
        break;
    case FS_RMDIR:
        ep = provider_lookup(buf[FSP_DATA]);
        if (ep != NULL) {
            prov = (provider_t*) ep->ptype;
            if (prov->rmdir != NULL) {
                rv = prov->rmdir(ep, buf+FSP_DATA+1);
                if (rv != 0) {
                    log_rv(rv);
                }
                retbuf[FSP_DATA] = rv;
            }
        }
        break;
    case FS_ASSIGN:
        // assign an endpoint number (i.e. a drive number for the PET)
        // to a filesystem provider and path
        // The drive number in buf[FSP_DATA] is the one to assign,
        // while the rest of the name determines which provider to use
        //
        // A provider can be determines relative to an existing one. In
        // this case the provider name is the endpoint (drive) number,
        // and the path is interpreted as relative to an existing endpoint.
        // If the provider name is a real name, the path is absolute.
        //
        rv = provider_assign(buf[FSP_DATA], buf+FSP_DATA+1);
        if (rv != 0) {
            log_rv(rv);
        }
        retbuf[FSP_DATA] = rv;
        break;
    }
    int e = write(fd, retbuf, 0xff & retbuf[FSP_LEN]);
    if (e < 0) {
        printf("Error on write: %d\n", errno);
    }
#if defined DEBUG_WRITE || defined DEBUG_CMD
    printf("write %02x %02x %02x:", 255&retbuf[0], 255&retbuf[1],
            255&retbuf[2] );
    for (int i = 3; i<retbuf[FSP_LEN];i++) printf(" %02x", 255&retbuf[i]);
    printf("\n");
#endif
}
void free_chan (int channo)
Definition at line 88 of file fscmd.c.
References chan_t::channo, chan_t::ep, and MAX_NUMBER_OF_ENDPOINTS.
Referenced by do_cmd().
{
       int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
               if (chantable[i].channo == channo) {
                       chantable[i].channo = -1;
                       chantable[i].ep = NULL;
               }
        }
}
void set_chan (int channo, endpoint_t * ep)
Definition at line 98 of file fscmd.c.
References chan_t::channo, ep, chan_t::ep, log_error(), and MAX_NUMBER_OF_ENDPOINTS.
Referenced by do_cmd().
{
       int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
               // we overwrite existing entries, to "heal" leftover cruft
               // just in case...
               if ((chantable[i].channo == -1) || (chantable[i].channo == channo)) {
                       chantable[i].channo = channo;
                       chantable[i].ep = ep;
                       return;
               }
        }
       log_error("Did not find free ep slot for channel %d\n", channo);
}
Variable Documentation
chan_t chantable[MAX_NUMBER_OF_ENDPOINTS]
Definition at line 66 of file fscmd.c.