XD2031 pcserver: fscmd.h File Reference
fscmd.h File Reference
Macros
#define F_FREE 0 /* must be 0 */
#define MAXFILES 16
Functions
void cmd_init ()
void cmd_assign_from_cmdline (int argc, char *argv[])
void cmd_loop (int readfs, int writefd)
Macro Definition Documentation
#define F_FREE 0 /* must be 0 */
Definition at line 33 of file fscmd.h.
#define MAXFILES 16
Definition at line 35 of file fscmd.h.
Referenced by find_file(), fsp_free(), fsp_new(), and reserve_file().
Function Documentation
void cmd_assign_from_cmdline (int argc, char * argv[])
take the command line, search for "-A<driv>=<name>" parameters and assign the value
Definition at line 125 of file fscmd.c.
References log_error(), and provider_assign().
Referenced by main().
{
    for (int i = 0; i < argc; i++) {
        if ((strlen(argv[i]) >4)
            && argv[i][0] == '-'
            && argv[i][1] == 'A') {
            if (!isdigit(argv[i][2])) {
                log_error("Could not identify %c as drive number!\n", argv[i][2]);
                continue;
            }
            if (argv[i][3] != '=') {
                log_error("Could not identify %s as ASSIGN parameter\n", argv[i]);
                continue;
            }
            int rv = provider_assign(argv[i][2] & 0x0f, &(argv[i][4]));
            if (rv < 0) {
                log_error("Could not assign, error number is %d\n", rv);
            }
        }
    }
}
void cmd_init ()
Definition at line 116 of file fscmd.c.
References chan_init(), and provider_init().
Referenced by main().
                {
    provider_init();
    chan_init();
}
void cmd_loop (int readfd, int writefd)
this is the main loop of the program
Here the data is read from the given readfd, put into a packet buffer, then given to do_cmd() for the actual execution, and the reply is again packeted and written to the writefd
Definition at line 191 of file fscmd.c.
References cmd_sync(), do_cmd(), FS_SYNC, FSP_CMD, FSP_DATA, and FSP_LEN.
Referenced by main().
{
        char buf[8192];
        int wrp,rdp,plen, cmd;
        int n;
    // sync device and server
    cmd_sync(readfd, writefd);
        /* write and read pointers in the input buffer "buf" */
        wrp = rdp = 0;
        while((n=read(readfd, buf+wrp, 8192-wrp))!=0) {
#ifdef DEBUG_READ
          printf("read %d bytes: ",n);
          for(int i=0;i<n;i++) printf("%02x ",255&buf[wrp+i]); printf("\n");
#endif
              if(n<0) {
                fprintf(stderr,"fstcp: read error %d (%s)\n",errno,strerror(errno));
                break;
              }
              wrp+=n;
              if(rdp && (wrp==8192 || rdp==wrp)) {
                if(rdp!=wrp) {
                  memmove(buf, buf+rdp, wrp-rdp);
                }
                wrp -= rdp;
                rdp = 0;
              }
//printf("wrp=%d, rdp=%d, FSP_LEN=%d\n",wrp,rdp,FSP_LEN);
              // as long as we have more than FSP_LEN bytes in the buffer
              // i.e. 2 or more, we loop and process packets
              // FSP_LEN is the position of the packet length
              while(wrp-rdp > FSP_LEN) {
                // first byte in packet is command, second is length of packet
                plen = 255 & buf[rdp+FSP_LEN];  //  AND with 255 to fix sign
                cmd = 255 & buf[rdp+FSP_CMD];   //  AND with 255 to fix sign
//printf("wrp-rdp=%d, plen=%d\n",wrp-rdp,plen);
                // full packet received already?
                if (cmd == FS_SYNC || plen < FSP_DATA) {
          // a packet is at least 3 bytes (when with zero data length)
          // or the byte is the FS_SYNC command
          // so ignore byte and shift one in buffer position
          rdp++;
        } else
                if(wrp-rdp >= plen) {
                  // yes, then execute
                  do_cmd(buf+rdp, writefd);
                  rdp +=plen;
                } else {
                  break;
                }
              }
            }
}