XD2031 pcserver: fsio.c File Reference
fsio.c File Reference
#include <stdio.h>
#include "fscmd.h"
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>
Functions
void usage (void)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 71 of file fsio.c.
References cmd_init(), cmd_loop(), and usage().
{
    int writefd, readfd;
    FILE *fdesc;
    int i, ro=0;
    char *dir;
    char *device = NULL;    /* device name or NULL if stdin/out */
    i=1;
    while(i<argc && argv[i][0]=='-') {
      switch(argv[i][1]) {
        case '?':
        usage();    /* usage() exits already */
        break;
        case 'r':
        if(argv[i][2]=='o') {
          ro=1;
        }
        case 'd':
        if (i < argc-2) {
          i++;
          device = argv[i];
        }
            break;
      }
      i++;
    }
    if(i!=argc-2) {
      usage();
    }
    dir = argv[i++];
    printf("dir=%s\n",dir);
    if(chdir(dir)<0) {
      fprintf(stderr, "Couldn't change to directory %s, errno=%d (%s)\n",
            dir, errno, strerror(errno));
      exit(1);
    }
    if (device != NULL) {
        fdesc = fopen(device, "a+");
        if (fdesc == NULL) {
          /* error */
          fprintf(stderr, "Could not open device %s, errno=%d (%s)\n",
            device, errno, strerror(errno));
          exit(1);
        }
        readfd = fileno(fdesc);
        writefd = readfd;
    }
    cmd_init();
    cmd_loop(readfd, writefd);
    if (device != NULL) {
        fclose(fdesc);
    }
    return 0;
}
void usage (void)
Definition at line 62 of file fsio.c.
Referenced by main().
                 {
    printf("Usage: fsser [options] exported_directory\n"
        " options=\n"
        "   -ro     export read-only\n"
        "   -d <device> define serial device to use\n"
    );
    exit(1);
}