XD2031 pcserver: fstcp.c File Reference
fstcp.c File Reference
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <netdb.h>
#include "fscmd.h"
#include "privs.h"
#include "log.h"
Macros
#define PORT 8090
Functions
void usage (void)
int main (int argc, char *argv[])
Macro Definition Documentation
#define PORT 8090
Definition at line 38 of file fstcp.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 76 of file fstcp.c.
References cmd_assign_from_cmdline(), cmd_init(), cmd_loop(), drop_privileges(), log_error(), PORT, and usage().
{
    int sock, err;
    struct sockaddr_in serv_addr, client_addr, host_addr;
    socklen_t client_addr_len;
    int port=PORT;
    int fd;
    int i, ro=0;
    char *dir, *hname;
    struct hostent *he;
    i=1;
    while(i<argc && argv[i][0]=='-') {
      switch(argv[i][1]) {
        case '?':
        usage();
        break;
        case 'r':
        if(argv[i][2]=='o') {
          ro=1;
        }
        break;
            case 'A':
                // ignore that one, as it will be evaluated later by cmd_...
                break;
            default:
                log_error("Unknown command line option %s\n", argv[i]);
                usage();
                break;
      }
      i++;
    }
    if(i!=argc-2) {
      usage();
    }
    dir = argv[i++];
    printf("dir=%s\n",dir);
    if(chdir(dir)<0) {
      fprintf(stderr, "Couldn't change to directory %s, errno=%d (%s)\n",
            dir, errno, strerror(errno));
      exit(1);
    }
    hname= argv[i++];
    printf("hostname=%s\n",hname);
    he = gethostbyname(hname);
    if(!he) {
      fprintf(stderr, "Could not get hostinfo for %s, h_errno=%d\n",
            hname, h_errno);
      exit(2);
    }
    printf("official name is %s\n",he->h_name);
    if(he->h_addrtype != AF_INET) {
      fprintf(stderr, "Address type for %s not Internet!\n", hname);
      exit(2);
    }
    memcpy((char*)&host_addr.sin_addr.s_addr, he->h_addr_list[0],
                            he->h_length);
/*  host_addr.sin_addr.s_addr = ntohl(*(long*)(he->h_addr_list[0]));*/
    printf("ok, want connection to %08x\n", host_addr.sin_addr.s_addr);
    printf("port=%d\n",port);
    sock = socket(AF_INET, SOCK_STREAM, 0);
    printf("sock=%d\n",sock);
    serv_addr.sin_family=AF_INET;
    serv_addr.sin_port=htons(port);
    serv_addr.sin_addr.s_addr=htonl(INADDR_ANY);
    err = bind(sock, (struct sockaddr*) &serv_addr, sizeof(serv_addr));
    if(err<0) {
      fprintf(stderr, "Could not bind (errno=%d, %s)!\n", errno,
                            strerror(errno));
      return 2;
    }
    err = listen(sock, 1);
    if(err<0) {
      fprintf(stderr, "Could not listen!\n");
      return 2;
    }
    // now we have enough set up to drop privileges
    drop_privileges();
    /* note that this may probably belong into the accept branch (e.g.
     * if we would clone()/fork() after accept */
    cmd_init();
    cmd_assign_from_cmdline(argc, argv);
    while(1) {
      client_addr_len = sizeof(client_addr);
      fd = accept(sock,(struct sockaddr*)&client_addr, &client_addr_len);
      if(fd<0) {
        fprintf(stderr, "Could not accept, errno=%d (%s)!\n",
                        errno, strerror(errno));
        return 2;
      }
      printf("accept request from %08x, port %d, clen=%d, inal=%d\n",
            client_addr.sin_addr.s_addr, client_addr.sin_port,
            client_addr_len, sizeof(struct in_addr));
      if(!memcmp(&client_addr.sin_addr.s_addr,
            &host_addr.sin_addr.s_addr, sizeof(struct in_addr))) {
        close(sock);
        printf("ok, got connection to %04x, port %d\n",
            client_addr.sin_addr.s_addr, client_addr.sin_port);
        cmd_loop(fd, fd);
        exit(0);
      } else {
        printf("connect trial rejected!\n");
        close(fd);
      }
    }
    close(sock);
    return 0;
}
void usage (void)
Definition at line 64 of file fstcp.c.
                 {
    printf("Usage: fsmux [options] run_directory hostname_to_export_to\n"
        " options=\n"
        //"   -ro       export read-only \n"    // does not currently work
        "   -A<drv>=<provider-string>\n"
        "               assign a provider to a drive\n"
        "               e.g. use '-A0=fs:.' to assign the current directory\n"
        "               to drive 0. Dirs are relative to the run_directory param\n"
    );
    exit(1);
}