XD2031 pcserver: log.h File Reference
log.h File Reference
Macros
#define log_rv(rv) log_error("ERROR RETURN: %d\n", (rv))
Functions
void log_errno (const char *msg,...)
void log_warn (const char *msg,...)
void log_error (const char *msg,...)
void log_info (const char *msg,...)
void log_debug (const char *msg,...)
void log_term (const char *msg)
Macro Definition Documentation
#define log_rv (rv) log_error("ERROR RETURN: %d\n", (rv))
Definition at line 40 of file log.h.
Referenced by do_cmd().
Function Documentation
void log_debug (const char * msg, ...)
Definition at line 95 of file log.c.
Referenced by dir_nlst_read_converter(), do_chdir(), do_cmd(), fs_cd(), provider_assign(), pull_data(), readfile(), reply_with_data(), and write_file().
{
       va_list args;
       va_start(args, msg);
       printf("DBG:");
        vprintf(msg, args);
}
void log_errno (const char * msg, ...)
Definition at line 58 of file log.c.
Referenced by _delete_callback(), close_fd(), cmd_sync(), dir_fill_entry(), fs_mkdir(), fs_rename(), fs_rmdir(), fsp_new(), open_dr(), and open_first_match().
{
       va_list args;
       va_start(args, msg);
    char buffer[1024];
    if (index(msg, '%') != NULL) {
        // the msg contains parameter, so we need to fix it
        vsprintf(buffer, msg, args);
        msg = buffer;
    }
        printf(">> %s: errno=%d: %s\n", msg, errno, strerror(errno));
}
void log_error (const char * msg, ...)
Definition at line 79 of file log.c.
Referenced by cmd_assign_from_cmdline(), config_ser(), dir_fill_entry(), dir_nlst_read_converter(), do_chdir(), do_cmd(), fs_cd(), fs_rename(), fsp_new(), main(), open_file(), provider_register(), pull_data(), read_file(), and set_chan().
{
       va_list args;
       va_start(args, msg);
       printf("ERR:");
        vprintf(msg, args);
}
void log_info (const char * msg, ...)
Definition at line 87 of file log.c.
Referenced by chan_to_endpoint(), fsp_new(), malloc_path(), open_dr(), open_file(), open_first_match(), and provider_assign().
{
       va_list args;
       va_start(args, msg);
       printf("INF:");
        vprintf(msg, args);
}
void log_term (const char * msg)
Definition at line 30 of file log.c.
Referenced by do_cmd().
{
    int newline = 0;
    printf(">>>: ");
    char c;
    while ((c = *msg) != 0) {
        if (newline) {
            printf("\n>>>: ");
        }
        if (isprint(c)) {
            putchar(c);
            newline = 0;
        } else
        if (c == 10) {
            newline = 1;
        } else
        if (c == 13) {
            // silently ignore
        } else {
            printf("{%02x}", ((int)c) & 0xff);
            newline = 0;
        }
        msg++;
    }
    printf("\n");
}
void log_warn (const char * msg, ...)
Definition at line 71 of file log.c.
Referenced by close_fds(), find_file(), prov_free(), and reserve_file().
{
       va_list args;
       va_start(args, msg);
       printf("WRN:");
        vprintf(msg, args);
}