XD2031 pcserver: privs.c File Reference
privs.c File Reference
#include <unistd.h>
#include <sys/types.h>
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include "privs.h"
Functions
static void drop_to_uid (uid_t ruid)
void drop_privileges ()
Function Documentation
void drop_privileges ()
drops privilege to the real used id to be used after opening e.g. the serial device (which may be root-only)
Definition at line 41 of file privs.c.
References drop_to_uid().
Referenced by main().
                       {
    uid_t ruid = getuid();
    uid_t euid = geteuid();
    printf("Real user ID=%d\n", ruid);
    printf("Effective user ID=%d\n", euid);
    if (ruid != 0) {
        // not root
        drop_to_uid(ruid);
    }
}
static void drop_to_uid (uid_t ruid) static
Definition at line 55 of file privs.c.
Referenced by drop_privileges().
{
    // in Linux, this releases all privileges, i.e.
    // makes real uid = saved uid = effective uid
    int e = setuid(ruid);
    if (e < 0) {
        fprintf(stderr, "Problem dropping privileges %d!\n", errno);
        exit(-1);
    }
    uid_t new_ruid = getuid();
    if (ruid != new_ruid) {
        fprintf(stderr, "Problem dropping privileges - new ruid not set: %d!\n", new_ruid);
        exit(-1);
    }
    printf("New effective user ID=%d\n", new_ruid);
    e = setuid(0);
    if (e == 0) {
        fprintf(stderr, "Detected problem: was able to regain privileges to uid=%d, euid=%d!\n",
            getuid(), geteuid());
        exit(-1);
    }
}