XD2031 pcserver: provider.c File Reference
provider.c File Reference
#include <stdio.h>
#include <ctype.h>
#include "log.h"
#include "provider.h"
#include "errors.h"
Functions
int provider_register (provider_t *provider)
int provider_assign (int drive, const char *name)
void provider_init ()
endpoint_t * provider_lookup (int drive)
Variables
provider_t http_provider
provider_t ftp_provider
provider_t fs_provider
struct {
provider_t * provider
} providers [MAX_NUMBER_OF_PROVIDERS]
struct {
int epno
endpoint_t * ep
} eptable [MAX_NUMBER_OF_ENDPOINTS]
Function Documentation
int provider_assign (int drive, const char * name)
drive is the endpoint number to assign the new provider to. name denotes the actual provider for the given drive/endpoint
Definition at line 70 of file provider.c.
References ep, epno, eptable, ERROR_FAULT, ERROR_OK, provider_t::freeep, log_debug(), log_info(), MAX_NUMBER_OF_ENDPOINTS, MAX_NUMBER_OF_PROVIDERS, provider_t::name, provider_t::newep, provider, provider_lookup(), providers, and _endpoint::ptype.
Referenced by cmd_assign_from_cmdline(), and do_cmd().
{
    log_info("assign '%s' to drive %d\n", name, drive);
    // find end of name
    int p = 0;
    while (name[p] != 0 && name[p] != ':') {
        p++;
    }
    endpoint_t *parent = NULL;
    provider_t *provider = NULL;
    // check if it is a drive
    if ((isdigit(name[0])) && (p == 1)) {
        // we have a drive number
        int drv = name[0] & 0x0f;
        parent = provider_lookup(drv);
        if (parent != NULL) {
            provider = parent->ptype;
            log_debug("Got drive number: %d, with provider %p\n", drv, provider);
        }
    }
    log_debug("Provider=%p\n", provider);
    if (provider == NULL) {
        // check each of the providers in turn
        for (int i = MAX_NUMBER_OF_PROVIDERS-1; i >= 0; i--) {
            if (providers[i].provider != NULL) {
                log_debug("Compare to provider %s\n", providers[i].provider->name);
                const char *pname = providers[i].provider->name;
                int j = 0;
                for (j = 0; j < p; j++) {
                    if (name[j] != pname[j]) {
                        // provider and assign name do not match
                        break;
                    }
                }
                if ((j == p) && (pname[p] == 0)) {
                    // got one
                    provider = providers[i].provider;
                    log_info("Found provider named '%s'\n", provider->name);
                    break;
                }
            }
        }
    }
    endpoint_t *newep = NULL;
    if (provider != NULL) {
        // get new endpoint
        newep = provider->newep(parent, (name[p] == 0) ? name + p : name + p + 1);
    }
    if (newep != NULL) {
        // check if the drive is already in use and free it if necessary
         int i;
            for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
                    if (eptable[i].epno == drive) {
                provider_t *prevprov = eptable[i].ep->ptype;
                prevprov->freeep(eptable[i].ep);
                            eptable[i].ep = NULL;
                eptable[i].epno = -1;
                break;
                    }
            }
        // register new endpoint
            for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
                    if (eptable[i].epno == -1) {
                eptable[i].ep = newep;
                eptable[i].epno = drive;
                break;
                    }
            }
        return ERROR_OK;
    }
    return ERROR_FAULT;
}
void provider_init (void)
Definition at line 152 of file provider.c.
References eptable, provider_t::init, MAX_NUMBER_OF_ENDPOINTS, and provider_register().
Referenced by cmd_init().
                     {
        int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
          eptable[i].epno = -1;
        }
        // manually handle the initial provider
        fs_provider.init();
    provider_register(&fs_provider);
        ftp_provider.init();
    provider_register(&ftp_provider);
        http_provider.init();
    provider_register(&http_provider);
        //eptable[0].epno = 0;            // drive 0
        //eptable[0].ep = fs_provider.newep(NULL, ".");
    //eptable[1].epno = 9;      // drive 9
    //eptable[1].ep = fs_provider.newep(NULL, "../tools");
        // test
        //eptable[4].epno = 6;            // drive 6
        //eptable[4].ep = fs_provider.newep(NULL, "..");
        // test
        //eptable[6].epno = 7;            // drive 7
        //eptable[6].ep = ftp_provider.newep(NULL, "zimmers.net/pub/cbm");
}
endpoint_t* provider_lookup (int drive)
Definition at line 183 of file provider.c.
References epno, eptable, and MAX_NUMBER_OF_ENDPOINTS.
Referenced by do_cmd(), and provider_assign().
{
        int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
                if (eptable[i].epno == drive) {
                        return eptable[i].ep;
                }
        }
        return NULL;
}
int provider_register (provider_t * provider)
Definition at line 54 of file provider.c.
References log_error(), MAX_NUMBER_OF_ENDPOINTS, provider_t::name, provider, and providers.
Referenced by provider_init().
{
        int i;
        for(i=0;i<MAX_NUMBER_OF_ENDPOINTS;i++) {
            if (providers[i].provider == NULL) {
            providers[i].provider = provider;
            return 0;
        }
        }
    log_error("No space left in provider table for provider %s\n", provider->name);
    return -22;
}
Variable Documentation
endpoint_t* ep
Definition at line 50 of file provider.c.
Referenced by dir_test(), do_cmd(), get_test(), provider_assign(), and set_chan().
int epno
Definition at line 49 of file provider.c.
Referenced by provider_assign(), and provider_lookup().
struct { ... } eptable[MAX_NUMBER_OF_ENDPOINTS]
Referenced by provider_assign(), provider_init(), and provider_lookup().
provider_t fs_provider
provider_t ftp_provider
provider_t http_provider
provider_t* provider
Definition at line 45 of file provider.c.
Referenced by provider_assign(), and provider_register().
struct { ... } providers[MAX_NUMBER_OF_PROVIDERS]
Referenced by provider_assign(), and provider_register().