XD2031 pcserver: provider_t Struct Reference
provider_t Struct Reference
#include <provider.h>
Data Fields
const char * name
void(* init)(void)
endpoint_t *(* newep)(endpoint_t *parent, const char *par)
void(* freeep)(endpoint_t *ep)
void(* close)(endpoint_t *ep, int chan)
int(* open_rd)(endpoint_t *ep, int chan, const char *name)
int(* open_wr)(endpoint_t *ep, int chan, const char *name)
int(* open_ap)(endpoint_t *ep, int chan, const char *name)
int(* open_rw)(endpoint_t *ep, int chan, const char *name)
int(* opendir)(endpoint_t *ep, int chan, const char *name)
int(* readfile)(endpoint_t *ep, int chan, char *retbuf, int len, int *eof)
int(* writefile)(endpoint_t *ep, int chan, char *buf, int len, int is_eof)
int(* scratch)(endpoint_t *ep, char *name, int *outdeleted)
int(* rename)(endpoint_t *ep, char *name)
int(* cd)(endpoint_t *ep, char *name)
int(* mkdir)(endpoint_t *ep, char *name)
int(* rmdir)(endpoint_t *ep, char *name)
Detailed Description
Definition at line 48 of file provider.h.
Field Documentation
int(* cd)(endpoint_t *ep, char *name)
Definition at line 67 of file provider.h.
Referenced by do_cmd().
void(* close)(endpoint_t *ep, int chan)
Definition at line 55 of file provider.h.
Referenced by dir_test(), do_cmd(), and get_test().
void(* freeep)(endpoint_t *ep)
Definition at line 52 of file provider.h.
Referenced by provider_assign().
void(* init)(void)
Definition at line 50 of file provider.h.
Referenced by dir_test(), get_test(), and provider_init().
int(* mkdir)(endpoint_t *ep, char *name)
Definition at line 68 of file provider.h.
Referenced by do_cmd(), and fs_mkdir().
const char* name
Definition at line 49 of file provider.h.
Referenced by do_chdir(), provider_assign(), and provider_register().
endpoint_t*(* newep)(endpoint_t *parent, const char *par)
Definition at line 51 of file provider.h.
Referenced by dir_test(), get_test(), and provider_assign().
int(* open_ap)(endpoint_t *ep, int chan, const char *name)
Definition at line 58 of file provider.h.
Referenced by do_cmd().
int(* open_rd)(endpoint_t *ep, int chan, const char *name)
Definition at line 56 of file provider.h.
Referenced by do_cmd(), and get_test().
int(* open_rw)(endpoint_t *ep, int chan, const char *name)
Definition at line 59 of file provider.h.
int(* open_wr)(endpoint_t *ep, int chan, const char *name)
Definition at line 57 of file provider.h.
Referenced by do_cmd().
int(* opendir)(endpoint_t *ep, int chan, const char *name)
Definition at line 60 of file provider.h.
Referenced by dir_test(), do_cmd(), and open_dr().
int(* readfile)(endpoint_t *ep, int chan, char *retbuf, int len, int *eof)
Definition at line 61 of file provider.h.
Referenced by dir_test(), do_cmd(), and get_test().
int(* rename)(endpoint_t *ep, char *name)
Definition at line 66 of file provider.h.
Referenced by do_cmd(), and fs_rename().
int(* rmdir)(endpoint_t *ep, char *name)
Definition at line 69 of file provider.h.
Referenced by do_cmd(), and fs_rmdir().
int(* scratch)(endpoint_t *ep, char *name, int *outdeleted)
Definition at line 65 of file provider.h.
Referenced by do_cmd().
int(* writefile)(endpoint_t *ep, int chan, char *buf, int len, int is_eof)
Definition at line 62 of file provider.h.
Referenced by do_cmd().
The documentation for this struct was generated from the following file:
provider.h