all:	XD2031-Benutzerhandbuch.tex gpl-2.0.tex
	pdflatex XD2031-Benutzerhandbuch.tex
	MakeIndex XD2031-Benutzerhandbuch.idx
	pdflatex XD2031-Benutzerhandbuch.tex
	# OS X:
	# open XD2031-Benutzerhandbuch.pdf
	# Linux:
	# xdg-open XD2031-Benutzerhandbuch.pdf

