
tests:
	./tests-1541.sh -qq
	./tests-1541-d2.sh -qq
	./tests-1541-relbug1.sh -qq
	./tests-1541-relbug2-67.sh -qq
	./tests-1541-relbug2-6a.sh -qq
	./tests-1571.sh -qq
	./tests-1571-relbug1.sh -qq
	./tests-1581.sh -qq
	./tests-1581-relbug1.sh -qq
	./tests-4040.sh -qq
	./tests-4040-relbug1.sh -qq
	./tests-4040-relpos.sh -qq
	./tests-4040-relopen.sh -qq
	./tests-8050.sh -qq
	./tests-8050-relbug1.sh -qq
	./tests-8250.sh -qq
	./tests-8250-relbug1.sh -qq
	./tests-8250-relpos.sh -qq
	./tests-8250-relrw.sh -qq

