XD2031 firmware: bus.c File Reference
bus.c File Reference
#include "config.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "channel.h"
#include "status.h"
#include "errormsg.h"
#include "cmd.h"
#include "cmd2.h"
#include "file.h"
#include "rtconfig.h"
#include "bus.h"
#include "led.h"
#include "debug.h"
#include "device.h"
Functions
void bus_init ()
void bus_init_bus (bus_t *bus)
static void _cmd_callback (int8_t errnum, uint8_t *rxdata)
static int16_t cmd_handler (bus_t *bus)
int16_t bus_sendbyte (bus_t *bus, uint8_t data, uint8_t with_eoi)
int16_t bus_receivebyte (bus_t *bus, uint8_t *data, uint8_t preload)
static int16_t bus_prepare (bus_t *bus)
static void bus_close (bus_t *bus)
int16_t bus_attention (bus_t *bus, uint8_t b)
Variables
static errormsg_t error
static uint8_t secaddr_offset_counter
static volatile bus_t * bus_for_irq
Function Documentation
static void _cmd_callback (int8_t errnum, uint8_t * rxdata) static
Definition at line 120 of file bus.c.
References bus_t::cmd_done, bus_t::errnum, and bus_t::errparam.
Referenced by cmd_handler().
{
        bus_for_irq->errnum = errnum;
        if (errnum == 1) {
        if (rxdata != NULL) {
            bus_for_irq->errparam = rxdata[1];
        } else {
            bus_for_irq->errparam = 0;
        }
        }
        bus_for_irq->cmd_done = 1;
}
int16_t bus_attention (bus_t * bus, uint8_t b)
Definition at line 359 of file bus.c.
References ACTIVE, bus_close(), bus_prepare(), cmd_handler(), bus_t::current_device_address, debug_flush, debug_printf, bus_t::device, IDLE, led_set(), and bus_t::secondary.
Referenced by ieee_mainloop_iteration().
{
    int16_t st = 0;
    // UNLISTEN and it is either open or the command channel
    if (b == 0x3f
        && (((bus->secondary & 0xf0) == 0xf0)
            || ((bus->secondary & 0x0f) == 0x0f))) {
        if ((bus->device & 0x0f) == bus->current_device_address) {
        // then process the command
            st = cmd_handler(bus);
        }
    } else {
    // not open, not command:
        switch (b & 0xf0) {
          case 0x20:
          case 0x40:
          // store device number plus LISTEN/TALK info
          if ((b & 0x0f) == bus->current_device_address) {
                bus->device = b;
          }
              break;
          case 0x60:
          // secondary address (open DATA channel)
          if ((bus->device & 0x0f) == bus->current_device_address) {
                bus->secondary = b;
            // process a command if necessary
                bus_prepare(bus);
          }
              break;
          case 0xe0:
          // secondary address (CLOSE)
          if ((bus->device & 0x0f) == bus->current_device_address) {
                bus->secondary = b;
            // process a command if necessary
                //st = bus_command(bus);
                bus_close(bus);
          }
              break;
          case 0xf0:            /* Open File needs the filename first */
          if ((bus->device & 0x0f) == bus->current_device_address) {
                bus->secondary = b;
            // TODO: close previously opened file
          }
              break;
      default:
          // falls through e.g. for unlisten/untalk
          break;
        }
    }
    if ((b == 0x3f) || (b == 0x5f) || ((b & 0xf0) == 0xe0)) {
    // unlisten, untalk, close
        bus->device = 0;
        bus->secondary = 0;
    led_set(IDLE);
    } else {
        if (bus->current_device_address != (bus->device & 0x0f)) {
        // not this device
            st |= 0x80;
        } else {
        led_set(ACTIVE);
    }
    }
#ifdef DEBUG_SERIAL
    debug_printf("ParallelAttention(%02x)->TrapDevice=%02x, st=%04x\n",
               b, bus->device, st | (bus->device << 8));
    debug_flush();
#endif
    st |= bus->device << 8;
    return st;
}
static void bus_close (bus_t * bus) static
Definition at line 347 of file bus.c.
References bus_secaddr_adjust(), channel_close(), channel_close_range(), and bus_t::secondary.
Referenced by bus_attention().
{
        uint8_t secaddr = bus->secondary & 0x0f;
          /* Close File */
          if(secaddr == 15) {
        // is this correct or only a convenience?
            channel_close_range(bus_secaddr_adjust(bus, 0), bus_secaddr_adjust(bus, 15));
          } else {
            /* Close a single buffer */
            channel_close(bus_secaddr_adjust(bus, secaddr));
          }
}
void bus_init ()
Definition at line 87 of file bus.c.
References ERROR_DOSVERSION, secaddr_offset_counter, and set_error().
Referenced by main().
                {
    secaddr_offset_counter = 0;
    set_error(&error, ERROR_DOSVERSION);
}
void bus_init_bus (bus_t * bus)
Definition at line 94 of file bus.c.
References bus_t::channel, bus_t::command, cmd_t::command_length, bus_t::current_device_address, bus_t::rtconf, rtconfig_init(), bus_t::secaddr_offset, and secaddr_offset_counter.
Referenced by ieeehwi_init().
{
    bus->secaddr_offset = secaddr_offset_counter;
    secaddr_offset_counter += 16;
    /* Read the hardware-set device address */
    //  device_address = device_hw_address();
    uint8_t devaddr = 8;
    /* Init vars and flags */
    bus->command.command_length = 0;
    // this is copied over after an UNTALK/UNLISTEN
    bus->current_device_address = devaddr;
    rtconfig_init(&(bus->rtconf), devaddr);
    bus->channel = NULL;
}
static int16_t bus_prepare (bus_t * bus) static
Definition at line 308 of file bus.c.
References bus_receivebyte(), bus_secaddr_adjust(), bus_t::channel, channel_find(), bus_t::current_device_address, debug_printf, debug_puts, bus_t::device, and bus_t::secondary.
Referenced by bus_attention().
{
    uint8_t b;
    int8_t secaddr;
    int st = 0;
#ifdef DEBUG_SERIAL
    debug_printf("***ParallelCommand %02x %02x\n",
         bus->device, bus->secondary);
#endif
    if ((bus->device & 0x0f) != bus->current_device_address) {
    return 0x80;    // device not present
    }
    secaddr = bus->secondary & 0x0f;
      if (secaddr != 15) {
            /* Open Channel */
        bus->channel = channel_find(bus_secaddr_adjust(bus, secaddr));
        if (bus->channel == NULL) {
            debug_puts("Did not find channel!\n");
            st |= 0x40; // TODO correct code?
        }
      }
          if ((bus->device & 0xf0) == 0x40) {
            // if we should TALK, prepare the first data byte
            if (!st) {
                    st = bus_receivebyte(bus, &b, 1) & 0xbf;   /* any error, except eof */
            //debug_printf("receive gets st=%04x\n", st);
        } else {
            // cause a FILE NOT FOUND
            debug_puts("FILE NOT FOUND\n");
            bus->device = 0;
        }
          }
    return 0;
}
int16_t bus_receivebyte (bus_t * bus, uint8_t * data, uint8_t preload)
Definition at line 242 of file bus.c.
References bus_secaddr_adjust(), bus_t::channel, channel_close(), channel_current_byte(), channel_current_is_eof(), channel_has_more(), channel_next(), channel_preloadp(), channel_refill(), debug_printf, debug_puts, bus_t::device, errormsg_t::error_buffer, ERROR_FILE_NOT_OPEN, ERROR_OK, errormsg_t::readp, bus_t::secondary, and set_error().
Referenced by bus_prepare(), and talkloop().
{
    int16_t st = 0;
    uint8_t secaddr = bus->secondary & 0x0f;
    channel_t *channel = bus->channel;
    if (secaddr == 15) {
        *data = error.error_buffer[error.readp];
        if (error.error_buffer[error.readp+1] == 0) {
            // send EOF
            st |= 0x40;
        }
        if (!preload) {
            // the real thing
            error.readp++;
            if (error.error_buffer[error.readp] == 0) {
                // finished reading the error message
                // set OK
                set_error(&error, ERROR_OK);
            }
        }
    } else {
        if (channel == NULL) {
        // if still NULL, error
        debug_printf("Setting file not open on secaddr %d\n", bus->secondary);
        set_error(&error, ERROR_FILE_NOT_OPEN);
        st = 0x83;
        } else {
#ifdef DEBUG_SERIAL
        //debug_printf("rx: chan=%p, channo=%d\n", channel, channel->channel_no);
#endif
        // first fillup the buffers
        channel_preloadp(channel);
        *data = channel_current_byte(channel);
        if (channel_current_is_eof(channel)) {
#ifdef DEBUG_SERIAL
            debug_puts("EOF!\n");
#endif
            st |= 0x40;
        }
        if (!preload) {
            // make sure the next call does have a data byte
            if (!channel_next(channel)) {
                if (channel_has_more(channel)) {
                    channel_refill(channel);
                } else {
                        if (secaddr == 15 || secaddr == 0) {
                            // autoclose when load is done, or after reading status channel
                        channel_close(bus_secaddr_adjust(bus, secaddr));
                        bus->channel = NULL;
                    }
                }
            }
        }
        }
    }
    return st + (bus->device << 8);
}
int16_t bus_sendbyte (bus_t * bus, uint8_t data, uint8_t with_eoi)
Definition at line 218 of file bus.c.
References bus_t::channel, channel_put(), bus_t::command, cmd_t::command_buffer, cmd_t::command_length, CONFIG_COMMAND_BUFFER_SIZE, debug_printf, bus_t::device, and bus_t::secondary.
Referenced by listenloop().
{
    int16_t st = 0;
#ifdef DEBUG_SERIAL_DATA
    debug_printf("sendbyte: %02x (%c)\n", data, (isprint(data) ? data : '-'));
#endif
    if((bus->secondary & 0x0f) == 0x0f || (bus->secondary & 0xf0) == 0xf0) {
      if (bus->command.command_length < CONFIG_COMMAND_BUFFER_SIZE) {
        bus->command.command_buffer[bus->command.command_length++] = data;
      }
    } else {
      bus->channel = channel_put(bus->channel, data, with_eoi);
      if (bus->channel == NULL) {
    st = 0x83;  // TODO correct code
      }
    }
    return st + (bus->device << 8);
}
static int16_t cmd_handler (bus_t * bus) static
Definition at line 132 of file bus.c.
References _cmd_callback(), bus, bus_secaddr_adjust(), channel_close(), channel_preload(), bus_t::cmd_done, bus_t::command, cmd_t::command_buffer, command_execute(), cmd_t::command_length, bus_t::current_device_address, debug_printf, rtconfig_t::device_address, bus_t::errnum, ERROR_DRIVE_NOT_READY, bus_t::errparam, file_open(), bus_t::rtconf, bus_t::secondary, serial_delay(), set_error(), and set_error_ts().
Referenced by bus_attention().
{
    int16_t st = 0;
    bus->cmd_done = 0;
    uint8_t secaddr = bus->secondary & 0x0f;
    int8_t rv = 0;
    // prepare for callback from interrupt
    bus_for_irq = bus;
    bus_for_irq->cmd_done = 0;
    // zero termination
    bus->command.command_buffer[bus->command.command_length++] = 0;
    if (secaddr == 0x0f) {
            /* Handle commands */
        // zero termination
            rv = command_execute(bus_secaddr_adjust(bus, secaddr), bus, &error, _cmd_callback);
        // change device address after command
        bus_for_irq->current_device_address = bus_for_irq->rtconf.device_address;
        } else {
            /* Handle filenames */
#ifdef DEBUG_SERIAL
            debug_printf("Open file secaddr=%02x, name='%s'\n",
                secaddr, bus->command.command_buffer);
#endif
            rv = file_open(bus_secaddr_adjust(bus, secaddr), bus, &error,
                            _cmd_callback, secaddr == 1);
        }
        if (rv < 0) {
        // open ran into an error
        // -- errormsg should be already set, so nothing left to do here
        // TODO
        debug_printf("Received direct error number on open: %d\n", rv);
            set_error(&error, ERROR_DRIVE_NOT_READY);
        st = 2;
        } else {
        // as this code is not (yet?) prepared for async operation, we
        // need to wait here until the response from the server comes
        // Note: use bus_for_irq here, as it is volatile
        while (bus_for_irq->cmd_done == 0) {
            // TODO this should be reworked more backend (serial) independent
            serial_delay();
        }
#ifdef DEBUG_SERIAL
        debug_printf("Received callback error number on open: %d\n", bus_for_irq->errnum);
#endif
        // result of the open
        if (bus_for_irq->errnum == 1) {
            set_error_ts(&error, bus_for_irq->errnum, bus_for_irq->errparam, 0);
        } else {
                    set_error(&error, bus_for_irq->errnum);
        }
        // command may (or may not) open channel 15 for callback to the server
        // so close it here, as this is done separately
        if (secaddr == 15) {
            channel_close(bus_secaddr_adjust(bus, 15));
        }
            if (bus_for_irq->errnum != 0) {
                    channel_close(bus_secaddr_adjust(bus, secaddr));
            } else {
                    // really only does something on read-only channels
                    channel_preload(bus_secaddr_adjust(bus, secaddr));
        }
        }
        bus_for_irq->command.command_length = 0;
        return st;
}
Variable Documentation
volatile bus_t* bus_for_irq static
Definition at line 118 of file bus.c.
errormsg_t error static
Definition at line 80 of file bus.c.
uint8_t secaddr_offset_counter static
Definition at line 85 of file bus.c.
Referenced by bus_init(), and bus_init_bus().