XD2031 firmware: channel.c File Reference
channel.c File Reference
#include <stdio.h>
#include <inttypes.h>
#include "delay.h"
#include "packet.h"
#include "channel.h"
#include "provider.h"
#include "serial.h"
#include "led.h"
#include "debug.h"
Macros
#define MAX_CHANNELS 8
Functions
static void _push_callback (int8_t channelno, int8_t errnum)
static void channel_close_int (channel_t *chan, uint8_t force)
void channel_init (void)
static void _pull_callback (int8_t channel_no, int8_t errorno)
static void channel_pull (channel_t *c, uint8_t slot)
int8_t channel_open (int8_t chan, uint8_t writetype, endpoint_t *prov, int8_t(*dirconv)(packet_t *))
channel_t * channel_find (int8_t chan)
static void channel_preload_int (channel_t *chan, uint8_t wait)
void channel_preload (int8_t chan)
void channel_preloadp (channel_t *chan)
char channel_current_byte (channel_t *chan)
uint8_t channel_next (channel_t *chan)
uint8_t channel_has_more (channel_t *chan)
void channel_close (int8_t channel_no)
channel_t * channel_refill (channel_t *chan)
channel_t * channel_put (channel_t *chan, char c, int forceflush)
void channel_close_range (uint8_t fromincl, uint8_t toincl)
Variables
channel_t channels [MAX_CHANNELS]
Macro Definition Documentation
#define MAX_CHANNELS 8
This file implements the central communication channels between the IEEE layer and the provider layers
Definition at line 41 of file channel.c.
Referenced by channel_find(), channel_init(), and channel_open().
Function Documentation
static void _pull_callback (int8_t channel_no, int8_t errorno) static
Definition at line 54 of file channel.c.
References channel_find(), channel_t::last_pull_errorno, PULL_ONECONV, PULL_PRELOAD, PULL_PULL2ND, channel_t::pull_state, and PULL_TWOCONV.
Referenced by channel_pull().
{
    channel_t *p = channel_find(channel_no);
    if (p != NULL) {
        p->last_pull_errorno = errorno;
        // TODO: only if errorno == 0?
        // Probably need some PULL_ERROR as well
        if (p->pull_state == PULL_PRELOAD) {
            p->pull_state = PULL_ONECONV;
        } else
        if (p->pull_state == PULL_PULL2ND) {
            p->pull_state = PULL_TWOCONV;
        }
    }
}
static void _push_callback (int8_t channelno, int8_t errnum) static
Definition at line 329 of file channel.c.
References channel_find(), channel_t::last_push_errorno, PUSH_FILLONE, PUSH_FILLTWO, PUSH_OPEN, and channel_t::push_state.
Referenced by channel_close(), and channel_put().
{
        channel_t *p = channel_find(channelno);
        if (p != NULL) {
                p->last_push_errorno = errnum;
                // TODO: only if errorno == 0?
                // Probably need some PUSH_ERROR as well
                if (p->push_state == PUSH_FILLTWO) {
            // release possibly waiting channel_put()
                        p->push_state = PUSH_FILLONE;
                } else
        if (p->push_state == PUSH_FILLONE) {
            // release possibly waiting channel_close()
            p->push_state = PUSH_OPEN;
        }
        }
}
void channel_close (int8_t channel_no)
Definition at line 250 of file channel.c.
References _push_callback(), channel_t::buf, channel_close_int(), channel_find(), channel_t::current, debug_flush, debug_printf, delayms(), endpoint, channel_t::endpoint, FS_EOF, packet_get_contentlen(), packet_set_filled(), endpoint_t::provdata, endpoint_t::provider, PUSH_FILLONE, PUSH_OPEN, channel_t::push_state, and provider_t::submit_call.
Referenced by bus_close(), bus_receivebyte(), cmd_handler(), and file_submit_call().
{
    channel_t *chan = channel_find(channel_no);
    debug_printf("channel_close(%p -> %d), push_state=%d\n", chan, channel_no, chan->push_state); debug_flush();
    if (chan != NULL) {
        if (chan->push_state != PUSH_OPEN) {
            // if it's not PUSH_FILLONE, then it is in the process
            // of being pushed
            while (chan->push_state != PUSH_FILLONE) {
                delayms(1);
            }
            packet_t *curpack = &chan->buf[chan->current];
            int l = packet_get_contentlen(curpack);
            // even if l==0, send an EOF packet to close the file
                packet_set_filled(curpack, channel_no, FS_EOF, l);
            endpoint_t *endpoint = chan->endpoint;
                    endpoint->provider->submit_call(endpoint->provdata,
                channel_no, curpack, curpack, _push_callback);
                    // wait until the packet has been sent and been responded to
                while (chan->push_state == PUSH_FILLONE) {
                            delayms(1);
            }
        }
        channel_close_int(chan, 0);
    }
}
static void channel_close_int (channel_t * chan, uint8_t force) static
Definition at line 238 of file channel.c.
References channel_t::buf, channel_t::channel_no, channel_t::data, DATA_BUFLEN, packet_init(), PULL_OPEN, channel_t::pull_state, PUSH_OPEN, and channel_t::push_state.
Referenced by channel_close(), channel_close_range(), channel_init(), and channel_refill().
{
    // do nothing but mostly invalidate channel_no,
    // as we do not currently support FS_OPEN_RW yet, which
    // would require an explicit close on the server
    chan->channel_no = -1;
    chan->pull_state = PULL_OPEN;
    chan->push_state = PUSH_OPEN;
    packet_init(&chan->buf[0], DATA_BUFLEN, chan->data[0]);
    packet_init(&chan->buf[1], DATA_BUFLEN, chan->data[1]);
}
void channel_close_range (uint8_t fromincl, uint8_t toincl)
Send message without the final 0x0d */
Definition at line 386 of file channel.c.
References channel_close_int(), and channel_find().
Referenced by bus_close().
{
    for (uint8_t i = fromincl; i <= toincl; i++) {
        // simple, brute force...
        channel_t *chan = channel_find(i);
        if (chan != NULL) {
            // force
            channel_close_int(chan, 1);
        }
    }
}
char channel_current_byte (channel_t * chan)
Definition at line 199 of file channel.c.
References channel_t::buf, channel_preload_int(), channel_t::current, and packet_peek_data().
Referenced by bus_receivebyte().
{
    channel_preload_int(chan, 1);
        return packet_peek_data(&chan->buf[chan->current]);
}
channel_t* channel_find (int8_t chan)
Definition at line 127 of file channel.c.
References MAX_CHANNELS.
Referenced by _pull_callback(), _push_callback(), bus_prepare(), channel_close(), channel_close_range(), channel_preload(), and file_submit_call().
{
    for (int8_t i = MAX_CHANNELS-1; i>= 0; i--) {
        if (channels[i].channel_no == chan) {
            return &channels[i];
        }
    }
    return NULL;
}
uint8_t channel_has_more (channel_t * chan)
Definition at line 232 of file channel.c.
References channel_t::buf, channel_preload_int(), channel_t::current, and packet_is_eof().
Referenced by bus_receivebyte().
{
    // make sure at least one packet is there
    channel_preload_int(chan, 1);
    return !packet_is_eof(&chan->buf[chan->current]);
}
void channel_init (void)
Definition at line 48 of file channel.c.
References channel_close_int(), and MAX_CHANNELS.
Referenced by main().
{
    for (int8_t i = MAX_CHANNELS-1; i>= 0; i--) {
        channel_close_int(&channels[i], 1);
    }
}
uint8_t channel_next (channel_t * chan)
return true (non-zero) when there is still a byte available in the buffer
Definition at line 207 of file channel.c.
References channel_t::buf, channel_preload_int(), channel_pull(), channel_t::current, packet_is_last(), packet_next(), PULL_ONEREAD, and channel_t::pull_state.
Referenced by bus_receivebyte().
{
    // make sure we do have something at least
    channel_preload_int(chan, 1);
//debug_puts("_next: "); debug_puthex(chan->pull_state); debug_putcrlf();
    // this is an optimization:
    // pull in the "other" buffer in the background
    uint8_t other = 1-chan->current;
    //if (packet_is_done(&chan->buf[other]) && (!packet_is_eoi(&chan->buf[chan->current]))) {
    if ((chan->pull_state == PULL_ONEREAD) && (!packet_is_last(&chan->buf[chan->current]))) {
        // if the other packet is free ("done"), and the current packet is not the last one ("eoi")
        // We should only do this on "standard" files though, not relative or others
        channel_pull(chan, other);
    }
    // return the actual value requested
    return packet_next(&chan->buf[chan->current]);
}
int8_t channel_open (int8_t chan, uint8_t writetype, endpoint_t * prov, int8_t(*)(packet_t *) dirconv)
Definition at line 103 of file channel.c.
References buf, channel_t::channel_no, channel_t::current, channel_t::directory_converter, channel_t::endpoint, MAX_CHANNELS, packet_reset(), PULL_OPEN, channel_t::pull_state, PUSH_OPEN, channel_t::push_state, and channel_t::writetype.
Referenced by file_submit_call().
{
//debug_printf("channel_open: chan=%d\n", chan);
    for (int8_t i = MAX_CHANNELS-1; i>= 0; i--) {
        if (channels[i].channel_no < 0) {
            channels[i].channel_no = chan;
            channels[i].current = 0;
            channels[i].writetype = writetype;
            channels[i].endpoint = prov;
            channels[i].directory_converter = dirconv;
            channels[i].pull_state = PULL_OPEN;
            channels[i].push_state = PUSH_OPEN;
            // note: we should not channel_pull() here, as file open has not yet even been sent
            // the pull is done in the open callback for a read-only channel
            for (uint8_t j = 0; j < 2; j++) {
                packet_reset(&channels[i].buf[j], chan);
            }
            return 0;
        }
    }
    return -1;
}
void channel_preload (int8_t chan)
pre-load data for a read-only channel
Definition at line 187 of file channel.c.
References channel_find(), and channel_preload_int().
Referenced by cmd_handler().
{
    channel_t *channel = channel_find(chan);
    if (channel != NULL) {
        channel_preload_int(channel, 1);
    }
}
static void channel_preload_int (channel_t * chan, uint8_t wait) static
Definition at line 136 of file channel.c.
References channel_t::buf, channel_pull(), channel_t::current, delayms(), channel_t::directory_converter, packet_has_data(), packet_is_last(), PULL_ONECONV, PULL_ONEREAD, PULL_OPEN, PULL_PRELOAD, channel_t::pull_state, PULL_TWOCONV, PULL_TWOREAD, channel_t::writetype, and WTYPE_READONLY.
Referenced by channel_current_byte(), channel_has_more(), channel_next(), channel_preload(), and channel_preloadp().
{
    // TODO:fix for read/write
    if (chan->writetype != WTYPE_READONLY) return;
    do {
        if (chan->pull_state == PULL_OPEN) {
        chan->current = 0;
        channel_pull(chan, 0);
        }
        if (wait) {
        while (chan->pull_state == PULL_PRELOAD) {
            delayms(1);
        }
        }
        if (chan->pull_state == PULL_ONECONV) {
        packet_t *curpack = &(chan->buf[chan->current]);
        if ((!packet_has_data(curpack)) && (!packet_is_last(curpack))) {
            // zero length packet received
            chan->pull_state = PULL_OPEN;
        } else {
            if (chan->directory_converter != NULL) {
                //debug_printf(">>1: %p, p=%p\n",chan->directory_converter, &chan->buf[chan->current]);
                //debug_printf(">>1: b=%p\n", packet_get_buffer(&chan->buf[chan->current]));
                chan->directory_converter(&chan->buf[chan->current]);
            }
            chan->pull_state = PULL_ONEREAD;
        }
        }
        if (chan->pull_state == PULL_TWOCONV) {
        packet_t *opack = &(chan->buf[1-chan->current]);
        if ((!packet_has_data(opack)) && (!packet_is_last(opack))) {
            // zero length packet received
            chan->pull_state = PULL_ONEREAD;
        } else {
            if (chan->directory_converter != NULL) {
                //debug_printf(">>2: %p, p=%p\n",chan->directory_converter, &chan->buf[1-chan->current]);
                //debug_printf(">>2: b=%p\n", packet_get_buffer(&chan->buf[1-chan->current]));
                chan->directory_converter(&chan->buf[1-chan->current]);
            }
            chan->pull_state = PULL_TWOREAD;
        }
        }
    }
    while (chan->pull_state == PULL_OPEN);
//led_on();
}
void channel_preloadp (channel_t * chan)
Definition at line 195 of file channel.c.
References channel_preload_int().
Referenced by bus_receivebyte().
{
    channel_preload_int(chan, 1);
}
static void channel_pull (channel_t * c, uint8_t slot) static
pull in a buffer from the server
Definition at line 73 of file channel.c.
References _pull_callback(), channel_t::buf, channel_t::channel_no, endpoint, channel_t::endpoint, FS_READ, packet_set_filled(), endpoint_t::provdata, endpoint_t::provider, PULL_ONEREAD, PULL_OPEN, PULL_PRELOAD, PULL_PULL2ND, channel_t::pull_state, provider_t::submit_call, channel_t::writetype, and WTYPE_READONLY.
Referenced by channel_next(), channel_preload_int(), and channel_refill().
{
    packet_t *p = &c->buf[slot];
    //debug_printf("pull: chan=%p, channo=%d\n", c, c->channel_no);
    // prepare to write a buffer with length 0
    packet_set_filled(p, c->channel_no, FS_READ, 0);
    endpoint_t *endpoint = c->endpoint;
    // not irq-protected, as exlusive state conditions
    if (c->pull_state == PULL_OPEN) {
        c->pull_state = PULL_PRELOAD;
        endpoint->provider->submit_call(endpoint->provdata, c->channel_no, p, p, _pull_callback);
    } else
    if (c->pull_state == PULL_ONEREAD && c->writetype == WTYPE_READONLY) {
        c->pull_state = PULL_PULL2ND;
        endpoint->provider->submit_call(endpoint->provdata, c->channel_no, p, p, _pull_callback);
    }
//led_on();
//debug_puts("pull_state is "); debug_puthex(c->pull_state); debug_putcrlf();
}
channel_t* channel_put (channel_t * chan, char c, int forceflush)
Definition at line 348 of file channel.c.
References _push_callback(), channel_t::buf, channel_t::channel_no, channel_t::current, delayms(), endpoint, channel_t::endpoint, FS_WRITE, packet_get_contentlen(), packet_is_full(), packet_reset(), packet_set_filled(), packet_write_char(), endpoint_t::provdata, endpoint_t::provider, PUSH_FILLONE, PUSH_FILLTWO, PUSH_OPEN, channel_t::push_state, and provider_t::submit_call.
Referenced by bus_sendbyte().
{
    if (chan->push_state == PUSH_OPEN) {
        chan->push_state = PUSH_FILLONE;
    }
    uint8_t channo = chan->channel_no;
    packet_t *curpack = &chan->buf[chan->current];
    packet_write_char(curpack, (uint8_t) c);
    if (packet_is_full(curpack) || forceflush) {
        packet_set_filled(curpack, channo, FS_WRITE, packet_get_contentlen(curpack));
        // wait until the other packet has been replied to,
        // i.e. it has been sent, the buffer is free again
        // which we need for the next channel_put
        while (chan->push_state == PUSH_FILLTWO) {
            delayms(1);
            //serial_delay();
        }
        // note that we pushed one and are now filling the second
        chan->push_state = PUSH_FILLTWO;
        // use same packet as rx/tx buffer
        endpoint_t *endpoint = chan->endpoint;
        endpoint->provider->submit_call(endpoint->provdata,
            channo, curpack, curpack, _push_callback);
        // switch
        chan->current = 1-chan->current;
        packet_reset(&chan->buf[chan->current], channo);
    }
    return chan;
}
channel_t* channel_refill (channel_t * chan)
should be called ONLY(!) when channel_next() false has indicated that the current buffer is empty, but channel_has_more() true has indicated that the current buffer is not the last one
Definition at line 287 of file channel.c.
References channel_t::buf, channel_close_int(), channel_pull(), channel_t::current, delayms(), channel_t::directory_converter, packet_has_data(), packet_is_last(), PULL_ONEREAD, PULL_PULL2ND, channel_t::pull_state, PULL_TWOCONV, and PULL_TWOREAD.
Referenced by bus_receivebyte().
{
    // buf->refill();
    // buf = find_buffer(...)
    //
    uint8_t other = 1-chan->current;
    if (!packet_is_last(&chan->buf[chan->current])) {
        // current packet is not last one
        // other packet should have been pulled in channel_next()
        // so it is either empty (request, or FS_EOF), or has data
        packet_t *opacket = &chan->buf[other];
        // wait until available
        while(chan->pull_state == PULL_PULL2ND) {
            delayms(1);
        }
        if (chan->pull_state == PULL_TWOCONV) {
            if (chan->directory_converter != NULL) {
//debug_printf(">>3: %p, p=%p\n",chan->directory_converter, &chan->buf[1-chan->current]);
//debug_printf(">>3: b=%p\n", packet_get_buffer(&chan->buf[1-chan->current]));
                chan->directory_converter(&chan->buf[1-chan->current]);
            }
            chan->pull_state = PULL_TWOREAD;
        }
        if (packet_has_data(opacket)) {
            // switch packets
            chan->current = other;
            chan->pull_state = PULL_ONEREAD;
            if (!packet_is_last(&chan->buf[chan->current])) {
                channel_pull(chan, 1-other);
            }
            return chan;
        }
    }
    // no more data - close it
    channel_close_int(chan, 0);
    return NULL;
}
Variable Documentation
channel_t channels[MAX_CHANNELS]
Definition at line 43 of file channel.c.