XD2031 firmware: cmd.h File Reference
cmd.h File Reference
#include <stdint.h>
#include "errormsg.h"
#include "rtconfig.h"
#include "config.h"
Data Structures
struct cmd_t
Enumerations
enum command_t {
CMD_NONE, CMD_SYNTAX, CMD_DIR, CMD_INITIALIZE,
CMD_RENAME, CMD_SCRATCH, CMD_CD, CMD_MKDIR,
CMD_RMDIR, CMD_ASSIGN, CMD_EXT
}
Functions
command_t command_find (uint8_t *buf)
const char * command_to_name (command_t cmd)
Enumeration Type Documentation
enum command_t
This file implements the disk drive commands
Enumerator:
CMD_NONE
CMD_SYNTAX
CMD_DIR
CMD_INITIALIZE
CMD_RENAME
CMD_SCRATCH
CMD_CD
CMD_MKDIR
CMD_RMDIR
CMD_ASSIGN
CMD_EXT
Definition at line 37 of file cmd.h.
             {
        // Default
        //
        CMD_NONE,
        CMD_SYNTAX,
        CMD_DIR,
        //
        // CBM DOS commands
        //
        CMD_INITIALIZE,
        CMD_RENAME,
        CMD_SCRATCH,
    //
        // unsupported
        //
        // CMD_VALIDATE,
        // CMD_COPY,
        // CMD_DUPLICATE,
        // CMD_NEW,
        // CMD_POSITION,
        // CMD_BLOCKREAD,
        // CMD_BLOCKWRITE,
        // CMD_UX,
        // CMD_MEM_READ,
        // CMD_MEM_WRITE,
        // CMD_MEM_EXEC,
        //
        // new commands
        //
        CMD_CD,
        CMD_MKDIR,
        CMD_RMDIR,
        CMD_ASSIGN,
    // configuration extension
    CMD_EXT
} command_t;
Function Documentation
command_t command_find (uint8_t * buf)
Definition at line 35 of file cmd.c.
References CMD_ASSIGN, CMD_CD, CMD_DIR, CMD_EXT, CMD_INITIALIZE, CMD_MKDIR, CMD_RENAME, CMD_RMDIR, CMD_SCRATCH, and CMD_SYNTAX.
Referenced by parse_filename().
{
    switch(*input) {
    case '$':
        return CMD_DIR;
        break;
    case 'I':
        return CMD_INITIALIZE;
        break;
    case 'R':
        if (*(input+1) == 'M' || *(input+1) == 'D') {
            // RMDIR or RD
            return CMD_RMDIR;
        }
        return CMD_RENAME;
        break;
    case 'S':
        return CMD_SCRATCH;
        break;
    case 'C':
        if (*(input+1) == 'D' || *(input+1) == 'H') {
            // CD or CHDIR
            return CMD_CD;
        }
        // this would be the COPY command
        return CMD_SYNTAX;
        break;
    case 'M':
        // MKDIR or MD
        return CMD_MKDIR;
        break;
    case 'A':
        return CMD_ASSIGN;
        break;
    case 'X':
        // extensions for XD2031
        return CMD_EXT;
        break;
    }
        return CMD_SYNTAX;
}
const char* command_to_name (command_t cmd)
Definition at line 76 of file cmd.c.
References CMD_ASSIGN, CMD_CD, CMD_DIR, CMD_EXT, CMD_INITIALIZE, CMD_MKDIR, CMD_NONE, CMD_RENAME, CMD_RMDIR, CMD_SCRATCH, and CMD_SYNTAX.
Referenced by command_execute(), file_open(), and parse_filename().
{
        switch(cmd) {
        case CMD_NONE:
                return "-";
                break;
        case CMD_DIR:
                return "$";
                break;
        case CMD_SYNTAX:
                return "?";
                break;
        case CMD_INITIALIZE:
                return "INITIALIZE";
                break;
        case CMD_RENAME:
                return "RENAME";
                break;
        case CMD_SCRATCH:
                return "SCRATCH";
                break;
        case CMD_CD:
                return "CD";
                break;
        case CMD_MKDIR:
                return "MKDIR";
                break;
        case CMD_RMDIR:
                return "RMDIR";
                break;
        case CMD_ASSIGN:
                return "ASSIGN";
                break;
    case CMD_EXT:
        return "EXT";
        break;
        }
        return "";
}