XD2031 firmware: debug.h File Reference
debug.h File Reference
#include "term.h"
#include "mem.h"
Macros
#define DEBUG 1
#define debug_flush() term_flush()
#define debug_puts(s) term_rom_puts(IN_ROM_STR(s))
#define debug_printf(format,...) term_rom_printf(IN_ROM_STR(format), __VA_ARGS__)
Functions
static void debug_putc (char c)
static void debug_putcrlf ()
static void debug_putnib (char c)
static void debug_puthex (char c)
Variables
static char hexnibs []
Macro Definition Documentation
#define DEBUG 1
This file implements the debug print layer
Definition at line 30 of file debug.h.
#define debug_flush () term_flush()
Definition at line 41 of file debug.h.
Referenced by bus_attention(), channel_close(), ieee_mainloop_iteration(), and talkloop().
#define debug_printf (format, ...) term_rom_printf(IN_ROM_STR(format), __VA_ARGS__)
Definition at line 45 of file debug.h.
Referenced by bus_attention(), bus_prepare(), bus_receivebyte(), bus_sendbyte(), channel_close(), cmd_handler(), command_execute(), file_open(), ieee_mainloop_iteration(), parse_filename(), provider_assign(), provider_lookup(), provider_register(), rtconfig_set(), serial_submit_call(), and set_error_ts().
#define debug_puts (s) term_rom_puts(IN_ROM_STR(s))
Definition at line 42 of file debug.h.
Referenced by bus_prepare(), bus_receivebyte(), command_execute(), directory_converter(), file_open(), file_submit_call(), parse_filename(), provider_assign(), and provider_lookup().
Function Documentation
static void debug_putc (char c) inline static
Definition at line 38 of file debug.h.
References term_putc().
Referenced by command_execute(), debug_putnib(), directory_converter(), file_open(), file_submit_call(), ieee_mainloop_iteration(), listenloop(), parse_filename(), and talkloop().
{ term_putc(c); }
static void debug_putcrlf () inline static
Definition at line 39 of file debug.h.
References term_flush(), and term_putcrlf().
Referenced by command_execute(), directory_converter(), file_open(), file_submit_call(), ieee_mainloop_iteration(), parse_filename(), and set_atn_irq().
{  term_putcrlf(); term_flush(); }
static void debug_puthex (char c) inline static
Definition at line 55 of file debug.h.
References debug_putnib().
Referenced by directory_converter(), file_submit_call(), and set_atn_irq().
{
    debug_putnib(c>>4);
    debug_putnib(c);
}
static void debug_putnib (char c) inline static
Definition at line 51 of file debug.h.
References debug_putc(), and hexnibs.
Referenced by debug_puthex().
{
    debug_putc(hexnibs[c&15]);
}
Variable Documentation
char hexnibs[] static
Initial value:
= {'0','1','2','3','4','5','6','7',
                         '8','9','a','b','c','d','e','f' }
Definition at line 48 of file debug.h.
Referenced by debug_putnib().