XD2031 firmware: delay.h File Reference
delay.h File Reference
#include "delayhw.h"
Functions
void serial_delay ()
static void delayms (uint8_t t)
static void delayus (uint8_t us)
Function Documentation
static void delayms (uint8_t t) inline static
Definition at line 35 of file delay.h.
References delayhw_ms, and serial_delay().
Referenced by channel_close(), channel_preload_int(), channel_put(), channel_refill(), and packet_wait_done().
{
    uint8_t ms = t;
    do {
        serial_delay();
        delayhw_ms(1);
        ms--;
    }
    while (ms > 0);
}
static void delayus (uint8_t us) inline static
Definition at line 45 of file delay.h.
References delayhw_us.
{
    delayhw_us(us);
}
void serial_delay ()
Definition at line 453 of file serial.c.
Referenced by cmd_handler(), delayms(), main(), serial_flush(), serial_submit(), and serial_submit_call().
                    {
    // can we receive?
    int16_t data = uarthw_receive();
    while (data >= 0) {
        push_data_to_packet(0xff & data);
        // try next byte
        data = uarthw_receive();
    }
    // try to send
    send();
}