XD2031 firmware: errormsg.c File Reference
errormsg.c File Reference
#include <string.h>
#include <ctype.h>
#include "mem.h"
#include "errormsg.h"
#include "channel.h"
#include "version.h"
#include "device.h"
#include "debug.h"
#include "led.h"
Macros
#define DEBUG_ERROR
#define H(v) ((v)|0x80)
Functions
static uint8_t * appendmsg (uint8_t *msg, const uint8_t *table, const uint8_t code)
uint8_t * appendnumber (uint8_t *msg, uint8_t value)
void set_error_ts (errormsg_t *err, uint8_t errornum, uint8_t track, uint8_t sector)
Variables
const char IN_ROM versionstr [] = HW_NAME "/" SW_NAME " V" VERSION LONGVERSION
Version number string, will be added to message 73.
static const uint8_t IN_ROM tokens []
static const uint8_t IN_ROM messages []
Macro Definition Documentation
#define DEBUG_ERROR
Definition at line 34 of file errormsg.c.
#define H (v) ((v)|0x80)
Definition at line 39 of file errormsg.c.
Referenced by appendmsg().
Function Documentation
static uint8_t* appendmsg (uint8_t * msg, const uint8_t * table, const uint8_t code) static
Definition at line 78 of file errormsg.c.
References H, rom_read_byte, and tokens.
Referenced by set_error_ts().
{
    uint8_t *ptr = (uint8_t*) table; // table index
    uint8_t pattern = H(code);
    // first find the code in the give table
    uint8_t c = rom_read_byte(ptr);
    while (c != 0 && c != pattern) {
        ptr++;
        c = rom_read_byte(ptr);
    }
    if (c == 0) {
        // not found
        return msg;
    }
    // skip over remaining codes
    c = rom_read_byte(ptr);
    while (c & 0x80) {
        ptr++;
        c = rom_read_byte(ptr);
    }
    // now ptr points to the first text entry
    // c contains the value
    do {
        if (c < 32) {
            // get text from token table (recursive)
            msg = appendmsg(msg, tokens, c);
        } else {
            *msg = c;
            msg++;
        }
        ptr++;
        c = rom_read_byte(ptr);
    } while (c != 0 && (c & 0x80) == 0);
    return msg;
}
uint8_t* appendnumber (uint8_t * msg, uint8_t value)
Definition at line 117 of file errormsg.c.
Referenced by set_error_ts().
{
    if (value >= 100) {
            *msg++ = '0' + value/100;
            value %= 100;
    }
    *msg++ = '0' + value/10;
    *msg++ = '0' + value%10;
    return msg;
}
void set_error_ts (errormsg_t * err, uint8_t errornum, uint8_t track, uint8_t sector)
Definition at line 128 of file errormsg.c.
References appendmsg(), appendnumber(), debug_printf, ERROR, errormsg_t::error_buffer, ERROR_DOSVERSION, ERROR_OK, ERROR_SCRATCHED, led_set(), messages, OFF, errormsg_t::readp, rom_read_byte, and versionstr.
Referenced by cmd_handler(), and set_error().
{
    uint8_t *msg = err->error_buffer;
    err->readp = 0;
    msg = appendnumber(msg,errornum);
    *msg++ = ',';
    if (errornum == ERROR_DOSVERSION) {
        char *p = (char*) versionstr;
        uint8_t c;
        while ((c = rom_read_byte(p++)) != 0) {
            *msg++ = c;
        }
    } else {
            msg = appendmsg(msg,messages,errornum);
    }
    *msg++ = ',';
    msg = appendnumber(msg,track);
    *msg++ = ',';
    msg = appendnumber(msg,sector);
    *msg++ = 13;
    // end string marker
    *msg = 0;
    if (errornum != ERROR_OK && errornum != ERROR_DOSVERSION && errornum != ERROR_SCRATCHED) {
        led_set(ERROR);
    } else {
        // same as idle, but clears error
        led_set(OFF);
    }
#ifdef DEBUG_ERROR
debug_printf("Set status to: %s\n", err->error_buffer);
#endif
}
Variable Documentation
const uint8_t IN_ROM messages[] static
Initial value:
= {
    H(ERROR_OK),            ' ','O','K',
    H(ERROR_SCRATCHED),         2,'S',' ','S','C','R','A','T','C','H','E','D',
    H(ERROR_WRITE_PROTECT),     3,'P','R','O','T','E','C','T',' ',1,
    H(ERROR_WRITE_ERROR),       3,1,
    H(ERROR_SYNTAX_UNKNOWN),
    H(ERROR_SYNTAX_NONAME),
    H(ERROR_SYNTAX_INVAL),
    H(ERROR_SYNTAX_DIR_SEPARATOR),
    H(ERROR_FILE_NAME_TOO_LONG),    4,1,
    H(ERROR_FILE_NOT_FOUND),    2,' ',5,7,
    H(ERROR_FILE_NOT_OPEN),     2,' ',5,6,
    H(ERROR_FILE_EXISTS),       2,' ','E','X','I','S','T','S',
    H(ERROR_FILE_TYPE_MISMATCH),    2,' ','T','Y','P','E',' ','M','I','S','M','A','T','C','H',
    H(ERROR_DIR_NOT_EMPTY),     8,  5,'E','M','T','Y',
    H(ERROR_NO_PERMISSION),     9,'P','E','R','M','I','S','S','I','O','N',
    H(ERROR_FAULT),         'G','E','N','E','R','A','L',' ','F','A','U','L','T',
    H(ERROR_NO_CHANNEL),        9,'C','H','A','N','N','E','L',
    H(ERROR_DIR_ERROR),     8,1,
    H(ERROR_DISK_FULL),     'D','I','S','K',' ','F','U','L','L',
    H(ERROR_DRIVE_NOT_READY),   'D','R','I','V','E',' ',  5,'R','E','A','D','Y',
    0
}
Definition at line 54 of file errormsg.c.
Referenced by set_error_ts().
const uint8_t IN_ROM tokens[] static
Initial value:
= {
    "\201ERROR"
    "\202FILE"
    "\203WRITE "
    "\204SYNTAX "
    "\205NOT "
    "\206OPEN"
    "\207FOUND"
    "\210DIR "
    "\211NO "
}
Definition at line 41 of file errormsg.c.
Referenced by appendmsg().
const char IN_ROM versionstr[] = HW_NAME "/" SW_NAME " V" VERSION LONGVERSION
Version number string, will be added to message 73.
Definition at line 37 of file errormsg.c.
Referenced by set_error_ts().