XD2031 firmware: errormsg.h File Reference
errormsg.h File Reference
#include <stdint.h>
#include "config.h"
#include "errors.h"
Data Structures
struct errormsg_t
Functions
void set_error_ts (errormsg_t *error, uint8_t errornum, uint8_t track, uint8_t sector)
static void set_error (errormsg_t *error, uint8_t errornum)
Function Documentation
static void set_error (errormsg_t * error, uint8_t errornum) inline static
Definition at line 52 of file errormsg.h.
References set_error_ts().
Referenced by bus_init(), bus_receivebyte(), cmd_handler(), command_execute(), file_open(), and file_submit_call().
{
    set_error_ts(error, errornum, 0, 0);
}
void set_error_ts (errormsg_t * error, uint8_t errornum, uint8_t track, uint8_t sector)
Definition at line 128 of file errormsg.c.
References appendmsg(), appendnumber(), debug_printf, ERROR, errormsg_t::error_buffer, ERROR_DOSVERSION, ERROR_OK, ERROR_SCRATCHED, led_set(), messages, OFF, errormsg_t::readp, rom_read_byte, and versionstr.
Referenced by cmd_handler(), and set_error().
{
    uint8_t *msg = err->error_buffer;
    err->readp = 0;
    msg = appendnumber(msg,errornum);
    *msg++ = ',';
    if (errornum == ERROR_DOSVERSION) {
        char *p = (char*) versionstr;
        uint8_t c;
        while ((c = rom_read_byte(p++)) != 0) {
            *msg++ = c;
        }
    } else {
            msg = appendmsg(msg,messages,errornum);
    }
    *msg++ = ',';
    msg = appendnumber(msg,track);
    *msg++ = ',';
    msg = appendnumber(msg,sector);
    *msg++ = 13;
    // end string marker
    *msg = 0;
    if (errornum != ERROR_OK && errornum != ERROR_DOSVERSION && errornum != ERROR_SCRATCHED) {
        led_set(ERROR);
    } else {
        // same as idle, but clears error
        led_set(OFF);
    }
#ifdef DEBUG_ERROR
debug_printf("Set status to: %s\n", err->error_buffer);
#endif
}