XD2031 firmware: file.h File Reference
file.h File Reference
#include <stdint.h>
#include "cmd.h"
#include "channel.h"
#include "bus.h"
Functions
void file_init (void)
int8_t file_open (uint8_t channel_no, bus_t *bus, errormsg_t *errormsg, void(*callback)(int8_t errnum, uint8_t *rxdata), uint8_t is_save)
uint8_t file_submit_call (uint8_t channel_no, uint8_t type, errormsg_t *errormsg, rtconfig_t *rtconf, void(*callback)(int8_t errnum, uint8_t *rxdata))
Function Documentation
void file_init (void)
Definition at line 54 of file file.c.
References open_t::channel_no, and MAX_ACTIVE_OPEN.
Referenced by main().
                     {
    for (uint8_t i = 0; i < MAX_ACTIVE_OPEN; i++) {
        active[i].channel_no = -1;
    }
}
int8_t file_open (uint8_t channel_no, bus_t * bus, errormsg_t * errormsg, void(*)(int8_t errnum, uint8_t *rxdata) callback, uint8_t is_save)
Definition at line 69 of file file.c.
References nameinfo_t::access, assert_not_null, callback, nameinfo_t::cmd, CMD_DIR, CMD_NONE, bus_t::command, cmd_t::command_buffer, command_to_name(), debug_printf, debug_putc(), debug_putcrlf(), debug_puts, ERROR_FILE_EXISTS, ERROR_FILE_TYPE_MISMATCH, ERROR_SYNTAX_UNKNOWN, file_submit_call(), FS_OPEN_AP, FS_OPEN_DR, FS_OPEN_RD, FS_OPEN_WR, nameinfo, parse_filename(), bus_t::rtconf, set_error(), and nameinfo_t::type.
Referenced by cmd_handler().
{
    assert_not_null(bus, "file_open: bus is null");
    cmd_t *command = &(bus->command);
    rtconfig_t *rtconf = &(bus->rtconf);
#ifdef DEBUG_FILE
    debug_printf("OPEN FILE: FOR CHAN: %d WITH NAME: %s\n",
        channel_no, (char*)&(command->command_buffer));
#endif
    // note: in a preemtive env, the following would have to be protected
    // to be atomic as we modify static variables
    parse_filename(command, &nameinfo, 0);
    // post-parse
    if (nameinfo.cmd != CMD_NONE && nameinfo.cmd != CMD_DIR) {
        // command name during open
        // this is in fact ignored by CBM DOS as checked with VICE's true drive emulation
        debug_printf("NO CORRECT CMD: %s\n", command_to_name(nameinfo.cmd));
        nameinfo.cmd = 0;
    }
    if (nameinfo.type != 0 && nameinfo.type != 'S' && nameinfo.type != 'P') {
        // not set, or set as not sequential and not program
        debug_puts("UNKOWN FILE TYPE: "); debug_putc(nameinfo.type); debug_putcrlf();
        set_error(errormsg, ERROR_FILE_TYPE_MISMATCH);
        return -1;
    }
    if (nameinfo.access != 0 && nameinfo.access != 'W' && nameinfo.access != 'R'
            && nameinfo.access != 'A') {
        debug_puts("UNKOWN FILE ACCESS TYPE "); debug_putc(nameinfo.access); debug_putcrlf();
        // not set, or set as not read, write, or append
        set_error(errormsg, ERROR_SYNTAX_UNKNOWN);
        return -1;
    }
    if (nameinfo.cmd == CMD_DIR && (nameinfo.access != 0 && nameinfo.access != 'R')) {
        // trying to write to a directory
        debug_puts("WRITE TO DIRECTORY!"); debug_putcrlf();
        set_error(errormsg, ERROR_FILE_EXISTS);
        return -1;
    }
    uint8_t type = FS_OPEN_RD;
    // either ",W" or secondary address is one, i.e. save
    if (nameinfo.access == 'W' || is_save) type = FS_OPEN_WR;
    if (nameinfo.access == 'A') type = FS_OPEN_AP;
    if (nameinfo.cmd == CMD_DIR) type = FS_OPEN_DR;
    return file_submit_call(channel_no, type, errormsg, rtconf, callback);
}
uint8_t file_submit_call (uint8_t channel_no, uint8_t type, errormsg_t * errormsg, rtconfig_t * rtconf, void(*)(int8_t errnum, uint8_t *rxdata) callback)
Definition at line 126 of file file.c.
References _file_open_callback(), assert_not_null, open_t::callback, callback, channel_close(), channel_find(), open_t::channel_no, channel_open(), debug_putc(), debug_putcrlf(), debug_puthex(), debug_puts, provider_t::directory_converter, nameinfo_t::drive, endpoint, ERROR_DRIVE_NOT_READY, ERROR_NO_CHANNEL, ERROR_SYNTAX_NONAME, FS_OPEN_AP, FS_OPEN_DR, FS_OPEN_WR, rtconfig_t::last_used_drive, MAX_ACTIVE_OPEN, nameinfo_t::name, nameinfo, nameinfo_t::namelen, OPEN_RX_DATA_LEN, packet_init(), packet_set_filled(), endpoint_t::provdata, provider, endpoint_t::provider, provider_lookup(), open_t::rxbuf, open_t::rxdata, set_error(), provider_t::submit_call, provider_t::to_provider, and open_t::txbuf.
Referenced by command_execute(), and file_open().
{
    assert_not_null(errormsg, "file_submit_call: errormsg is null");
    assert_not_null(rtconf, "file_submit_call: rtconf is null");
    // check for default drive (here is the place to set the last used one)
    if (nameinfo.drive == 0xff) {
        // there currently only is a single drive, 0
        nameinfo.drive = rtconf->last_used_drive;
        // TODO: fix this hack!
        nameinfo.name[0] = rtconf->last_used_drive;
    }
    // here is the place to plug in other file system providers,
    // like SD-Card, or even an outgoing IEC or IEEE, to convert between
    // the two bus systems. This is done depending on the drive number
    // and managed with the ASSIGN call.
    //provider_t *provider = &serial_provider;
    endpoint_t *endpoint = provider_lookup(nameinfo.drive);
    // check the validity of the drive (note that in general provider_lookup
    // returns a default provider - serial-over-USB to the PC, which then
    // may do further checks
    if (endpoint == NULL) {
        debug_puts("ILLEGAL DRIVE: "); debug_putc(0x30+nameinfo.drive); debug_putcrlf();
        set_error(errormsg, ERROR_DRIVE_NOT_READY);
        return -1;
    }
    provider_t *provider = endpoint->provider;
    // find open slot
    //int8_t slot = -1;
    open_t *activeslot = NULL;
    for (uint8_t i = 0; i < MAX_ACTIVE_OPEN; i++) {
        if (active[i].channel_no < 0) {
            //slot = i;
            activeslot = (open_t*) &active[i];
            break;
        }
    }
    //if (slot < 0) {
    if (activeslot == NULL) {
        debug_puts("NO OPEN SLOT FOR OPEN!");
        debug_putcrlf();
        set_error(errormsg, ERROR_NO_CHANNEL);
        return -1;
    }
    packet_init(&activeslot->txbuf, nameinfo.namelen, nameinfo.name);
    packet_set_filled(&activeslot->txbuf, channel_no, type, nameinfo.namelen);
    if (provider->to_provider != NULL && provider->to_provider(&activeslot->txbuf) < 0) {
        // converting the file name to the provider exceeded the buffer space
        debug_puts("NAME CONVERSION EXCEEDS BUFFER!");
        debug_putcrlf();
        set_error(errormsg, ERROR_SYNTAX_NONAME);
        return -1;
    }
    // open channel
    uint8_t writetype = (type == FS_OPEN_WR || type == FS_OPEN_AP) ? 1 : 0;
    int8_t (*converter)(packet_t*) = (type == FS_OPEN_DR) ? (provider->directory_converter) : NULL;
    channel_t *channel = channel_find(channel_no);
    if (channel != NULL) {
        debug_puts("FILE OPEN ERROR");
        debug_putcrlf();
        set_error(errormsg, ERROR_NO_CHANNEL);
        // clean up
        channel_close(channel_no);
        return -1;
    }
    int8_t e = channel_open(channel_no, writetype, endpoint, converter);
    if (e < 0) {
        debug_puts("E="); debug_puthex(e); debug_putcrlf();
        set_error(errormsg, ERROR_NO_CHANNEL);
        return -1;
    }
    activeslot->callback = callback;
    // no more error here, just the submit.
    // so callers can be sure if this function returns <0, they do not need
    // to close the channel, as it has not been opened
    // If this function returns 0, a callback must be received and handled,
    // and the channel is already opened.
    activeslot->channel_no = channel_no;
    // prepare response buffer
    packet_init(&activeslot->rxbuf, OPEN_RX_DATA_LEN, activeslot->rxdata);
    provider->submit_call(endpoint->provdata, channel_no, &activeslot->txbuf,
            &activeslot->rxbuf, _file_open_callback);
    return 0;
}