XD2031 firmware: ieee.h File Reference
ieee.h File Reference
Functions
void ieeehwi_init (uint8_t deviceno)
void ieee_mainloop_iteration (void)
Function Documentation
void ieee_mainloop_iteration (void)
Definition at line 211 of file ieee.c.
References atnahi(), atnalo(), atnishi(), bus_attention(), davishi(), davislo(), debug_flush, debug_printf, debug_putc(), debug_putcrlf(), ieeehw_setup(), isListening, isTalking, listenloop(), ndachi(), ndaclo(), nrfdhi(), nrfdlo(), par_status, rdd(), setrx(), and talkloop().
Referenced by main().
{
        int cmd = 0;
    // only do something on ATN low
    if (atnishi()) {
        return;
    }
    // set receive mode
    setrx();
        par_status=0;
        /* Loop to get commands during ATN lo ----------------------------*/
        while(1)
        {
            ndaclo();
        // acknowledge ATN
            atnalo();
            nrfdhi();
            /* wait for DAV lo */
            do {
                if(atnishi()) {
            // ATN hi, end loop
                    goto cmd;
                }
            } while(davishi());
            nrfdlo();
        // read data
            cmd=rdd();
        // ack with ndac hi
            ndachi();
            par_status = bus_attention(&bus, cmd);
        // wait until DAV goes up
//      do {
//      if (atnishi()) {
//          // ATN hi, end loop
//          goto cmd;
//      }
//      }
            while(davislo());
        }
        /* ---------------------------------------------------------------*/
    // ATN is high now
    // parallelattention has set status what to do
    // now transfer the data
cmd:
#ifdef DEBUG_BUS
    debug_printf("stat=%04x", par_status); debug_putcrlf();
#endif
    if(isListening())
        {
        // make sure nrfd stays lo...
        nrfdlo();
        // ... when we un-acknowlege the ATN
        // (which is already hi anyway)
                atnahi();
                listenloop();
        } else
        {
                atnahi();
                nrfdhi();
                if(isTalking()) {
                    talkloop();
                }
        }
    ieeehw_setup();
#ifdef DEBUG_BUS
    debug_putc('X'); debug_flush();
#endif
        return;
}
void ieeehwi_init (uint8_t deviceno)
Definition at line 298 of file ieee.c.
References bus_init_bus(), and ieeehw_setup().
Referenced by main().
{
        ieeehw_setup();
    // register bus instance
    bus_init_bus(&bus);
}