XD2031 firmware: ieee.c File Reference
ieee.c File Reference
#include <ctype.h>
#include "ieeehw.h"
#include "errormsg.h"
#include "cmd.h"
#include "channel.h"
#include "bus.h"
#include "debug.h"
#include "led.h"
Macros
#define isListening() ((par_status&0xf000)==0x2000)
#define isTalking() ((par_status&0xf000)==0x4000)
Functions
void talkloop (void)
void listenloop (void)
int16_t liecin (int *c)
void ieee_mainloop_iteration (void)
void ieeehwi_init (uint8_t deviceno)
Variables
static bus_t bus
static int16_t par_status = 0
Macro Definition Documentation
#define isListening () ((par_status&0xf000)==0x2000)
Definition at line 46 of file ieee.c.
Referenced by ieee_mainloop_iteration().
#define isTalking () ((par_status&0xf000)==0x4000)
Definition at line 47 of file ieee.c.
Referenced by ieee_mainloop_iteration().
Function Documentation
void ieee_mainloop_iteration (void)
Definition at line 211 of file ieee.c.
References atnahi(), atnalo(), atnishi(), bus_attention(), davishi(), davislo(), debug_flush, debug_printf, debug_putc(), debug_putcrlf(), ieeehw_setup(), isListening, isTalking, listenloop(), ndachi(), ndaclo(), nrfdhi(), nrfdlo(), par_status, rdd(), setrx(), and talkloop().
Referenced by main().
{
        int cmd = 0;
    // only do something on ATN low
    if (atnishi()) {
        return;
    }
    // set receive mode
    setrx();
        par_status=0;
        /* Loop to get commands during ATN lo ----------------------------*/
        while(1)
        {
            ndaclo();
        // acknowledge ATN
            atnalo();
            nrfdhi();
            /* wait for DAV lo */
            do {
                if(atnishi()) {
            // ATN hi, end loop
                    goto cmd;
                }
            } while(davishi());
            nrfdlo();
        // read data
            cmd=rdd();
        // ack with ndac hi
            ndachi();
            par_status = bus_attention(&bus, cmd);
        // wait until DAV goes up
//      do {
//      if (atnishi()) {
//          // ATN hi, end loop
//          goto cmd;
//      }
//      }
            while(davislo());
        }
        /* ---------------------------------------------------------------*/
    // ATN is high now
    // parallelattention has set status what to do
    // now transfer the data
cmd:
#ifdef DEBUG_BUS
    debug_printf("stat=%04x", par_status); debug_putcrlf();
#endif
    if(isListening())
        {
        // make sure nrfd stays lo...
        nrfdlo();
        // ... when we un-acknowlege the ATN
        // (which is already hi anyway)
                atnahi();
                listenloop();
        } else
        {
                atnahi();
                nrfdhi();
                if(isTalking()) {
                    talkloop();
                }
        }
    ieeehw_setup();
#ifdef DEBUG_BUS
    debug_putc('X'); debug_flush();
#endif
        return;
}
void ieeehwi_init (uint8_t deviceno)
Definition at line 298 of file ieee.c.
References bus_init_bus(), and ieeehw_setup().
Referenced by main().
{
        ieeehw_setup();
    // register bus instance
    bus_init_bus(&bus);
}
int16_t liecin (int * c)
Definition at line 61 of file ieee.c.
References atnislo(), davishi(), davislo(), E_ATN, E_EOI, eoiishi(), ndachi(), ndaclo(), nrfdhi(), nrfdlo(), and rdd().
Referenced by listenloop().
{
        int er = 0;
        nrfdhi();
    // do...while to make sure to at least test ATN once
        do {
            if(atnislo()) {
        // ATN got low, exit
                goto atn;
            }
        } while( davishi() );
        nrfdlo();
        if(!eoiishi())
                er|=E_EOI;
        *c=rdd();
        ndachi();
        do {
            if(atnislo()) {
        // ATN got low, exit
                //break;
                goto atn;
            }
        } while( davislo() );
        ndaclo();
        return(er);
atn:
    // we do not need to do anything,
    // as we already are in listen mode, and the
    // ACK hardware or software has just pulled
    // NRFD and NDAC
        return E_ATN;
}
void listenloop (void)
Definition at line 103 of file ieee.c.
References bus_sendbyte(), debug_putc(), E_ATN, E_EOI, liecin(), par_status, and setidle.
Referenced by ieee_mainloop_iteration().
                  {
#ifdef DEBUG_BUS
    debug_putc('L');
#endif
        int er, c;
        while(((er=liecin(&c))&E_ATN)!=E_ATN) {
            par_status = bus_sendbyte(&bus, c, er & E_EOI);
        }
    // if did not stop due to ATN, set to idle,
    // otherwise stay in rx mode
    if (er != E_ATN) {
        setidle();
    }
        return;
}
void talkloop (void)
Hardware-independent IEEE layer
Definition at line 121 of file ieee.c.
References atnislo(), bus_receivebyte(), davhi(), davlo(), debug_flush, debug_putc(), E_EOI, E_NODEV, eoihi(), eoilo(), ndacishi(), ndacislo(), nrfdishi(), nrfdislo(), par_status, setidle, setrx(), settx(), and wrd().
Referenced by ieee_mainloop_iteration().
{
        int16_t er /*,sec*/;
        uint8_t c;
#ifdef DEBUG_BUS
    debug_putc('T'); debug_flush();
#endif
        settx();            /* enables sending */
        er=0;
        /*sec=secadr&0x0f;*/
        while (!er) {
            /* wait nrfd hi */
            do {
                if( atnislo() ) {
            goto atn;
        }
            } while( nrfdislo() );
            /* write data & eoi */
            par_status = bus_receivebyte(&bus, &c, 1);
            if(par_status & 0x40)
            {
                eoilo();
                er|=E_EOI;
            }
            wrd(c);
            davlo();
            /* wait nrfd lo */
            do {
                if( atnislo() ) {
            goto atn;
        }
                if( ndacishi() && nrfdishi() ) {
                    eoihi();
                    davhi();
            er |= E_NODEV;
            goto idle;
                }
            } while( nrfdishi() );
            /* wait ndac hi */
            do {
                if ( atnislo() ) {
            // ATN got low
                    goto atn;
                }
            } while( ndacislo() );
            davhi();
            eoihi();
            par_status = bus_receivebyte(&bus, &c, 0);
            /* wait ndac lo */
            if( par_status & 0xff ) {
                break;
            } else {
                do {
                    if ( atnislo() ) {
                        goto atn;
                    }
                } while( ndacishi() );
            }
        }
    // no ATN, so set bus to idle
    setidle();
        return; //(er&(E_EOI));
atn:
    // sets IEEE488 back to receive mode
        setrx();
        return; //(er&(E_EOI));
idle:
    // after EOF we set bus to idle
    setidle();
        return; //(er&(E_EOI));
}
Variable Documentation
bus_t bus static
Definition at line 50 of file ieee.c.
Referenced by cmd_handler().
int16_t par_status = 0 static
Definition at line 53 of file ieee.c.
Referenced by ieee_mainloop_iteration(), listenloop(), and talkloop().