XD2031 firmware: led.h File Reference
led.h File Reference
Enumerations
enum led_t {
IDLE = 0, OFF = 1, ON = 2, ACTIVE = 3,
ERROR = 4, PANIC = 5
}
Functions
void led_set (led_t signal)
void led_init ()
static void led_on ()
static void led_off ()
void led_toggle ()
Enumeration Type Documentation
enum led_t
LED hardware layer
Takes the LED_PORT, LED_DDR and LED_BIT definitions from config.h
Enumerator:
IDLE
OFF
ON
ACTIVE
ERROR
PANIC
Definition at line 32 of file led.h.
             {
    IDLE    = 0,
    OFF = 1,
    ON  = 2,
    ACTIVE  = 3,
    ERROR   = 4,
    PANIC   = 5
} led_t;
Function Documentation
void led_init ()
Definition at line 90 of file ledhw.c.
References has_error, LED_BIT, led_current, LED_DDR, LED_PORT, and led_program.
Referenced by main().
                {
    // set data direction
    LED_DDR  |= _BV(LED_BIT);
    // switch LED off
    LED_PORT &= ~_BV(LED_BIT);
    // switch off led interrupt program
    led_program = 0;
    led_current = 0;
    // save error state over ACTIVE/IDLE calls
    has_error = 0;
}
static void led_off () inline static
Definition at line 49 of file led.h.
References led_set(), and OFF.
{
    led_set(OFF);
}
static void led_on () inline static
Definition at line 45 of file led.h.
References led_set(), and ON.
{
    led_set(ON);
}
void led_set (led_t signal)
Definition at line 118 of file ledhw.c.
References _led_off(), _led_on(), ACTIVE, ERROR, has_error, IDLE, init_prg(), OFF, ON, PANIC, and PANIC_OFFSET.
Referenced by bus_attention(), ISR(), led_off(), led_on(), and set_error_ts().
{
    switch(mode) {
    case IDLE:
        if (has_error) {
            init_prg(0);
        } else {
            _led_off();
        }
        break;
    case OFF:
        has_error = 0;
        _led_off();
        break;
    case ACTIVE:
    case ON:
        _led_on();
        break;
    case PANIC:
        init_prg(PANIC_OFFSET);
        break;
    case ERROR:
        has_error = 1;
    default:
        init_prg(0);
        break;
    }
}
void led_toggle ()
Definition at line 114 of file ledhw.c.
References LED_BIT, and LED_PORT.
                  {
    LED_PORT ^= _BV(LED_BIT);
}