XD2031 firmware: avr/ledhw.c File Reference
ledhw.c File Reference
#include <avr/io.h>
#include <avr/interrupt.h>
#include <inttypes.h>
#include "config.h"
#include "mem.h"
#include "led.h"
Macros
#define PANIC_OFFSET 5
Functions
static void init_prg (uint8_t ptr)
void led_init ()
static void _led_on ()
static void _led_off ()
void led_toggle ()
void led_set (led_t mode)
Variables
volatile uint8_t led_program = 0
volatile uint8_t led_current = 0
volatile uint8_t led_counter = 0
volatile uint8_t led_bit = 0
volatile uint8_t led_pattern = 0
volatile uint8_t led_shift = 0
uint8_t led_code []
static uint8_t has_error = 0
Macro Definition Documentation
#define PANIC_OFFSET 5
Definition at line 59 of file ledhw.c.
Referenced by led_set().
Function Documentation
static void _led_off () inline static
Definition at line 109 of file ledhw.c.
References LED_BIT, LED_PORT, and led_program.
Referenced by led_set().
{
    led_program = 0;
    LED_PORT &= ~_BV(LED_BIT);
}
static void _led_on () inline static
Definition at line 104 of file ledhw.c.
References LED_BIT, LED_PORT, and led_program.
Referenced by led_set().
{
    led_program = 0;
    LED_PORT |= _BV(LED_BIT);
}
static void init_prg (uint8_t ptr) static
Definition at line 73 of file ledhw.c.
References led_bit, led_counter, led_current, led_pattern, led_program, and led_shift.
Referenced by led_set().
{
    cli();
    led_shift = 0;
    led_bit = 0;
    led_pattern = 0;
    led_counter = 0;
    led_current = ptr+1;
    led_program = ptr+1;
    sei();
}
void led_init ()
Definition at line 90 of file ledhw.c.
References has_error, LED_BIT, led_current, LED_DDR, LED_PORT, and led_program.
Referenced by main().
                {
    // set data direction
    LED_DDR  |= _BV(LED_BIT);
    // switch LED off
    LED_PORT &= ~_BV(LED_BIT);
    // switch off led interrupt program
    led_program = 0;
    led_current = 0;
    // save error state over ACTIVE/IDLE calls
    has_error = 0;
}
void led_set (led_t mode)
Definition at line 118 of file ledhw.c.
References _led_off(), _led_on(), ACTIVE, ERROR, has_error, IDLE, init_prg(), OFF, ON, PANIC, and PANIC_OFFSET.
Referenced by bus_attention(), ISR(), led_off(), led_on(), and set_error_ts().
{
    switch(mode) {
    case IDLE:
        if (has_error) {
            init_prg(0);
        } else {
            _led_off();
        }
        break;
    case OFF:
        has_error = 0;
        _led_off();
        break;
    case ACTIVE:
    case ON:
        _led_on();
        break;
    case PANIC:
        init_prg(PANIC_OFFSET);
        break;
    case ERROR:
        has_error = 1;
    default:
        init_prg(0);
        break;
    }
}
void led_toggle ()
Definition at line 114 of file ledhw.c.
References LED_BIT, and LED_PORT.
                  {
    LED_PORT ^= _BV(LED_BIT);
}
Variable Documentation
uint8_t has_error = 0 static
Definition at line 86 of file ledhw.c.
Referenced by led_init(), and led_set().
volatile uint8_t led_bit = 0
Definition at line 51 of file ledhw.c.
Referenced by init_prg().
uint8_t led_code[]
Initial value:
= {
    2, 0, 2, 255, 0,
    1, 0x0f, 0
}
Definition at line 62 of file ledhw.c.
volatile uint8_t led_counter = 0
Definition at line 48 of file ledhw.c.
Referenced by init_prg().
volatile uint8_t led_current = 0
Definition at line 45 of file ledhw.c.
Referenced by init_prg(), and led_init().
volatile uint8_t led_pattern = 0
Definition at line 54 of file ledhw.c.
Referenced by init_prg().
volatile uint8_t led_program = 0
LED hardware layer
Takes the LED_PORT, LED_DDR and LED_BIT definitions from config.h
Definition at line 42 of file ledhw.c.
Referenced by _led_off(), _led_on(), init_prg(), and led_init().
volatile uint8_t led_shift = 0
Definition at line 57 of file ledhw.c.
Referenced by init_prg().