XD2031 firmware: main.c File Reference
main.c File Reference
#include <avr/io.h>
#include <avr/pgmspace.h>
#include <avr/interrupt.h>
#include <inttypes.h>
#include <ctype.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <alloca.h>
#include "config.h"
#include "version.h"
#include "main.h"
#include "packet.h"
#include "serial.h"
#include "uarthw.h"
#include "ieeehw.h"
#include "ieee.h"
#include "term.h"
#include "file.h"
#include "channel.h"
#include "bus.h"
#include "mem.h"
#include "timer.h"
#include "led.h"
Functions
void ListVersion ()
uint16_t BytesFree ()
int main ()
Variables
static endpoint_t term_endpoint
Function Documentation
uint16_t BytesFree ()
Definition at line 69 of file main.c.
Referenced by main().
{
    extern unsigned char __heap_start;
    uint16_t momentan_frei = SP - (uint16_t) &__heap_start;
    return momentan_frei;
}
void ListVersion ()
Definition at line 58 of file main.c.
References HW_NAME, IN_ROM_STR, SW_NAME, term_putcrlf(), term_rom_puts(), and VERSION.
Referenced by main().
{
    term_putcrlf();
    term_rom_puts(IN_ROM_STR("### "HW_NAME"/"SW_NAME" v"VERSION" ###"));
    term_putcrlf();
}
int main ()
Definition at line 82 of file main.c.
References bus_init(), BytesFree(), channel_init(), F_CPU, file_init(), ieee_mainloop_iteration(), ieeehw_init(), ieeehwi_init(), led_init(), ListVersion(), provider_t::prov_assign, endpoint_t::provdata, endpoint_t::provider, provider_init(), provider_set_default(), serial_delay(), serial_init(), serial_sync(), term_init(), term_printf(), term_putcrlf(), term_set_endpoint(), timer_init(), and uarthw_init().
{
    // Initialisierungen
    //
    // first some basic hardware infrastructure
    timer_init();           // Timer Interrupt initialisieren
    led_init();
    provider_init();        // needs to be in the beginning, as other
                    // modules like serial register here
    term_init();            // does not need endpoint/provider yet
                    // but can take up to a buffer of text
    // server communication
    uarthw_init();          // first hardware
    provider_t *serial = serial_init(); // then logic layer
    // now prepare for terminal etc
    // (note: in the future the assign parameter could be used
    // to distinguish different UARTs for example)
    void *epdata = serial->prov_assign(NULL);
    term_endpoint.provider = serial;
    term_endpoint.provdata = epdata;
    // and set as default
    provider_set_default(serial, epdata);
    // debug output via "terminal"
    term_set_endpoint(&term_endpoint);
    // init file handling (active open calls)
    file_init();
    // init main channel handling
    channel_init();
    // bus init
    bus_init();         // first the general bus (with bus counter)
    // IEEE488 bus
    ieeehw_init();          // hardware
    ieeehwi_init(8);        // hardware-independent part; registers as bus
    // enable interrupts
    sei();
    // sync with the server
    serial_sync();
    // show our version...
    ListVersion();
    // ... and some system info
    term_printf((" %u Bytes free"), BytesFree());
    term_printf((", %d kHz"), (int32_t)(F_CPU/1000));
    term_putcrlf();
    term_putcrlf();
    while (1)           // Mainloop-Begin
    {
        // keep data flowing on the serial line
        serial_delay();
        // handle IEEE488 bus
        ieee_mainloop_iteration();
    }
}
Variable Documentation
endpoint_t term_endpoint static
Definition at line 77 of file main.c.