XD2031 firmware: name.h File Reference
name.h File Reference
#include "cmd.h"
Data Structures
struct nameinfo_t
Macros
#define NAMEINFO_UNUSED_DRIVE 0xff
Functions
void parse_filename (cmd_t *in, nameinfo_t *result, uint8_t is_command)
Variables
nameinfo_t nameinfo
Macro Definition Documentation
#define NAMEINFO_UNUSED_DRIVE 0xff
Definition at line 42 of file name.h.
Referenced by command_execute(), and parse_filename().
Function Documentation
void parse_filename (cmd_t * in, nameinfo_t * result, uint8_t is_command)
Definition at line 58 of file name.c.
References nameinfo_t::access, nameinfo_t::cmd, CMD_DIR, CMD_NONE, cmd_t::command_buffer, command_find(), cmd_t::command_length, command_to_name(), debug_printf, debug_putc(), debug_putcrlf(), debug_puts, nameinfo_t::drive, nameinfo_t::name, NAME_ACCESS, NAME_CMDDRIVE, NAME_COMMAND, NAME_DRIVE, NAME_FILE, NAME_NAME, NAME_TYPE, NAMEINFO_UNUSED_DRIVE, nameinfo_t::namelen, and nameinfo_t::type.
Referenced by command_execute(), and file_open().
{
    // runtime vars
    uint8_t *p = in->command_buffer;
    uint8_t len = in->command_length;
    // init output
    result->drive = NAMEINFO_UNUSED_DRIVE;
    result->cmd = CMD_NONE; // no command
    result->type = 0;   // PRG
    result->access = 'R';   // read
    // start either for command or file name
    uint8_t state;
    if (is_command) {
        state = NAME_COMMAND;
        result->name = NULL;
        result->namelen = 0;
    } else {
        state = NAME_FILE;
        result->name = p;   // full name
        result->namelen = len;  // default
    }
    uint8_t drv = 0;
    while (len > 0) {
        switch(state) {
        case NAME_COMMAND:
            // save first char as potential command
            if (result->cmd == CMD_NONE) {
                if (isalpha(*p)) {
                    result->cmd = command_find(p);
                    result->namelen = 0;    // just to be sure, until we parsed it
                }
            }
            // fallthrough
        case NAME_CMDDRIVE:
            // last digit as drive
            if (isdigit(*p)) {
                result->drive = *p - 0x30;
            }
            // command parameters following?
            if (*p == ':') {
                result->name = (p+1);
                result->namelen = len-1;
                state = NAME_NAME;
            }
            break;
        case NAME_FILE:
            if (*p == '$') {
                result->cmd = CMD_DIR;  // directory
                result->namelen = 0;    // just to be sure, until we parsed it
                state = NAME_CMDDRIVE;  // jump into command parser
            }
        case NAME_DRIVE:
            // last digit as potential drive
            if (isdigit(*p)) {
                drv = *p - 0x30;
                //p++;
            }
            if (*p == ':') {
                // found drive separator
                result->drive = drv;
                result->name = (p+1);
                result->namelen = len-1;
                state = NAME_NAME;
                break;
            }
            // fallthrough
        case NAME_NAME:
            if (is_command) {
                // here the "=" case for COPY/RENAME is missing,
                // also the "," for multiple files after the "="
                // - further processing is done in command handling
                break;
            }
            if (*p == ',') {
                // found file type/access separator
                result->namelen = p - result->name;
                state = NAME_TYPE;
                break;
            }
            break;
        case NAME_TYPE:
            if (result->type == 0) {
                result->type = *p;
            }
            if (*p == ',') {
                state = NAME_ACCESS;
            }
            break;
        case NAME_ACCESS:
            if (result->access == 0) {
                result->access = *p;
            }
            break;
        default:
            break;
        }
        len--;
        p++;
    }
//  if (result->cmd == 0 && cmd == '$') {
//      // no command detected, but name starts with "$"
//      // so this is a directory name without file name filter
//      result->drive = drv;
//      result->cmd = cmd;
//      result->namelen = 0;
//  }
    // insert the drive (as endpoint address) as first byte of the file name
        // prepare request data
        if (result->name == in->command_buffer) {
                // we used a default, and need to insert the endpoint in front
                // of the name
                memmove(result->name+1, result->name, result->namelen);
                result->namelen++;
        } else {
                // parser has left some space before the name
                result->namelen++;
                result->name--;
        }
        result->name[0] = result->drive;
#if DEBUG_NAME
    debug_printf("CMD=%s\n", result->cmd == CMD_NONE ? '-' : command_to_name(result->cmd));
    debug_printf("DRIVE=%c\n", result->drive == NAMEINFO_UNUSED_DRIVE ? '-' : result->drive + 0x30);
    debug_puts("NAME="); debug_puts((char*)result->name); debug_putcrlf();
    debug_puts("ACCESS="); debug_putc(result->access); debug_putcrlf();
    debug_puts("TYPE="); debug_putc(result->type); debug_putcrlf();
#endif
}
Variable Documentation
nameinfo_t nameinfo
Definition at line 47 of file name.c.
Referenced by command_execute(), file_open(), and file_submit_call().