XD2031 firmware: packet.h File Reference
packet.h File Reference
#include <inttypes.h>
#include "wireformat.h"
#include "delay.h"
Data Structures
struct packet_t
Macros
#define PACKET_EMPTY 0
#define PACKET_WR 1
#define PACKET_TYPE 2
#define PACKET_LEN 3
#define PACKET_DATA 4
#define PACKET_DONE 5
Typedefs
typedef uint8_t bool
Functions
static int8_t packet_get_chan (packet_t *packet)
static int8_t packet_get_type (packet_t *packet)
static int8_t packet_get_contentlen (packet_t *packet)
static int8_t packet_get_capacity (packet_t *packet)
static uint8_t * packet_get_buffer (packet_t *packet)
static void packet_init (packet_t *packet, uint8_t len, uint8_t *buffer)
static void packet_reset (packet_t *packet, uint8_t channo)
static bool packet_is_done (packet_t *buf)
static bool packet_is_full (packet_t *buf)
static void packet_wait_done (packet_t *buf)
static void packet_set_read (packet_t *packet)
static int8_t packet_set_write (packet_t *packet, int8_t chan, uint8_t type, uint8_t datalen)
static void packet_set_filled (packet_t *packet, int8_t chan, uint8_t type, uint8_t datalen)
static void packet_update_wp (packet_t *packet, int8_t datalen)
static void packet_write_char (packet_t *buf, uint8_t ch)
static uint8_t packet_read_char (packet_t *buf)
static uint8_t packet_peek_data (packet_t *buf)
static uint8_t packet_next (packet_t *buf)
static uint8_t packet_is_last (packet_t *buf)
static uint8_t packet_is_eof (packet_t *buf)
static uint8_t packet_current_is_eof (packet_t *buf)
static bool packet_has_data (packet_t *buf)
Macro Definition Documentation
#define PACKET_DATA 4
Definition at line 65 of file packet.h.
#define PACKET_DONE 5
Definition at line 66 of file packet.h.
#define PACKET_EMPTY 0
Packet handling
Definition at line 61 of file packet.h.
#define PACKET_LEN 3
Definition at line 64 of file packet.h.
#define PACKET_TYPE 2
Definition at line 63 of file packet.h.
#define PACKET_WR 1
Definition at line 62 of file packet.h.
Typedef Documentation
typedef uint8_t bool
Definition at line 68 of file packet.h.
Function Documentation
static uint8_t packet_current_is_eof (packet_t * buf) inline static
Definition at line 200 of file packet.h.
References FS_EOF, packet_t::rp, packet_t::type, and packet_t::wp.
Referenced by channel_current_is_eof().
{
//debug_puts("packet_eof: "); debug_puthex(buf->type); debug_puthex(buf->rp); debug_puthex(buf->wp); debug_putcrlf();
    return (buf->type == ((uint8_t)(FS_EOF & 0xff))) && ((buf->rp + 1) >= buf->wp);
}
static uint8_t* packet_get_buffer (packet_t * packet) inline static
Definition at line 95 of file packet.h.
References packet_t::buffer.
Referenced by directory_converter(), and to_provider().
{
    return packet->buffer;
}
static int8_t packet_get_capacity (packet_t * packet) inline static
Definition at line 91 of file packet.h.
References packet_t::len.
Referenced by directory_converter().
{
    return packet->len;
}
static int8_t packet_get_chan (packet_t * packet) inline static
Definition at line 79 of file packet.h.
References packet_t::chan.
Referenced by read_char_from_packet().
{
    return packet->chan;
}
static int8_t packet_get_contentlen (packet_t * packet) inline static
Definition at line 87 of file packet.h.
References packet_t::wp.
Referenced by channel_close(), channel_put(), read_char_from_packet(), and to_provider().
{
    return packet->wp;
}
static int8_t packet_get_type (packet_t * packet) inline static
Definition at line 83 of file packet.h.
References packet_t::type.
Referenced by read_char_from_packet().
{
    return packet->type;
}
static bool packet_has_data (packet_t * buf) inline static
Definition at line 205 of file packet.h.
References packet_t::rp, and packet_t::wp.
Referenced by channel_preload_int(), channel_refill(), and read_char_from_packet().
{
    return (buf->rp < buf->wp) ? 1 : 0;
}
static void packet_init (packet_t * packet, uint8_t len, uint8_t * buffer) inline static
Definition at line 99 of file packet.h.
References packet_t::buffer, packet_t::chan, packet_t::len, packet_t::rp, and packet_t::wp.
Referenced by channel_close_int(), file_submit_call(), and term_init().
{
    packet->buffer = buffer;
    packet->len = len;
    packet->chan = -3;
    packet->rp = 0;
    packet->wp = 0;
}
static bool packet_is_done (packet_t * buf) inline static
Definition at line 114 of file packet.h.
References packet_t::rp, and packet_t::wp.
Referenced by packet_wait_done().
{
    return buf->wp == buf->rp;
}
static uint8_t packet_is_eof (packet_t * buf) inline static
Definition at line 195 of file packet.h.
References FS_EOF, packet_t::rp, packet_t::type, and packet_t::wp.
Referenced by channel_has_more(), and channel_is_eof().
{
//debug_puts("packet_eof: "); debug_puthex(buf->type); debug_puthex(buf->rp); debug_puthex(buf->wp); debug_putcrlf();
    return (buf->type == ((uint8_t)(FS_EOF & 0xff))) && (buf->rp >= buf->wp);
}
static bool packet_is_full (packet_t * buf) inline static
Definition at line 118 of file packet.h.
References packet_t::len, and packet_t::wp.
Referenced by channel_put().
{
    return buf->wp == buf->len;
}
static uint8_t packet_is_last (packet_t * buf) inline static
Definition at line 190 of file packet.h.
References FS_EOF, and packet_t::type.
Referenced by channel_next(), channel_preload_int(), and channel_refill().
{
//debug_puts("packet_eof: "); debug_puthex(buf->type); debug_puthex(buf->rp); debug_puthex(buf->wp); debug_putcrlf();
    return (buf->type == ((uint8_t)(FS_EOF & 0xff)));
}
static uint8_t packet_next (packet_t * buf) inline static
Definition at line 185 of file packet.h.
References packet_t::rp, and packet_t::wp.
Referenced by channel_next().
{
    buf->rp++;
    return (buf->rp < buf->wp) ? 1 : 0;
}
static uint8_t packet_peek_data (packet_t * buf) inline static
Definition at line 171 of file packet.h.
References packet_t::buffer, and packet_t::rp.
Referenced by channel_current_byte().
{
    return buf->buffer[buf->rp];
}
static uint8_t packet_read_char (packet_t * buf) inline static
Definition at line 165 of file packet.h.
References packet_t::buffer, and packet_t::rp.
Referenced by read_char_from_packet().
{
    return buf->buffer[buf->rp++];
}
static void packet_reset (packet_t * packet, uint8_t channo) inline static
Definition at line 108 of file packet.h.
References packet_t::chan, packet_t::rp, and packet_t::wp.
Referenced by channel_open(), and channel_put().
{
    packet->rp = 0;
    packet->wp = 0;
    packet->chan = channo;
}
static void packet_set_filled (packet_t * packet, int8_t chan, uint8_t type, uint8_t datalen) inline static
tell the packet that it has been filled "out of band", e.g. by directly writing to the buffer the packet points to.
Definition at line 146 of file packet.h.
References packet_t::chan, packet_set_read(), packet_t::type, and packet_t::wp.
Referenced by channel_close(), channel_pull(), channel_put(), file_submit_call(), and send().
{
    packet->type = type;
    packet->chan = chan;
    packet->wp = datalen;
    packet_set_read(packet);
}
static void packet_set_read (packet_t * packet) inline static
Definition at line 128 of file packet.h.
References packet_t::rp.
Referenced by packet_set_filled().
{
    packet->rp = 0;
}
static int8_t packet_set_write (packet_t * packet, int8_t chan, uint8_t type, uint8_t datalen) inline static
Definition at line 132 of file packet.h.
References packet_t::chan, packet_t::len, packet_t::type, and packet_t::wp.
Referenced by push_data_to_packet().
{
    if (datalen > packet->len) {
        return -1;
    }
    packet->type = type;
    packet->chan = chan;
    packet->wp = 0;
    return 0;
}
static void packet_update_wp (packet_t * packet, int8_t datalen) inline static
Definition at line 153 of file packet.h.
References packet_t::wp.
Referenced by directory_converter().
{
    packet->wp = datalen;
}
static void packet_wait_done (packet_t * buf) inline static
Definition at line 122 of file packet.h.
References delayms(), and packet_is_done().
Referenced by term_putc(), term_puts(), and term_rom_puts().
{
    while( ! packet_is_done(buf) ) {
        delayms(1);
    }
}
static void packet_write_char (packet_t * buf, uint8_t ch) inline static
Definition at line 161 of file packet.h.
References packet_t::buffer, and packet_t::wp.
Referenced by channel_put(), and push_data_to_packet().
{
    buf->buffer[buf->wp++] = ch;
}