XD2031 firmware: petSD/ieeehw.c File Reference
ieeehw.c File Reference
#include "ieeehw.h"
Functions
static void ieee_interrupts_init (void)
static void set_atn_irq (uint8_t x)
void ieeehw_setup ()
void ieeehw_init ()
Variables
uint8_t is_atna = 0
uint8_t is_ndacout = 0
uint8_t is_nrfdout = 0
Function Documentation
static void ieee_interrupts_init (void) static
Definition at line 43 of file ieeehw.c.
Referenced by ieeehw_init().
{
  DDRD &= ~_BV(PD2);        // define ATN as input
  PORTD |= _BV(PD2);        // enable pull-up
  EIMSK &= (uint8_t) ~_BV(INT0);    // disable interrupt
  EICRA &= (uint8_t) ~_BV(ISC00);   // configure interrupt on falling
  EICRA |= _BV(ISC01);              // edge of ATN
  EIMSK |= _BV(INT0);       // enable interrupt
  //debug_putps("Done init ieee ints"); debug_putcrlf();
}
void ieeehw_init (void)
Definition at line 79 of file ieeehw.c.
Referenced by main().
                   {
    IEEE_DDR_TE |= _BV(IEEE_PIN_TE);                // Define TE as output
    IEEE_PORT_TE &= (uint8_t) ~ _BV(IEEE_PIN_TE);   // TE=0
    IEEE_DDR_DC |= _BV(IEEE_PIN_DC);                // Define DC as output
    IEEE_PORT_DC |= _BV(IEEE_PIN_DC);               // DC=1 (device)
    // disable ATN interrupt
    set_atn_irq(0);
    // clear IEEE lines
    ieeehw_setup();
    // start ATN interrupt handling
    ieee_interrupts_init();
}
void ieeehw_setup (void)
Definition at line 69 of file ieeehw.c.
Referenced by ieee_mainloop_iteration(), ieeehw_init(), and ieeehwi_init().
                    {
    // clear IEEE lines
    atnahi();
    clrd();
    davhi();
    nrfdhi();
    ndachi();
    eoihi();
}
static void set_atn_irq (uint8_t x) static
Definition at line 55 of file ieeehw.c.
References debug_putcrlf(), debug_puthex(), and IEEE_ATN_INT.
Referenced by ieeehw_init().
{
#if DEBUG
  debug_putps("ATN_IRQ:"); debug_puthex(x); debug_putcrlf();
#endif
  if (x)
    EIMSK |= _BV(IEEE_ATN_INT);
  else
    EIMSK &= (uint8_t) ~_BV(IEEE_ATN_INT);
}
Variable Documentation
uint8_t is_atna = 0
Definition at line 35 of file ieeehw.c.
Referenced by atnahi(), atnalo(), ndachi(), and nrfdhi().
uint8_t is_ndacout = 0
Definition at line 36 of file ieeehw.c.
Referenced by atnalo(), ndachi(), and ndaclo().
uint8_t is_nrfdout = 0
Definition at line 37 of file ieeehw.c.
Referenced by atnalo(), nrfdhi(), and nrfdlo().