XD2031 firmware: petSD/ieeehw.h File Reference
ieeehw.h File Reference
#include <stdint.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include "device.h"
Macros
#define E_OK 0
#define E_ATN 1
#define E_EOI 2
#define E_TIME 4
#define E_BRK 5
#define E_NODEV 6
#define setidle() setrx()
Functions
static uint8_t atnislo (void)
static uint8_t atnishi (void)
static void ndaclo (void)
static void nrfdlo (void)
static void ndachi (void)
static void nrfdhi (void)
static uint8_t ndacislo (void)
static uint8_t ndacishi (void)
static uint8_t nrfdislo (void)
static uint8_t nrfdishi (void)
static void davlo (void)
static void davhi (void)
static uint8_t davislo (void)
static uint8_t davishi (void)
static void eoilo (void)
static void eoihi (void)
static uint8_t eoiislo (void)
static uint8_t eoiishi (void)
static void telo (void)
static void tehi (void)
static void atnahi (void)
static void atnalo (void)
static void clrd (void)
static void wrd (uint8_t data)
static uint8_t rdd (void)
void ieeehw_init (void)
void ieeehw_setup (void)
static void settx (void)
static void setrx (void)
Variables
uint8_t is_atna
uint8_t is_nrfdout
uint8_t is_ndacout
Macro Definition Documentation
#define E_ATN 1
Definition at line 40 of file ieeehw.h.
Referenced by liecin(), and listenloop().
#define E_BRK 5
Definition at line 43 of file ieeehw.h.
#define E_EOI 2
Definition at line 41 of file ieeehw.h.
Referenced by liecin(), listenloop(), and talkloop().
#define E_NODEV 6
Definition at line 44 of file ieeehw.h.
Referenced by talkloop().
#define E_OK 0
Definition at line 39 of file ieeehw.h.
#define E_TIME 4
Definition at line 42 of file ieeehw.h.
#define setidle (void) setrx()
Definition at line 240 of file ieeehw.h.
Referenced by listenloop(), and talkloop().
Function Documentation
static void atnahi (void) inline static
Definition at line 170 of file ieeehw.h.
References is_atna.
Referenced by ieee_mainloop_iteration(), and ieeehw_setup().
{
  is_atna = 0;
}
static void atnalo (void) inline static
Definition at line 175 of file ieeehw.h.
References is_atna, is_ndacout, is_nrfdout, ndaclo(), and nrfdlo().
Referenced by ieee_mainloop_iteration().
{
  if (!is_nrfdout) {
    nrfdlo();
  }
  if (!is_ndacout) {
    ndaclo();
  }
  is_atna = 1;
}
static uint8_t atnishi (void) inline static
Definition at line 56 of file ieeehw.h.
References IEEE_INPUT_ATN, and IEEE_PIN_ATN.
Referenced by ieee_mainloop_iteration(), ndachi(), nrfdhi(), and settx().
{
  return (IEEE_INPUT_ATN & _BV(IEEE_PIN_ATN));
}
static uint8_t atnislo (void) inline static
Definition at line 52 of file ieeehw.h.
References IEEE_INPUT_ATN, and IEEE_PIN_ATN.
Referenced by liecin(), and talkloop().
{
  return !(IEEE_INPUT_ATN & _BV(IEEE_PIN_ATN));
}
static void clrd (void) inline static
Definition at line 187 of file ieeehw.h.
References IEEE_D_PORT.
Referenced by ieeehw_setup().
{
  IEEE_D_PORT = 0xff;
}
static void davhi (void) inline static
Definition at line 122 of file ieeehw.h.
References IEEE_PIN_DAV, and IEEE_PORT_DAV.
Referenced by ieeehw_setup(), settx(), and talkloop().
{
  IEEE_PORT_DAV |= _BV(IEEE_PIN_DAV);               // DAV high
}
static uint8_t davishi (void) inline static
Definition at line 130 of file ieeehw.h.
References IEEE_INPUT_DAV, and IEEE_PIN_DAV.
Referenced by ieee_mainloop_iteration(), and liecin().
{
  return (IEEE_INPUT_DAV & _BV(IEEE_PIN_DAV));
}
static uint8_t davislo (void) inline static
Definition at line 126 of file ieeehw.h.
References IEEE_INPUT_DAV, and IEEE_PIN_DAV.
Referenced by ieee_mainloop_iteration(), and liecin().
{
  return !(IEEE_INPUT_DAV & _BV(IEEE_PIN_DAV));
}
static void davlo (void) inline static
Definition at line 118 of file ieeehw.h.
References IEEE_PIN_DAV, and IEEE_PORT_DAV.
Referenced by talkloop().
{
  IEEE_PORT_DAV &= (uint8_t)~_BV(IEEE_PIN_DAV);     // DAV low
}
static void eoihi (void) inline static
Definition at line 143 of file ieeehw.h.
References IEEE_DDR_EOI, IEEE_PIN_EOI, and IEEE_PORT_EOI.
Referenced by ieeehw_setup(), setrx(), settx(), and talkloop().
{
  IEEE_DDR_EOI &= (uint8_t)~_BV(IEEE_PIN_EOI);      // EOI as input
  IEEE_PORT_EOI |= (uint8_t)_BV(IEEE_PIN_EOI);      // Enable pull-up
}
static uint8_t eoiishi (void) inline static
Definition at line 152 of file ieeehw.h.
References IEEE_INPUT_EOI, and IEEE_PIN_EOI.
Referenced by liecin().
{
  return (IEEE_INPUT_EOI & _BV(IEEE_PIN_EOI));
}
static uint8_t eoiislo (void) inline static
Definition at line 148 of file ieeehw.h.
References IEEE_INPUT_EOI, and IEEE_PIN_EOI.
{
  return !(IEEE_INPUT_EOI & _BV(IEEE_PIN_EOI));
}
static void eoilo (void) inline static
Definition at line 138 of file ieeehw.h.
References IEEE_DDR_EOI, IEEE_PIN_EOI, and IEEE_PORT_EOI.
Referenced by talkloop().
{
  IEEE_PORT_EOI &= (uint8_t)~_BV(IEEE_PIN_EOI);     // EOI low
  IEEE_DDR_EOI |= (uint8_t) _BV(IEEE_PIN_EOI);      // EOI as output
}
void ieeehw_init (void)
Definition at line 79 of file ieeehw.c.
                   {
    IEEE_DDR_TE |= _BV(IEEE_PIN_TE);                // Define TE as output
    IEEE_PORT_TE &= (uint8_t) ~ _BV(IEEE_PIN_TE);   // TE=0
    IEEE_DDR_DC |= _BV(IEEE_PIN_DC);                // Define DC as output
    IEEE_PORT_DC |= _BV(IEEE_PIN_DC);               // DC=1 (device)
    // disable ATN interrupt
    set_atn_irq(0);
    // clear IEEE lines
    ieeehw_setup();
    // start ATN interrupt handling
    ieee_interrupts_init();
}
void ieeehw_setup (void)
Definition at line 69 of file ieeehw.c.
                    {
    // clear IEEE lines
    atnahi();
    clrd();
    davhi();
    nrfdhi();
    ndachi();
    eoihi();
}
static void ndachi (void) inline static
Definition at line 73 of file ieeehw.h.
References atnishi(), IEEE_PIN_NDAC, IEEE_PORT_NDAC, is_atna, and is_ndacout.
Referenced by ieee_mainloop_iteration(), ieeehw_setup(), liecin(), and setrx().
{
  // disable interrupt to avoid race condition
  // of ATN irq between the atnishi() check and
  // setting NDAC lo
  cli();
  if (atnishi() || is_atna) {
    IEEE_PORT_NDAC |= _BV(IEEE_PIN_NDAC);           // NDAC high
  }
  // allow interrupt again
  sei();
  is_ndacout = 1;
}
static uint8_t ndacishi (void) inline static
Definition at line 103 of file ieeehw.h.
References IEEE_INPUT_NDAC, and IEEE_PIN_NDAC.
Referenced by settx(), and talkloop().
{
  return (IEEE_INPUT_NDAC & _BV(IEEE_PIN_NDAC));
}
static uint8_t ndacislo (void) inline static
Definition at line 99 of file ieeehw.h.
References IEEE_INPUT_NDAC, and IEEE_PIN_NDAC.
Referenced by talkloop().
{
  return !(IEEE_INPUT_NDAC & _BV(IEEE_PIN_NDAC));
}
static void ndaclo (void) inline static
Definition at line 63 of file ieeehw.h.
References IEEE_PIN_NDAC, IEEE_PORT_NDAC, and is_ndacout.
Referenced by atnalo(), ieee_mainloop_iteration(), and liecin().
{
 IEEE_PORT_NDAC &= (uint8_t)~_BV(IEEE_PIN_NDAC);    // NDAC low
 is_ndacout = 0;
}
static void nrfdhi (void) inline static
Definition at line 86 of file ieeehw.h.
References atnishi(), IEEE_PIN_NRFD, IEEE_PORT_NRFD, is_atna, and is_nrfdout.
Referenced by ieee_mainloop_iteration(), ieeehw_setup(), liecin(), and setrx().
{
  // disable interrupt to avoid race condition
  // of ATN irq between the atnishi() check and
  // setting NDAC lo
  cli();
  if (atnishi() || is_atna) {
    IEEE_PORT_NRFD |= _BV(IEEE_PIN_NRFD);           // NRFD high
  }
  // allow interrupt again
  sei();
  is_nrfdout = 1;
}
static uint8_t nrfdishi (void) inline static
Definition at line 112 of file ieeehw.h.
References IEEE_INPUT_NRFD, and IEEE_PIN_NRFD.
Referenced by talkloop().
{
  return (IEEE_INPUT_NRFD & _BV(IEEE_PIN_NRFD));
}
static uint8_t nrfdislo (void) inline static
Definition at line 108 of file ieeehw.h.
References IEEE_INPUT_NRFD, and IEEE_PIN_NRFD.
Referenced by talkloop().
{
  return !(IEEE_INPUT_NRFD & _BV(IEEE_PIN_NRFD));
}
static void nrfdlo (void) inline static
Definition at line 68 of file ieeehw.h.
References IEEE_PIN_NRFD, IEEE_PORT_NRFD, and is_nrfdout.
Referenced by atnalo(), ieee_mainloop_iteration(), and liecin().
{
  IEEE_PORT_NRFD &= (uint8_t)~_BV(IEEE_PIN_NRFD);   // NRFD low
  is_nrfdout = 0;
}
static uint8_t rdd (void) inline static
Definition at line 195 of file ieeehw.h.
References IEEE_D_PIN.
Referenced by ieee_mainloop_iteration(), and liecin().
{
  return (uint8_t) ~ IEEE_D_PIN;
}
static void setrx (void) inline static
Definition at line 225 of file ieeehw.h.
References eoihi(), IEEE_D_DDR, IEEE_D_PORT, IEEE_DDR_DAV, IEEE_DDR_NDAC, IEEE_DDR_NRFD, IEEE_PIN_DAV, IEEE_PIN_NDAC, IEEE_PIN_NRFD, IEEE_PORT_DAV, ndachi(), nrfdhi(), and telo().
Referenced by ieee_mainloop_iteration(), and talkloop().
{
  IEEE_DDR_DAV &= (uint8_t)~_BV(IEEE_PIN_DAV);      // DAV as input
  IEEE_D_DDR = 0;                                   // Data as input
  IEEE_PORT_DAV |= _BV(IEEE_PIN_DAV);               // Enable DAV pull-up
  IEEE_D_PORT = 0xff;                               // Enable data pull-ups
  eoihi();                                          // Release EOI
  nrfdhi();                                         // Release NRFD
  ndachi();                                         // Release NDAC
  telo();                                           // Bus driver => LISTEN
  IEEE_DDR_NDAC |= _BV(IEEE_PIN_NDAC);              // NDAC as output
  IEEE_DDR_NRFD |= (uint8_t) _BV(IEEE_PIN_NRFD);    // NRFD as output
}
static void settx (void) inline static
Definition at line 207 of file ieeehw.h.
References atnishi(), davhi(), eoihi(), IEEE_D_DDR, IEEE_D_PORT, IEEE_DDR_DAV, IEEE_DDR_NDAC, IEEE_DDR_NRFD, IEEE_PIN_DAV, IEEE_PIN_NDAC, IEEE_PIN_NRFD, IEEE_PORT_NDAC, IEEE_PORT_NRFD, ndacishi(), and tehi().
Referenced by talkloop().
{
  IEEE_DDR_NDAC &= (uint8_t)~_BV(IEEE_PIN_NDAC);    // NDAC as input
  IEEE_DDR_NRFD &= (uint8_t)~_BV(IEEE_PIN_NRFD);    // NRFD as input
  IEEE_PORT_NDAC |= _BV(IEEE_PIN_NDAC);             // Enable NDAC pull-up
  IEEE_PORT_NRFD |= _BV(IEEE_PIN_NRFD);             // Enable NRFD pull-up
  davhi();                                          // Release DAV
  eoihi();                                          // EOI high
  IEEE_D_PORT = 0xff;                               // Release data lines
  tehi();                                           // Bus driver => TALK
  IEEE_DDR_DAV |= _BV(IEEE_PIN_DAV);                // DAV as output (high)
  IEEE_D_DDR = 0xff;                                // Data as output (high)
  /* We're faster than the PET, so we have to wait for NDAC low first
   * to avoid running in DEVICE NOT PRESENT error */
  while(ndacishi() && atnishi());                   // Wait for NDAC low
}
static void tehi (void) inline static
Definition at line 162 of file ieeehw.h.
References IEEE_PIN_TE, and IEEE_PORT_TE.
Referenced by settx().
{
  IEEE_PORT_TE |= _BV(IEEE_PIN_TE);                 // TE high (talk)
}
static void telo (void) inline static
Definition at line 158 of file ieeehw.h.
References IEEE_PIN_TE, and IEEE_PORT_TE.
Referenced by setrx().
{
  IEEE_PORT_TE &= (uint8_t) ~ _BV(IEEE_PIN_TE);     // TE low (listen)
}
static void wrd (uint8_t data) inline static
Definition at line 191 of file ieeehw.h.
References IEEE_D_PORT.
Referenced by talkloop().
{
  IEEE_D_PORT = (uint8_t) ~ data;
}
Variable Documentation
uint8_t is_atna
Definition at line 35 of file ieeehw.c.
uint8_t is_ndacout
Definition at line 36 of file ieeehw.c.
uint8_t is_nrfdout
Definition at line 37 of file ieeehw.c.