XD2031 firmware: provider.h File Reference
provider.h File Reference
#include <inttypes.h>
#include "packet.h"
#include "errormsg.h"
Data Structures
struct provider_t
struct endpoint_t
Functions
int8_t provider_assign (uint8_t drive, const char *name)
endpoint_t * provider_lookup (uint8_t drive)
uint8_t provider_register (const char *name, provider_t *provider)
void provider_set_default (provider_t *prov, void *epdata)
void provider_init (void)
Function Documentation
int8_t provider_assign (uint8_t drive, const char * name)
The assign process assigns the drive to a provider. I.e. the drive is so far unused (or will be overwritten), and the code has to determine just from the name, which provider to use.
The name starts with an alphanumeric string, followed by a colon. After that, it depends on the provider. If that string is a digit, it is the notation relative to an existing drive's provider. Relative here means that for example a subdirectory can by used. If the string is not a digit, it will be looked up in the list of registered providers. If found, the whole name will be used to retrieve a new endpoint provider. Note that the whole name is used to allow one provider handle/use multiple endpoints e.g. in terms of subdirectory.
If no provider is found, this code returns an error, and the calling code forwards the request to the default provider that is always returned when no assignment can be found.
Note that if an assigned drive is used to assign a new name, the assignment of that drive is removed. This enables the use of the default provider when the assign returns after error, to forward the assign command. Also this enables the use of a server-based provider that is not hidden by an old definition on this device.
Definition at line 74 of file provider.c.
References debug_printf, debug_puts, drive, drives, MAX_DRIVES, MAX_PROV, provider_t::prov_assign, endpoint_t::provider, provider_lookup(), and provs.
Referenced by command_execute().
{
    int8_t rv = -1;
#ifdef DEBUG_PROVIDER
    debug_printf("ASSIGN: drive %d to '%s'\n", drive, name);
#endif
    // check drive
    if (drive > 10) {
        return -1;
    }
    // first find the colon
    uint8_t p = 0;
    while (name[p] != 0 && name[p] != ':') {
        p++;
    }
    provider_t *newprov = NULL;
    void *provdata = NULL;
    if ((isdigit(name[0])) && (p == 1)) {
        // we have a drive digit
        uint8_t drv = name[0] & 0x0f;
        endpoint_t *ep = provider_lookup(drv);
        if (ep == NULL) {
            debug_printf("Drive %d not used, cannot do relative assign!\n", drv);
            return -1;
        }
        if (ep == &default_provider) {
            debug_puts("Default is not registered, forwarding to server\n");
            return -1;
        }
        newprov = ep->provider;
        // currently a relative assignment is not supported
        provdata = newprov->prov_assign(name);
    }
    if (newprov == NULL) {
        // now check each provider in turn, if the name fits
        for (int8_t i = MAX_PROV-1; i >= 0; i--) {
        uint8_t j;
        if (provs[i].name != NULL) {
            //debug_printf("Compare with %s\n",provs[i].name);
            for (j = 0; j < p; j++) {
                if (provs[i].name[j] != name[j]) {
                    // name does not match
                    //debug_printf("name does not match at i=%d, j=%d (%02x vs. %02x\n",
                    //      i, j, provs[i].name[j], name[j]);
                    break;
                }
            }
            //debug_printf("j=%d, p=%d, %02x\n", j, p, provs[i].name[p]);
            if ((j == p) && (provs[i].name[p] == 0)) {
                // found it
                //debug_printf("Found new provider: %p in slot %d\n", p, i);
                newprov = provs[i].provider;
                // new get the runtime data
                provdata = newprov->prov_assign(name);
                break;
            }
        }
        }
    }
    // when we are going to return, remove
    // the old assign mapping
    for (int8_t i = MAX_DRIVES-1; i >= 0; i--) {
        if (drives[i].drive == drive) {
            drives[i].drive = -1;
            drives[i].endpoint.provider = NULL;
            break;
        }
    }
    if (newprov != NULL) {
        // got one, so register it
        for (int8_t i = MAX_DRIVES-1; i >= 0; i--) {
            if (drives[i].drive == -1) {
                drives[i].drive = drive;
                drives[i].endpoint.provider = newprov;
                drives[i].endpoint.provdata = provdata;
#ifdef DEBUG_PROVIDER
                debug_printf("Register prov %p for drive %d with data %p in slot %d\n",
                    newprov, drive, provdata, i);
#endif
                rv = 0;
                break;
            }
        }
    }
    return rv;
}
void provider_init (void)
Definition at line 211 of file provider.c.
References drives, MAX_DRIVES, MAX_PROV, and provs.
Referenced by main().
{
    for (int8_t i = MAX_PROV-1; i >= 0; i--) {
        provs[i].provider = NULL;
        provs[i].name = NULL;
    }
    for (int8_t i = MAX_DRIVES-1; i >= 0; i--) {
        drives[i].endpoint.provider = NULL;
        drives[i].drive = -1;
    }
}
endpoint_t* provider_lookup (uint8_t drive)
Definition at line 170 of file provider.c.
References debug_printf, debug_puts, default_provider, drives, endpoint, MAX_DRIVES, and endpoint_t::provider.
Referenced by file_submit_call(), and provider_assign().
{
#ifdef DEBUG_PROVIDER
    debug_printf("provider_lookup for drive %d\n", drive);
#endif
    for (int8_t i = MAX_DRIVES-1; i >= 0; i--) {
        if ((drives[i].drive == drive) && (drives[i].endpoint.provider != NULL)) {
#ifdef DEBUG_PROVIDER
            debug_printf("found %p in slot %d (default=%p)\n",
                drives[i].endpoint.provider, i, default_provider.provider);
#endif
            return &(drives[i].endpoint);
        }
    }
#ifdef DEBUG_PROVIDER
    debug_puts("not found, returning default\n");
#endif
    return &default_provider;
}
uint8_t provider_register (const char * name, provider_t * provider)
Definition at line 190 of file provider.c.
References debug_printf, MAX_PROV, name, provider, and provs.
{
#ifdef DEBUG_PROVIDER
    debug_printf("Register provider %p for '%s'\n", provider, name);
#endif
    for (int8_t i = MAX_PROV-1; i >= 0; i--) {
        if (provs[i].name == NULL) {
            provs[i].name = name;
            provs[i].provider = provider;
            break;
        }
    }
    return 0;
}
void provider_set_default (provider_t * prov, void * epdata)
Definition at line 206 of file provider.c.
References endpoint_t::provdata, and endpoint_t::provider.
Referenced by main().
{
    default_provider.provider = prov;
    default_provider.provdata = epdata;
}