XD2031 firmware: serial.c File Reference
serial.c File Reference
#include <stdio.h>
#include <string.h>
#include "version.h"
#include "packet.h"
#include "provider.h"
#include "wireformat.h"
#include "serial.h"
#include "uarthw.h"
#include "petscii.h"
#include "debug.h"
#include "led.h"
Macros
#define NUMBER_OF_SLOTS 4
#define TX_TYPE 0
#define TX_LEN 1
#define TX_CHANNEL 2
#define TX_DATA 3
#define TX_IDLE 4
#define RX_IDLE 0
#define RX_LEN 1
#define RX_CHANNELNO 2
#define RX_DATA 3
#define RX_IGNORE 4
Functions
void serial_submit (void *epdata, packet_t *buf)
void serial_submit_call (void *epdata, int8_t channelno, packet_t *txbuf, packet_t *rxbuf, void(*callback)(int8_t channelno, int8_t errnum))
static int8_t directory_converter (packet_t *p)
static int8_t to_provider (packet_t *p)
static void * prov_assign (const char *name)
static void prov_free (void *epdata)
static uint8_t * append (uint8_t *outp, const char *to_append)
static int16_t read_char_from_packet (packet_t *buf)
static void advance_slots ()
static void send (void)
static void push_data_to_packet (int8_t rxdata)
void serial_delay ()
void serial_flush ()
provider_t * serial_init ()
void serial_sync ()
Variables
provider_t serial_provider
static packet_t * slots [NUMBER_OF_SLOTS]
static uint8_t slots_used = 0
static int8_t txstate
struct {
int8_t channelno
packet_t * rxpacket
void(* callback)(int8_t channelno, int8_t errnum)
} rx_channels [NUMBER_OF_SLOTS]
static int8_t rxstate
static int8_t current_channelno
static int8_t current_channelpos
static packet_t * current_rxpacket
static int8_t current_data_left
static int8_t current_is_eoi
static uint8_t out [64]
Macro Definition Documentation
#define NUMBER_OF_SLOTS 4
Definition at line 99 of file serial.c.
Referenced by push_data_to_packet(), serial_init(), serial_submit(), and serial_submit_call().
#define RX_CHANNELNO 2
Definition at line 124 of file serial.c.
Referenced by push_data_to_packet().
#define RX_DATA 3
Definition at line 125 of file serial.c.
Referenced by push_data_to_packet().
#define RX_IDLE 0
Definition at line 122 of file serial.c.
Referenced by push_data_to_packet(), and serial_init().
#define RX_IGNORE 4
Definition at line 126 of file serial.c.
Referenced by push_data_to_packet().
#define RX_LEN 1
Definition at line 123 of file serial.c.
Referenced by push_data_to_packet().
#define TX_CHANNEL 2
Definition at line 110 of file serial.c.
Referenced by read_char_from_packet().
#define TX_DATA 3
Definition at line 111 of file serial.c.
Referenced by read_char_from_packet().
#define TX_IDLE 4
Definition at line 112 of file serial.c.
Referenced by read_char_from_packet(), and serial_init().
#define TX_LEN 1
Definition at line 109 of file serial.c.
Referenced by read_char_from_packet().
#define TX_TYPE 0
Definition at line 108 of file serial.c.
Referenced by advance_slots(), read_char_from_packet(), and serial_submit().
Function Documentation
static void advance_slots () static
Definition at line 346 of file serial.c.
References TX_TYPE.
Referenced by send().
{
    uint8_t i = 0;
    slots_used--;
    while (i < slots_used) {
        slots[i] = slots[i+1];
        i++;
    }
    txstate = TX_TYPE;
}
static uint8_t* append (uint8_t * outp, const char * to_append) static
Definition at line 143 of file serial.c.
References ascii_to_petscii().
Referenced by directory_converter().
{
    while(*to_append != 0) {
        *outp = ascii_to_petscii(*to_append);
        outp++;
        to_append++;
    }
    *outp = 0;
    outp++;
    return outp;
}
static int8_t directory_converter (packet_t * p) static
Definition at line 166 of file serial.c.
References append(), ascii_to_petscii(), debug_putc(), debug_putcrlf(), debug_puthex(), debug_puts, FS_DIR_LEN, FS_DIR_MOD_DIR, FS_DIR_MOD_FIL, FS_DIR_MOD_FRE, FS_DIR_MOD_NAM, FS_DIR_MODE, FS_DIR_NAME, out, packet_get_buffer(), packet_get_capacity(), packet_update_wp(), and SW_NAME_LOWER.
{
    uint8_t *inp = NULL;
    uint8_t *outp = &(out[0]);
    if (p == NULL) {
        debug_puts("P IS NULL!");
        return -1;
    }
    inp = packet_get_buffer(p);
    uint8_t type = inp[FS_DIR_MODE];
    //packet_update_wp(p, 2);
    if (type == FS_DIR_MOD_NAM) {
        *outp = 1; outp++;  // load address low
        *outp = 4; outp++;  // load address high
    }
    *outp = 1; outp++;      // link address low; will be overwritten on LOAD
    *outp = 1; outp++;      // link address high
    uint16_t lineno = 0;
    // line number, derived from file length
    if (inp[FS_DIR_LEN+3] != 0
        || inp[FS_DIR_LEN+2] > 0xf9
        || (inp[FS_DIR_LEN+2] == 0xf9 && inp[FS_DIR_LEN+1] == 0xff && inp[FS_DIR_LEN] != 0)) {
        // more than limit of 63999 blocks
        lineno = 63999;
    } else {
        lineno = inp[FS_DIR_LEN+1] | (inp[FS_DIR_LEN+2] << 8);
        if (inp[FS_DIR_LEN] != 0) {
            lineno++;
        }
    }
    *outp = lineno & 255; outp++;
    *outp = (lineno>>8) & 255; outp++;
    //snprintf(outp, 5, "%hd", (unsigned short)lineno);
    //outp++;
    if (lineno < 10) { *outp = ' '; outp++; }
    if (type == FS_DIR_MOD_NAM) {
        *outp = 0x12;   // reverse for disk name
        outp++;
    } else {
        if (type != FS_DIR_MOD_FRE) {
            if (lineno < 100) { *outp = ' '; outp++; }
            if (lineno < 1000) { *outp = ' '; outp++; }
            if (lineno < 10000) { *outp = ' '; outp++; }
        }
    }
    if (type != FS_DIR_MOD_FRE) {
        *outp = '"'; outp++;
        uint8_t i = FS_DIR_NAME;
        // note the check i<16 - this is buffer overflow protection
        // file names longer than 16 chars are not displayed
        while ((inp[i] != 0) && (i < (FS_DIR_NAME + 16))) {
            *outp = ascii_to_petscii(inp[i]);
            outp++;
            i++;
        }
        // note: not counted in i
        *outp = '"'; outp++;
        // fill up with spaces, at least one space behind filename
        while (i < FS_DIR_NAME + 16 + 1) {
            *outp = ' '; outp++;
            i++;
        }
    }
    // add file type
    if (type == FS_DIR_MOD_NAM) {
        // file name entry
        outp = append(outp, SW_NAME_LOWER);
        //strcpy(outp, SW_NAME_LOWER);
        //outp += strlen(SW_NAME_LOWER)+1;  // includes ending 0-byte
    } else
    if (type == FS_DIR_MOD_DIR) {
        outp = append(outp, "dir");
        //strcpy(outp, "dir");
        //outp += 4;    // includes ending 0-byte
    } else
    if (type == FS_DIR_MOD_FIL) {
        outp = append(outp, "prg");
        //strcpy(outp, "prg");
        //outp += 4;    // includes ending 0-byte
    } else
    if (type == FS_DIR_MOD_FRE) {
        outp = append(outp, "blocks free");
        //strcpy(outp, "bytes free");
        //outp += 11;   // includes ending 0-byte
        *outp = 0; outp++;  // BASIC end marker (zero link address)
        *outp = 0; outp++;  // BASIC end marker (zero link address)
    }
    uint8_t len = outp - out;
    if (len > packet_get_capacity(p)) {
        debug_puts("CONVERSION NOT POSSIBLE!"); debug_puthex(len); debug_putcrlf();
        return -1;  // conversion not possible
    }
#if DEBUG_SERIAL
    debug_puts("CONVERTED TO: LEN="); debug_puthex(len);
    for (uint8_t j = 0; j < len; j++) {
        debug_putc(' '); debug_puthex(out[j]);
    }
    debug_putcrlf();
#endif
    // this should probably be combined
    memcpy(packet_get_buffer(p), &out, len);
    packet_update_wp(p, len);
    return 0;
}
static void* prov_assign (const char * name) static
Definition at line 81 of file serial.c.
{
    return NULL;
}
static void prov_free (void * epdata) static
Definition at line 86 of file serial.c.
{
    return;
}
static void push_data_to_packet (int8_t rxdata) static
interrupt for received data
Definition at line 377 of file serial.c.
References current_channelpos, FS_EOF, FS_REPLY, FS_SYNC, FS_WRITE, NUMBER_OF_SLOTS, packet_set_write(), packet_write_char(), RX_CHANNELNO, rx_channels, RX_DATA, RX_IDLE, RX_IGNORE, RX_LEN, send(), uarthw_can_send(), and uarthw_send().
Referenced by serial_delay().
{
    switch(rxstate) {
    case RX_IDLE:
        // no current packet
        if (rxdata == FS_SYNC) {
            // sync received
            // mirror the sync back
            // first flush all packets
            while (slots_used > 0) {
                send();
            }
            // can we send?
            while (!uarthw_can_send());
            // yes, send sync
            uarthw_send(FS_SYNC);
        } else
        if (rxdata == FS_REPLY || rxdata == FS_WRITE || rxdata == FS_EOF) {
            // note EOI flag
            current_is_eoi = rxdata;
            // start a reply handling
            rxstate = RX_LEN;
        } else {
            //led_toggle();
        }
        break;
    case RX_LEN:
        current_data_left = rxdata - 3;
        rxstate = RX_CHANNELNO;
        break;
    case RX_CHANNELNO:
        current_channelno = rxdata;
        rxstate = RX_IGNORE;    // fallback
        // find the current receive buffer
        for (uint8_t i = 0; i < NUMBER_OF_SLOTS; i++) {
            if (rx_channels[i].channelno == current_channelno) {
//if (current_is_eoi == FS_EOF && current_data_left == 0) led_toggle();
                current_channelpos = i;
                current_rxpacket = rx_channels[current_channelpos].rxpacket;
                if (packet_set_write(current_rxpacket, current_channelno,
                        current_is_eoi, current_data_left) >= 0) {
                    rxstate = RX_DATA;
                }
                break;
            }
        }
        // well, RX_IGNORE should not happen, but we have no means of telling anyone here
        if (current_data_left == 0) {
            // we are actually already done. do callback and set status to idle
            rx_channels[current_channelpos].callback(current_channelno,
                    (rxstate == RX_IGNORE) ? -1 : 0);
            rx_channels[current_channelpos].channelno = -1;
            rxstate = RX_IDLE;
        }
        break;
    case RX_DATA:
        packet_write_char(current_rxpacket, rxdata);
        // fallthrough
    case RX_IGNORE:
        current_data_left --;
//if (packet_get_contentlen(current_rxpacket) > 1) led_on();
        if (current_data_left <= 0) {
            rx_channels[current_channelpos].callback(current_channelno,
                    (rxstate == RX_IGNORE) ? -1 : 0);
            rx_channels[current_channelpos].channelno = -1;
            rxstate = RX_IDLE;
        }
        break;
    default:
        break;
    }
}
static int16_t read_char_from_packet (packet_t * buf) static
Definition at line 312 of file serial.c.
References packet_get_chan(), packet_get_contentlen(), packet_get_type(), packet_has_data(), packet_read_char(), TX_CHANNEL, TX_DATA, TX_IDLE, TX_LEN, and TX_TYPE.
Referenced by send().
{
        int16_t rv = -1;
        switch (txstate) {
        case TX_TYPE:
                txstate = TX_LEN;
                rv = 0xff & packet_get_type(buf);
                break;
        case TX_LEN:
                txstate = TX_CHANNEL;
                rv = (0xff & packet_get_contentlen(buf)) + 3;   // plus 2 to adhere to packet wire format
        break;
    case TX_CHANNEL:
        rv = 0xff & packet_get_chan(buf);
                if (packet_get_contentlen(buf) == 0) {
                        txstate = TX_IDLE;
                } else {
                        txstate = TX_DATA;
                }
                break;
        case TX_DATA:
                rv = 0xff & packet_read_char(buf);
                if (!packet_has_data(buf)) {
                        txstate = TX_IDLE;
                }
                break;
        default:
                break;
        }
        return rv;
}
static void send (void) static
Definition at line 356 of file serial.c.
References advance_slots(), read_char_from_packet(), uarthw_can_send(), and uarthw_send().
Referenced by push_data_to_packet(), serial_delay(), and serial_submit().
                       {
    while (slots_used > 0 && uarthw_can_send()) {
        // read data
        int16_t data = read_char_from_packet(slots[0]);
        if (data >= 0) {
            // send it
            uarthw_send(data);
            //led_on();
        } else {
            // packet empty, so get next slot
            advance_slots();
        }
    }
}
void serial_delay ()
send/receive data while waiting for some delay
Definition at line 453 of file serial.c.
References push_data_to_packet(), send(), and uarthw_receive().
Referenced by cmd_handler(), delayms(), main(), serial_flush(), serial_submit(), and serial_submit_call().
                    {
    // can we receive?
    int16_t data = uarthw_receive();
    while (data >= 0) {
        push_data_to_packet(0xff & data);
        // try next byte
        data = uarthw_receive();
    }
    // try to send
    send();
}
void serial_flush ()
flush the data out the UART
Definition at line 469 of file serial.c.
References serial_delay().
Referenced by term_flush().
                    {
    while (slots_used > 0) {
        serial_delay();
    }
}
provider_t* serial_init ()
initialize the UART
Definition at line 555 of file serial.c.
References NUMBER_OF_SLOTS, rx_channels, RX_IDLE, serial_provider, and TX_IDLE.
Referenced by main().
{
    slots_used = 0;
    for (int8_t i = NUMBER_OF_SLOTS-1; i >= 0; i--) {
        rx_channels[i].channelno = -1;
    }
    rxstate = RX_IDLE;
    txstate = TX_IDLE;
    // we should not register (at least for now, as when we are being
    // selected, the remote end does not know about it currently, as we
    // do not notify it. So open requests will be returned with an error
    //provider_register("FS", &serial_provider);
    return &serial_provider;
}
void serial_submit (void * epdata, packet_t * buf)
submit the contents of a buffer to the UART If buffer slot is available, return immediately. Otherwise wait until slot is available
Note: submitter must check packet_is_done() or friends before reuse or freeing the memory!
Definition at line 484 of file serial.c.
References buf, NUMBER_OF_SLOTS, send(), serial_delay(), slots_used, and TX_TYPE.
Referenced by serial_submit_call().
{
    // wait for slot free
    while (slots_used >= (NUMBER_OF_SLOTS-1)) {
        serial_delay();
    }
    // protect slot* by disabling the interrupt
    //cli();     - as slots are not handled in irq anymore
    // note: slots_used can only decrease until here, as this is the
    // only place to increase it, so there is no race from the while()
    // above to setting it here.
    slots[slots_used] = buf;
    slots_used++;
    if (slots_used == 1) {
        // no packet before, so need to start sending
        txstate = TX_TYPE;
        send();
        //led_on();
    }
    // enable interrupts again
    //sei();     - as slots are not handled in irq anymore
}
void serial_submit_call (void * epdata, int8_t channelno, packet_t * txbuf, packet_t * rxbuf, void(*)(int8_t channelno, int8_t errnum) callback)
Definition at line 521 of file serial.c.
References callback, packet_t::chan, channelno, debug_printf, NUMBER_OF_SLOTS, rx_channels, rxbuf, serial_delay(), and serial_submit().
{
    if (channelno < 0) {
        debug_printf("!!!! submit with channelno=%d\n", channelno);
    }
    if (txbuf->chan < 0) {
        debug_printf("!!!! submit with packet->chan=%d\n", txbuf->chan);
    }
    // check rx slot
    // wait / loop until receive buffer is being freed by interrupt routine
    int8_t channelpos = -1;
    while (channelpos < 0) {
        for (uint8_t i = 0; i < NUMBER_OF_SLOTS; i++) {
            if (rx_channels[i].channelno < 0) {
                channelpos = i;
                break;
            }
        }
        serial_delay();
    }
    rx_channels[channelpos].channelno = channelno;
    rx_channels[channelpos].rxpacket = rxbuf;
    rx_channels[channelpos].callback = callback;
    // send request
    serial_submit(epdata, txbuf);
}
void serial_sync ()
sync with the server
Definition at line 576 of file serial.c.
References FS_SYNC, uarthw_can_send(), and uarthw_send().
Referenced by main().
                   {
    // sync with the pc server
    // by sending 128 FS_SYNC bytes
    for (uint8_t cnt = 128; cnt > 0; cnt--) {
        while (!uarthw_can_send());
        uarthw_send(FS_SYNC);
    }
}
static int8_t to_provider (packet_t * p) static
convert PETSCII names to ASCII names
Definition at line 287 of file serial.c.
References buf, packet_get_buffer(), packet_get_contentlen(), and petscii_to_ascii().
{
    uint8_t *buf = packet_get_buffer(p);
    uint8_t len = packet_get_contentlen(p);
//debug_printf("CONVERT: len=%d, b=%s\n", len, buf);
    while (len > 0) {
//debug_puts("CONVERT: ");
//debug_putc(*buf); //debug_puthex(*buf);debug_puts("->");
        *buf = petscii_to_ascii(*buf);
//debug_putc(*buf);debug_puthex(*buf);debug_putcrlf();
        buf++;
        len--;
    }
    return 0;
}
Variable Documentation
void(* callback)(int8_t channelno, int8_t errnum)
Definition at line 119 of file serial.c.
Referenced by command_execute(), file_open(), file_submit_call(), and serial_submit_call().
int8_t channelno
Definition at line 117 of file serial.c.
Referenced by serial_submit_call().
int8_t current_channelno static
Definition at line 129 of file serial.c.
int8_t current_channelpos static
Definition at line 130 of file serial.c.
Referenced by push_data_to_packet().
int8_t current_data_left static
Definition at line 132 of file serial.c.
int8_t current_is_eoi static
Definition at line 133 of file serial.c.
packet_t* current_rxpacket static
Definition at line 131 of file serial.c.
uint8_t out[64] static
Definition at line 164 of file serial.c.
Referenced by directory_converter().
struct { ... } rx_channels[NUMBER_OF_SLOTS]
Referenced by push_data_to_packet(), serial_init(), and serial_submit_call().
packet_t* rxpacket
Definition at line 118 of file serial.c.
int8_t rxstate static
Definition at line 128 of file serial.c.
provider_t serial_provider
Initial value:
= {
    prov_assign,
    prov_free,
        serial_submit,
        serial_submit_call,
    directory_converter,
    to_provider
}
submit the contents of a buffer to the UART If buffer slot is available, return immediately. Otherwise wait until slot is available
Note: submitter must check buf_is_empty() for true or buf_wait_free() before reuse or freeing the memory!
Definition at line 90 of file serial.c.
Referenced by serial_init().
packet_t* slots[NUMBER_OF_SLOTS] static
Definition at line 103 of file serial.c.
uint8_t slots_used = 0 static
Definition at line 104 of file serial.c.
Referenced by serial_submit().
int8_t txstate static
Definition at line 106 of file serial.c.