XD2031 firmware: serial.h File Reference
serial.h File Reference
#include "provider.h"
Macros
#define BAUD 115200
Functions
provider_t * serial_init ()
void serial_sync ()
void serial_flush ()
void serial_delay ()
Variables
provider_t serial_provider
Macro Definition Documentation
#define BAUD 115200
high level serial line driver - adapting the packets to send and receive to the hardware-specific uart drivers
Definition at line 39 of file serial.h.
Function Documentation
void serial_delay ()
send/receive data while waiting for some delay
Definition at line 453 of file serial.c.
References push_data_to_packet(), send(), and uarthw_receive().
                    {
    // can we receive?
    int16_t data = uarthw_receive();
    while (data >= 0) {
        push_data_to_packet(0xff & data);
        // try next byte
        data = uarthw_receive();
    }
    // try to send
    send();
}
void serial_flush ()
flush the data out the UART
Definition at line 469 of file serial.c.
References serial_delay().
Referenced by term_flush().
                    {
    while (slots_used > 0) {
        serial_delay();
    }
}
provider_t* serial_init ()
initialize the UART
Definition at line 555 of file serial.c.
References NUMBER_OF_SLOTS, rx_channels, RX_IDLE, serial_provider, and TX_IDLE.
Referenced by main().
{
    slots_used = 0;
    for (int8_t i = NUMBER_OF_SLOTS-1; i >= 0; i--) {
        rx_channels[i].channelno = -1;
    }
    rxstate = RX_IDLE;
    txstate = TX_IDLE;
    // we should not register (at least for now, as when we are being
    // selected, the remote end does not know about it currently, as we
    // do not notify it. So open requests will be returned with an error
    //provider_register("FS", &serial_provider);
    return &serial_provider;
}
void serial_sync ()
sync with the server
Definition at line 576 of file serial.c.
References FS_SYNC, uarthw_can_send(), and uarthw_send().
Referenced by main().
                   {
    // sync with the pc server
    // by sending 128 FS_SYNC bytes
    for (uint8_t cnt = 128; cnt > 0; cnt--) {
        while (!uarthw_can_send());
        uarthw_send(FS_SYNC);
    }
}
Variable Documentation
provider_t serial_provider
submit the contents of a buffer to the UART If buffer slot is available, return immediately. Otherwise wait until slot is available
Note: submitter must check buf_is_empty() for true or buf_wait_free() before reuse or freeing the memory!
Definition at line 90 of file serial.c.
Referenced by serial_init().