XD2031 firmware: term.h File Reference
term.h File Reference
#include "provider.h"
Functions
void term_init ()
void term_set_endpoint (endpoint_t *ep)
void term_flush (void)
void term_putc (char c)
void term_putcrlf (void)
void term_puts (const char *)
void term_rom_puts (const char *)
void term_printf (const char *,...)
void term_rom_printf (const char *,...)
Function Documentation
void term_flush (void)
Definition at line 57 of file term.c.
References nchars, send(), and serial_flush().
Referenced by debug_putcrlf().
                  {
    if (nchars > 0) {
        // has not been sent with the last char
        // flush
        if (endpoint != NULL) {
            send();
        }
    }
    serial_flush();
}
void term_init ()
Definition at line 178 of file term.c.
References buf, nchars, packet_init(), and TERM_BUFFER_LENGTH.
Referenced by main().
                 {
    endpoint = NULL;
    nchars = 0;
    packet_init(&termpack, TERM_BUFFER_LENGTH, (uint8_t*)buf);
}
void term_printf (const char * , ...)
Definition at line 152 of file term.c.
References pbuf, TERM_BUFFER_LENGTH, and term_puts().
Referenced by main().
{
    va_list args;
    va_start( args, format );
    vsnprintf(pbuf, TERM_BUFFER_LENGTH, format, args );
    pbuf[TERM_BUFFER_LENGTH-1] = 0; // just in case
    term_puts(pbuf);
}
void term_putc (char c)
Definition at line 68 of file term.c.
References buf, nchars, packet_wait_done(), send(), and TERM_BUFFER_LENGTH.
Referenced by debug_putc(), and term_putcrlf().
                       {
    // wait if buffer is still being sent
    packet_wait_done(&termpack);
    if (nchars < TERM_BUFFER_LENGTH) {
        buf[nchars] = c;
        nchars++;
    }
    if (nchars >= TERM_BUFFER_LENGTH) {
        if (endpoint != NULL) {
            send();
        }
    }
}
void term_putcrlf (void)
Definition at line 85 of file term.c.
References nchars, send(), and term_putc().
Referenced by debug_putcrlf(), ListVersion(), and main().
                    {
    term_putc('\r');
    term_putc('\n');
    if (nchars > 0) {
        // has not been sent with the last char
        // flush
        if (endpoint != NULL) {
            send();
        }
    }
}
void term_puts (const char * str)
Note that this function expects its parameter in RAM
Definition at line 128 of file term.c.
References buf, nchars, packet_wait_done(), send(), and TERM_BUFFER_LENGTH.
Referenced by term_printf(), and term_rom_printf().
{
    packet_wait_done(&termpack);
    uint8_t len = strlen(str);
    if (len >= TERM_BUFFER_LENGTH) {
        // cut, can't send more bytes anyway
        len = TERM_BUFFER_LENGTH;
    }
    if ((nchars + len) >= TERM_BUFFER_LENGTH) {
        if (endpoint == NULL) {
            // no way we can print that now
            return;
        }
        send();
    }
    packet_wait_done(&termpack);
    memcpy(buf+nchars, str, len);
    nchars += len;
}
void term_rom_printf (const char * , ...)
Definition at line 163 of file term.c.
References pbuf, rom_vsnprintf, TERM_BUFFER_LENGTH, and term_puts().
{
    va_list args;
    va_start( args, rom_format );
    rom_vsnprintf(pbuf, TERM_BUFFER_LENGTH, rom_format, args );
    pbuf[TERM_BUFFER_LENGTH-1] = 0; // just in case
    term_puts(pbuf);
}
void term_rom_puts (const char * rom_str)
Note that this function expects its parameter in ROM
Definition at line 101 of file term.c.
References buf, nchars, packet_wait_done(), rom_memcpy, rom_strlen, send(), and TERM_BUFFER_LENGTH.
Referenced by ListVersion().
{
    packet_wait_done(&termpack);
    uint8_t len = rom_strlen(rom_str);
    if (len >= TERM_BUFFER_LENGTH) {
        // cut, can't send more bytes anyway
        len = TERM_BUFFER_LENGTH;
    }
    if ((nchars + len) >= TERM_BUFFER_LENGTH) {
        if (endpoint == NULL) {
            // no way we can print that now
            return;
        }
        send();
    }
    packet_wait_done(&termpack);
    rom_memcpy(buf+nchars, rom_str, len);
    nchars += len;
}
void term_set_endpoint (endpoint_t * ep)
Definition at line 174 of file term.c.
Referenced by main().
{
    endpoint = _endpoint;
}