XD2031 firmware: term.c File Reference
term.c File Reference
#include <inttypes.h>
#include <stdarg.h>
#include <string.h>
#include <stdio.h>
#include "packet.h"
#include "term.h"
#include "serial.h"
#include "wireformat.h"
#include "mem.h"
#include "led.h"
Macros
#define TERM_BUFFER_LENGTH 129
Functions
static void send ()
void term_flush ()
void term_putc (char c)
void term_putcrlf ()
void term_rom_puts (const char *rom_str)
void term_puts (const char *str)
void term_printf (const char *format,...)
void term_rom_printf (const char *rom_format,...)
void term_set_endpoint (endpoint_t *_endpoint)
void term_init ()
Variables
static char buf [TERM_BUFFER_LENGTH]
static char pbuf [TERM_BUFFER_LENGTH]
static uint8_t nchars
static endpoint_t * endpoint
static packet_t termpack
Macro Definition Documentation
#define TERM_BUFFER_LENGTH 129
Definition at line 39 of file term.c.
Referenced by term_init(), term_printf(), term_putc(), term_puts(), term_rom_printf(), and term_rom_puts().
Function Documentation
static void send (void) static
Definition at line 48 of file term.c.
References FS_TERM, nchars, packet_set_filled(), endpoint_t::provdata, endpoint_t::provider, and provider_t::submit.
Referenced by term_flush(), term_putc(), term_putcrlf(), term_puts(), and term_rom_puts().
                   {
    // tell the packet what's in the buffer to be read
    // nchars are in the buffer to be sent; channel is -1 (for terminal)
    packet_set_filled(&termpack, 0xfe, FS_TERM, nchars);
    endpoint->provider->submit(endpoint->provdata, &termpack);
    nchars = 0;
}
void term_flush (void)
Definition at line 57 of file term.c.
References nchars, send(), and serial_flush().
Referenced by debug_putcrlf().
                  {
    if (nchars > 0) {
        // has not been sent with the last char
        // flush
        if (endpoint != NULL) {
            send();
        }
    }
    serial_flush();
}
void term_init ()
Definition at line 178 of file term.c.
References buf, nchars, packet_init(), and TERM_BUFFER_LENGTH.
Referenced by main().
                 {
    endpoint = NULL;
    nchars = 0;
    packet_init(&termpack, TERM_BUFFER_LENGTH, (uint8_t*)buf);
}
void term_printf (const char * format, ...)
Definition at line 152 of file term.c.
References pbuf, TERM_BUFFER_LENGTH, and term_puts().
Referenced by main().
{
    va_list args;
    va_start( args, format );
    vsnprintf(pbuf, TERM_BUFFER_LENGTH, format, args );
    pbuf[TERM_BUFFER_LENGTH-1] = 0; // just in case
    term_puts(pbuf);
}
void term_putc (char c)
Definition at line 68 of file term.c.
References buf, nchars, packet_wait_done(), send(), and TERM_BUFFER_LENGTH.
Referenced by debug_putc(), and term_putcrlf().
                       {
    // wait if buffer is still being sent
    packet_wait_done(&termpack);
    if (nchars < TERM_BUFFER_LENGTH) {
        buf[nchars] = c;
        nchars++;
    }
    if (nchars >= TERM_BUFFER_LENGTH) {
        if (endpoint != NULL) {
            send();
        }
    }
}
void term_putcrlf (void)
Definition at line 85 of file term.c.
References nchars, send(), and term_putc().
Referenced by debug_putcrlf(), ListVersion(), and main().
                    {
    term_putc('\r');
    term_putc('\n');
    if (nchars > 0) {
        // has not been sent with the last char
        // flush
        if (endpoint != NULL) {
            send();
        }
    }
}
void term_puts (const char * str)
Note that this function expects its parameter in RAM
Definition at line 128 of file term.c.
References buf, nchars, packet_wait_done(), send(), and TERM_BUFFER_LENGTH.
Referenced by term_printf(), and term_rom_printf().
{
    packet_wait_done(&termpack);
    uint8_t len = strlen(str);
    if (len >= TERM_BUFFER_LENGTH) {
        // cut, can't send more bytes anyway
        len = TERM_BUFFER_LENGTH;
    }
    if ((nchars + len) >= TERM_BUFFER_LENGTH) {
        if (endpoint == NULL) {
            // no way we can print that now
            return;
        }
        send();
    }
    packet_wait_done(&termpack);
    memcpy(buf+nchars, str, len);
    nchars += len;
}
void term_rom_printf (const char * rom_format, ...)
Definition at line 163 of file term.c.
References pbuf, rom_vsnprintf, TERM_BUFFER_LENGTH, and term_puts().
{
    va_list args;
    va_start( args, rom_format );
    rom_vsnprintf(pbuf, TERM_BUFFER_LENGTH, rom_format, args );
    pbuf[TERM_BUFFER_LENGTH-1] = 0; // just in case
    term_puts(pbuf);
}
void term_rom_puts (const char * rom_str)
Note that this function expects its parameter in ROM
Definition at line 101 of file term.c.
References buf, nchars, packet_wait_done(), rom_memcpy, rom_strlen, send(), and TERM_BUFFER_LENGTH.
Referenced by ListVersion().
{
    packet_wait_done(&termpack);
    uint8_t len = rom_strlen(rom_str);
    if (len >= TERM_BUFFER_LENGTH) {
        // cut, can't send more bytes anyway
        len = TERM_BUFFER_LENGTH;
    }
    if ((nchars + len) >= TERM_BUFFER_LENGTH) {
        if (endpoint == NULL) {
            // no way we can print that now
            return;
        }
        send();
    }
    packet_wait_done(&termpack);
    rom_memcpy(buf+nchars, rom_str, len);
    nchars += len;
}
void term_set_endpoint (endpoint_t * _endpoint)
Definition at line 174 of file term.c.
Referenced by main().
{
    endpoint = _endpoint;
}
Variable Documentation
char buf[TERM_BUFFER_LENGTH] static
Definition at line 41 of file term.c.
Referenced by channel_open(), serial_submit(), term_init(), term_putc(), term_puts(), term_rom_puts(), and to_provider().
endpoint_t* endpoint static
Definition at line 45 of file term.c.
uint8_t nchars static
Definition at line 43 of file term.c.
Referenced by send(), term_flush(), term_init(), term_putc(), term_putcrlf(), term_puts(), and term_rom_puts().
char pbuf[TERM_BUFFER_LENGTH] static
Definition at line 42 of file term.c.
Referenced by term_printf(), and term_rom_printf().
packet_t termpack static
Definition at line 46 of file term.c.