XD2031 firmware: avr/uarthw.c File Reference
uarthw.c File Reference
#include "config.h"
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/pgmspace.h>
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <util/delay.h>
#include "compat.h"
#include "uarthw.h"
#include "led.h"
Macros
#define BUFFER_SIZE 128
#define BUFFER_SIZE_MASK 0x7f
#define BUFFER_NEXT(p) ((p + 1) & BUFFER_SIZE_MASK)
Functions
static void _uart_enable_sendisr ()
int8_t uarthw_can_send ()
void uarthw_send (int8_t data)
int16_t uarthw_receive ()
void uarthw_init ()
Variables
volatile int8_t txbuf [BUFFER_SIZE]
volatile uint8_t tx_wp
volatile uint8_t tx_rp
volatile int8_t rxbuf [BUFFER_SIZE]
volatile uint8_t rx_wp
volatile uint8_t rx_rp
volatile uint8_t rx_err
Macro Definition Documentation
#define BUFFER_NEXT (p) ((p + 1) & BUFFER_SIZE_MASK)
Definition at line 49 of file uarthw.c.
Referenced by uarthw_can_send(), uarthw_receive(), and uarthw_send().
#define BUFFER_SIZE 128
UART backend provider for the channels
Definition at line 47 of file uarthw.c.
#define BUFFER_SIZE_MASK 0x7f
Definition at line 48 of file uarthw.c.
Function Documentation
static void _uart_enable_sendisr () static
Definition at line 110 of file uarthw.c.
Referenced by uarthw_send().
{
        UCSRB |= (1<<UDRIE);          // UDRE Interrupt ein
}
int8_t uarthw_can_send ()
when returns true, there is space in the uart send buffer, so uarthw_send(...) can be called with a byte to send
Definition at line 75 of file uarthw.c.
References BUFFER_NEXT, tx_rp, and tx_wp.
Referenced by push_data_to_packet(), send(), and serial_sync().
{
    // check for wrap-around to read pointer
    uint8_t tmp = BUFFER_NEXT(tx_wp);
    return (tmp != tx_rp) ? 1 : 0;
}
void uarthw_init ()
interrupt for data send register empty
Note that it does not block other interrupts - most specifically the one we need for ATN handling.
That means that this interrupt, plus all other interrupt routines must be short enough to be done between two of the UDRE interrupts
ISR(USART_UDRE_vect) { if (tx_wp != tx_rp) { UDR = txbuf[tx_rp];
tx_rp = BUFFER_NEXT(tx_rp);
allow other interrupts from now, esp. the ATN interrupt sei(); }
if (tx_wp == tx_rp) { no more data available Disable ISR UCSRB &= ~_BV(UDRIE); } } interrupt for received data
Again note that this interrupt routine runs without other interrupts blocked.
ISR(USART_RXC_vect) { rxbuf[rx_wp] = UDR;
allow other interrupts from now, esp. the ATN interrupt sei();
uint8_t tmp = BUFFER_NEXT(rx_wp); if (tmp == rx_rp) { buffer overflow rx_err++; led_on(); } else { rx_wp = tmp; } }
Definition at line 170 of file uarthw.c.
References BAUD, F_CPU, rx_rp, rx_wp, tx_rp, and tx_wp.
Referenced by main().
                   {
    // tx ring buffer init
    tx_wp = 0;
    tx_rp = 0;
    // rx ring buffer init
    rx_wp = 0;
    rx_rp = 0;
    // init UART
        UCSRB = _BV(TXEN);              // TX aktiv
        UCSRB |= _BV(RXEN);             // RX aktivieren
        UBRRL = (uint8_t)(F_CPU/(BAUD*16L))-1;          // Baudrate festlegen
        UBRRH = (uint8_t)((F_CPU/(BAUD*16L))-1)>>8;     // Baudrate festlegen
        UCSRB |= _BV(RXCIE);            // UART Interrupt bei Datenempfang komplett
        //UCSRB |= _BV(UDRIE);          // UART Interrupt bei Senderegister leer
        //UCSRB |= _BV(TXCIE);          // UART Interrupt bei Sendevorgang beendet
}
int16_t uarthw_receive ()
receive a byte from the receive buffer Returns -1 when no byte available
Definition at line 94 of file uarthw.c.
References BUFFER_NEXT, rx_rp, rx_wp, and rxbuf.
Referenced by serial_delay().
{
    if (rx_wp == rx_rp) {
        // no data available
        return -1;
    }
    int16_t data = 0xff & rxbuf[rx_rp];
    rx_rp = BUFFER_NEXT(rx_rp);
    return data;
}
void uarthw_send (int8_t data)
submit a byte to the send buffer
Definition at line 84 of file uarthw.c.
References _uart_enable_sendisr(), BUFFER_NEXT, tx_wp, and txbuf.
Referenced by push_data_to_packet(), send(), and serial_sync().
{
    txbuf[tx_wp] = data;
    tx_wp = BUFFER_NEXT(tx_wp);
    _uart_enable_sendisr();
}
Variable Documentation
volatile uint8_t rx_err
Definition at line 63 of file uarthw.c.
volatile uint8_t rx_rp
Definition at line 62 of file uarthw.c.
Referenced by uarthw_init(), and uarthw_receive().
volatile uint8_t rx_wp
Definition at line 61 of file uarthw.c.
Referenced by uarthw_init(), and uarthw_receive().
volatile int8_t rxbuf[BUFFER_SIZE]
Definition at line 60 of file uarthw.c.
Referenced by serial_submit_call(), and uarthw_receive().
volatile uint8_t tx_rp
Definition at line 57 of file uarthw.c.
Referenced by uarthw_can_send(), and uarthw_init().
volatile uint8_t tx_wp
Definition at line 56 of file uarthw.c.
Referenced by uarthw_can_send(), uarthw_init(), and uarthw_send().
volatile int8_t txbuf[BUFFER_SIZE]
Definition at line 55 of file uarthw.c.
Referenced by uarthw_send().