XD2031 firmware: xs1541/ieeehw.c File Reference
ieeehw.c File Reference
#include "ieeehw.h"
Functions
static void ieee_interrupts_init (void)
static void set_atn_irq (uint8_t x)
void ieeehw_setup ()
void ieeehw_init ()
Variables
uint8_t is_atna = 0
uint8_t is_ndacout = 0
uint8_t is_nrfdout = 0
Function Documentation
static void ieee_interrupts_init (void) static
Definition at line 38 of file ieeehw.c.
References IEEE_PCINT, and IEEE_PCMSK.
Referenced by ieeehw_init().
{
  /* clear interrupt flag */
  PCIFR |= _BV(PCIF3);
  /* enable ATN in pin change enable mask
  * translates to
  *   PCMSK3 |= _BV(PCINT27)
  * which is ok for PD3
  */
  IEEE_PCMSK |= _BV(IEEE_PCINT);
  /* Enable pin change interrupt 3 (PCINT31..24) */
  PCICR |= _BV(PCIE3);
  //debug_putps("Done init ieee ints"); debug_putcrlf();
}
void ieeehw_init (void)
Definition at line 98 of file ieeehw.c.
References IEEE_DDR_DC, IEEE_DDR_TE, ieee_interrupts_init(), IEEE_PIN_DC, IEEE_PIN_TE, IEEE_PORT_DC, IEEE_PORT_TE, ieeehw_setup(), and set_atn_irq().
                   {
    // disable ATN interrupt
    set_atn_irq(0);
    // clear IEEE lines
    ieeehw_setup();
    // start ATN interrupt handling
    ieee_interrupts_init();
}
void ieeehw_setup (void)
Definition at line 88 of file ieeehw.c.
References atnahi(), clrd(), davhi(), eoihi(), ndachi(), and nrfdhi().
                    {
    // clear IEEE lines
    atnahi();
    clrd();
    davhi();
    nrfdhi();
    ndachi();
    eoihi();
}
static void set_atn_irq (uint8_t x) static
Definition at line 56 of file ieeehw.c.
References debug_putcrlf(), debug_puthex(), IEEE_PCINT, and IEEE_PCMSK.
Referenced by ieeehw_init().
{
#if DEBUG
  debug_putps("ATN_IRQ:"); debug_puthex(x); debug_putcrlf();
#endif
  if (x)
    IEEE_PCMSK |= _BV(IEEE_PCINT);
  else
    IEEE_PCMSK &= (uint8_t) ~_BV(IEEE_PCINT);
}
Variable Documentation
uint8_t is_atna = 0
Definition at line 30 of file ieeehw.c.
uint8_t is_ndacout = 0
Definition at line 31 of file ieeehw.c.
uint8_t is_nrfdout = 0
Definition at line 32 of file ieeehw.c.