XD2031 firmware: xs1541/ieeehw.h File Reference
ieeehw.h File Reference
#include <stdint.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include "device.h"
Macros
#define E_OK 0
#define E_ATN 1
#define E_EOI 2
#define E_TIME 4
#define E_BRK 5
#define E_NODEV 6
Functions
static void nrfdlo ()
static uint8_t atnislo ()
static uint8_t atnishi ()
static void ndaclo ()
static void ndachi ()
static void nrfdhi ()
static uint8_t ndacislo ()
static uint8_t ndacishi ()
static uint8_t nrfdislo ()
static uint8_t nrfdishi ()
static void davlo ()
static void davhi ()
static uint8_t davislo ()
static uint8_t davishi ()
static void eoilo ()
static void eoihi ()
static uint8_t eoiislo ()
static uint8_t eoiishi ()
static void atnahi ()
static void atnalo ()
static void clrd (void)
static void wrd (uint8_t data)
static uint8_t rdd (void)
void ieeehw_init ()
void ieeehw_setup ()
static void settx (void)
static void setidle (void)
static void setrx (void)
Variables
uint8_t is_atna
uint8_t is_nrfdout
uint8_t is_ndacout
Macro Definition Documentation
#define E_ATN 1
Definition at line 37 of file ieeehw.h.
#define E_BRK 5
Definition at line 40 of file ieeehw.h.
#define E_EOI 2
Definition at line 38 of file ieeehw.h.
#define E_NODEV 6
Definition at line 41 of file ieeehw.h.
#define E_OK 0
Definition at line 36 of file ieeehw.h.
#define E_TIME 4
Definition at line 39 of file ieeehw.h.
Function Documentation
static void atnahi (void) inline static
Definition at line 169 of file ieeehw.h.
References is_atna.
{
    is_atna = 0;
}
static void atnalo (void) inline static
Definition at line 174 of file ieeehw.h.
References is_atna, is_ndacout, is_nrfdout, ndaclo(), and nrfdlo().
{
    if (!is_nrfdout) {
        nrfdlo();
    }
    if (!is_ndacout) {
        ndaclo();
    }
    is_atna = 1;
}
static uint8_t atnishi (void) inline static
Definition at line 61 of file ieeehw.h.
References IEEE_INPUT_ATN, and IEEE_PIN_ATN.
Referenced by ndachi(), and nrfdhi().
{
    return (IEEE_INPUT_ATN & _BV(IEEE_PIN_ATN));
}
static uint8_t atnislo (void) inline static
Definition at line 57 of file ieeehw.h.
References IEEE_INPUT_ATN, and IEEE_PIN_ATN.
{
    return !(IEEE_INPUT_ATN & _BV(IEEE_PIN_ATN));
}
static void clrd (void) inline static
Definition at line 186 of file ieeehw.h.
References IEEE_D_DDR, and IEEE_D_PORT.
{
    IEEE_D_DDR = 0;
    IEEE_D_PORT = 0xff;
}
static void davhi (void) inline static
Definition at line 132 of file ieeehw.h.
References IEEE_DDR_DAV, IEEE_PIN_DAV, and IEEE_PORT_DAV.
Referenced by setidle(), setrx(), and settx().
{
      IEEE_DDR_DAV &= (uint8_t)~_BV(IEEE_PIN_DAV);      // DAV as input
      IEEE_PORT_DAV |= _BV(IEEE_PIN_DAV);               // Enable pull-up
}
static uint8_t davishi (void) inline static
Definition at line 141 of file ieeehw.h.
References IEEE_INPUT_DAV, and IEEE_PIN_DAV.
{
    return (IEEE_INPUT_DAV & _BV(IEEE_PIN_DAV));
}
static uint8_t davislo (void) inline static
Definition at line 137 of file ieeehw.h.
References IEEE_INPUT_DAV, and IEEE_PIN_DAV.
{
    return !(IEEE_INPUT_DAV & _BV(IEEE_PIN_DAV));
}
static void davlo (void) inline static
Definition at line 127 of file ieeehw.h.
References IEEE_DDR_DAV, IEEE_PIN_DAV, and IEEE_PORT_DAV.
{
      IEEE_PORT_DAV &= (uint8_t)~_BV(IEEE_PIN_DAV);     // DAV low
      IEEE_DDR_DAV |= _BV(IEEE_PIN_DAV);                // DAV as output
}
static void eoihi (void) inline static
Definition at line 152 of file ieeehw.h.
References IEEE_DDR_EOI, IEEE_PIN_EOI, and IEEE_PORT_EOI.
Referenced by setidle(), setrx(), and settx().
{
    IEEE_DDR_EOI &= (uint8_t)~_BV(IEEE_PIN_EOI);    // EOI as input
    IEEE_PORT_EOI |= (uint8_t)_BV(IEEE_PIN_EOI);    // Enable pull-up
}
static uint8_t eoiishi (void) inline static
Definition at line 161 of file ieeehw.h.
References IEEE_INPUT_EOI, and IEEE_PIN_EOI.
{
    return (IEEE_INPUT_EOI & _BV(IEEE_PIN_EOI));
}
static uint8_t eoiislo (void) inline static
Definition at line 157 of file ieeehw.h.
References IEEE_INPUT_EOI, and IEEE_PIN_EOI.
{
    return !(IEEE_INPUT_EOI & _BV(IEEE_PIN_EOI));
}
static void eoilo (void) inline static
Definition at line 147 of file ieeehw.h.
References IEEE_DDR_EOI, IEEE_PIN_EOI, and IEEE_PORT_EOI.
{
    IEEE_PORT_EOI &= (uint8_t)~_BV(IEEE_PIN_EOI);   // EOI low
    IEEE_DDR_EOI |= (uint8_t) _BV(IEEE_PIN_EOI);    // EOI as output
}
void ieeehw_init ()
Definition at line 79 of file ieeehw.c.
References IEEE_DDR_DC, IEEE_DDR_TE, ieee_interrupts_init(), IEEE_PIN_DC, IEEE_PIN_TE, IEEE_PORT_DC, IEEE_PORT_TE, ieeehw_setup(), and set_atn_irq().
Referenced by main().
                   {
    IEEE_DDR_TE |= _BV(IEEE_PIN_TE);                // Define TE as output
    IEEE_PORT_TE &= (uint8_t) ~ _BV(IEEE_PIN_TE);   // TE=0
    IEEE_DDR_DC |= _BV(IEEE_PIN_DC);                // Define DC as output
    IEEE_PORT_DC |= _BV(IEEE_PIN_DC);               // DC=1 (device)
    // disable ATN interrupt
    set_atn_irq(0);
    // clear IEEE lines
    ieeehw_setup();
    // start ATN interrupt handling
    ieee_interrupts_init();
}
void ieeehw_setup ()
Definition at line 69 of file ieeehw.c.
References atnahi(), clrd(), davhi(), eoihi(), ndachi(), and nrfdhi().
Referenced by ieee_mainloop_iteration(), ieeehw_init(), and ieeehwi_init().
                    {
    // clear IEEE lines
    atnahi();
    clrd();
    davhi();
    nrfdhi();
    ndachi();
    eoihi();
}
static void ndachi (void) inline static
Definition at line 80 of file ieeehw.h.
References atnishi(), IEEE_DDR_NDAC, IEEE_PIN_NDAC, IEEE_PORT_NDAC, is_atna, and is_ndacout.
Referenced by setidle(), and settx().
{
    // disable interrupt to avoid race condition
    // of ATN irq between the atnishi() check and
    // setting NDAC lo
    cli();
    if (atnishi() || is_atna) {
            IEEE_DDR_NDAC &= (uint8_t)~_BV(IEEE_PIN_NDAC);    // NDAC as input
            IEEE_PORT_NDAC |= _BV(IEEE_PIN_NDAC);             // Enable pull-up
    }
    // allow interrupt again
    sei();
    is_ndacout = 1;
}
static uint8_t ndacishi (void) inline static
Definition at line 112 of file ieeehw.h.
References IEEE_INPUT_NDAC, and IEEE_PIN_NDAC.
{
    return (IEEE_INPUT_NDAC & _BV(IEEE_PIN_NDAC));
}
static uint8_t ndacislo (void) inline static
Definition at line 108 of file ieeehw.h.
References IEEE_INPUT_NDAC, and IEEE_PIN_NDAC.
{
    return !(IEEE_INPUT_NDAC & _BV(IEEE_PIN_NDAC));
}
static void ndaclo (void) inline static
Definition at line 68 of file ieeehw.h.
References IEEE_DDR_NDAC, IEEE_PIN_NDAC, IEEE_PORT_NDAC, and is_ndacout.
Referenced by atnalo().
{
        IEEE_PORT_NDAC &= (uint8_t)~_BV(IEEE_PIN_NDAC);   // NDAC low
        IEEE_DDR_NDAC |= _BV(IEEE_PIN_NDAC);              // NDAC as output
    is_ndacout = 0;
}
static void nrfdhi (void) inline static
Definition at line 94 of file ieeehw.h.
References atnishi(), IEEE_DDR_NRFD, IEEE_PIN_NRFD, IEEE_PORT_NRFD, is_atna, and is_nrfdout.
Referenced by setidle(), and settx().
{
    // disable interrupt to avoid race condition
    // of ATN irq between the atnishi() check and
    // setting NDAC lo
    cli();
    if (atnishi() || is_atna) {
            IEEE_DDR_NRFD &= (uint8_t)~_BV(IEEE_PIN_NRFD);    // NRFD as input
            IEEE_PORT_NRFD |= _BV(IEEE_PIN_NRFD);             // Enable pull-up
    }
    // allow interrupt again
    sei();
    is_nrfdout = 1;
}
static uint8_t nrfdishi (void) inline static
Definition at line 121 of file ieeehw.h.
References IEEE_INPUT_NRFD, and IEEE_PIN_NRFD.
{
    return (IEEE_INPUT_NRFD & _BV(IEEE_PIN_NRFD));
}
static uint8_t nrfdislo (void) inline static
Definition at line 117 of file ieeehw.h.
References IEEE_INPUT_NRFD, and IEEE_PIN_NRFD.
{
    return !(IEEE_INPUT_NRFD & _BV(IEEE_PIN_NRFD));
}
static void nrfdlo (void) inline static
Definition at line 74 of file ieeehw.h.
References IEEE_DDR_NRFD, IEEE_PIN_NRFD, IEEE_PORT_NRFD, and is_nrfdout.
Referenced by atnalo().
{
        IEEE_PORT_NRFD &= (uint8_t)~_BV(IEEE_PIN_NRFD);   // NRFD low
        IEEE_DDR_NRFD |= (uint8_t) _BV(IEEE_PIN_NRFD);    // NRFD as output
    is_nrfdout = 0;
}
static uint8_t rdd (void) inline static
Definition at line 196 of file ieeehw.h.
References IEEE_D_PIN.
{
    return (uint8_t) ~ IEEE_D_PIN;
}
static void setidle (void) inline static
Definition at line 217 of file ieeehw.h.
References davhi(), eoihi(), ndachi(), and nrfdhi().
{
    nrfdhi();
    ndachi();
    davhi();
    eoihi();
}
static void setrx (void) inline static
Definition at line 226 of file ieeehw.h.
References davhi(), and eoihi().
{
    davhi();
    eoihi();
}
static void settx (void) inline static
Definition at line 208 of file ieeehw.h.
References davhi(), eoihi(), ndachi(), and nrfdhi().
{
    nrfdhi();
    ndachi();
    davhi();
    eoihi();
}
static void wrd (uint8_t data) inline static
Definition at line 191 of file ieeehw.h.
References IEEE_D_DDR, and IEEE_D_PORT.
{
    IEEE_D_DDR = data;
    IEEE_D_PORT = (uint8_t) ~ data;
}
Variable Documentation
uint8_t is_atna
Definition at line 35 of file ieeehw.c.
Referenced by atnahi(), atnalo(), ndachi(), and nrfdhi().
uint8_t is_ndacout
Definition at line 36 of file ieeehw.c.
Referenced by atnalo(), ndachi(), and ndaclo().
uint8_t is_nrfdout
Definition at line 37 of file ieeehw.c.
Referenced by atnalo(), nrfdhi(), and nrfdlo().